### ISSUE TITLE
Control In-Air Icon Rotation Speed

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#10]
This would mainly apply to the Cube and Ball gamemodes, and is something I have accidentally modified before using a weird combination of XBot and speedhacks. When I jumped with the cube on flat ground, it completed twice the rotations it would complete normally before landing. This actually looked silly and fun. Being able to decrease the rotation speed would be cool too.

This is more one of those fun features, just like RGB icons.

**Comment by absoIute** [comment]
added in v6.2-beta3!
