### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by TaurusGMD** [absoIute/Mega-Hack-Pro-Future#100]
Hi, Absolute! I recently bought MegaHack and have a problem with it. I am trying to download extensions via the extensions folder, but they are not defined in the megahack. The extensions folder contains run-info.dll and VolumeControl.dll
Sorry for the bad English, I am translating from Russian via Google Translate

**Comment by absoIute** [comment]
go to https://matcool.github.io/mods , download the minhook dll & put it in your GD folder
