### ISSUE TITLE
individualised scaling 

### ISSUE THREAD

**Issue by XylexPhD** [absoIute/Mega-Hack-Pro-Future#102]
I think it would be helpful to have a feature where if you scale an object that has scaled objects in it, it remembers what scale the objects were all at but resets their current size to be "1.00" and so scales them all down smoothly without any scale bugs or anything like that. idk if it would work like that but you get what I mean.

an example would be if there's 3 objects and one is scaled to 0.50, they'd all scale down at the same rate to say 0.5, then the object that was already at 0.5 gets scaled to 0.25? idk if this makes sense but yeah

thank you for your consideration!

**Comment by absoIute** [comment]
hey, this is what the 'set scale' button does in the creator tab! though it is bugged right now and doesn't work all the time so working on a fix

**Comment by XylexPhD** [comment]
Oh! Thanks lol, I'm still learning what everything does 😅

**Comment by Brittank88** [comment]
@XylexPhD In the meantime, BetterEdit makes scaling awesome and fixes multiscaling alignment bugs too.

**Comment by XylexPhD** [comment]
Okay, thanks!
