### ISSUE TITLE
NONGs Downloader

### ISSUE THREAD

**Issue by Squad897** [absoIute/Mega-Hack-Pro-Future#104]
I think it would be cool if the client could access some kind a database full of NONGs that are used in GD levels. Instead of having to go onto the internet to download the songs and put it into your GD Local files, I think it would be cool if you could do this through the mhv6 client. I think it could work by the client matching the ID of a level with one in a database, and then providing the download for the corresponding music when you first download the song for the level.

**Comment by Brittank88** [comment]
I was actually considering undertaking this as a project myself - a mapping between NG IDs and NONG source locations that can be downloaded from.

**Comment by Brittank88** [comment]
Should we leave this one open for now, @absoIute? I feel as if this would be a very cool addition, if I can come up with a good search tool for generating mappings like this.

**Comment by absoIute** [comment]
it'd be nice but it's not legally sound since you're basically linking to pirated MP3s, so the plan is to use Soundcloud's API when they open that up again since they have a good chunk of NONG songs uploaded by the original artist.

**Comment by Brittank88** [comment]
I did genuinely forget about the whole legal side of this. That's a very good point. Darn, that kinda ruins my mapping idea.

**Comment by succmydecc** [comment]
Come on, most big music brands wont go after someone like you @absoIute .

**Comment by Brittank88** [comment]
@succmydecc This has to be a joke, right? Have you seen the state of say, YouTube?

Please don't try to push Absolute to take legal chances like that. I doubt he'll budge and do something literally legally risky anyway.

**Comment by absoIute** [comment]
thanks, music labels can and will go after anyone infringing on them, it's not a risk worth taking

**Comment by Brittank88** [comment]
I'm going to re-link [this NONG downloading extension](https://github.com/paroxysms/nong-downloader-extension) here and make this the new pinned issue as opposed to #160.
