### ISSUE TITLE
Treasure Room Hack Issues

### ISSUE THREAD

**Issue by VIKI155** [absoIute/Mega-Hack-Pro-Future#107]

**Comment by VIKI155** [comment]
Treasure Hack Its not Working

**Comment by VIKI155** [comment]
video (Not just the best quality) : https://mega.nz/file/Ej4hBCbI#bPNwzrr82kAmqTk4nTVJ5z2podN3iC5Kj9TfaVfpcSI

**Comment by patrykchrymecki** [comment]
I'm pretty sure it only unlocks the treasure room but doesn't let you unlock chests without keys.

**Comment by Brittank88** [comment]
I guess Absolute can clarify the exact functionality of this bypass.

**Comment by absoIute** [comment]
treasure room bypass only unlocks the room, not the chest keys
