### ISSUE TITLE
CPS Counter | Bot Clicks

### ISSUE THREAD

**Issue by VIKI155** [absoIute/Mega-Hack-Pro-Future#108]

**Comment by Brittank88** [comment]
Could you describe this a bit better? Do you mean that the CPS counter should be able to register clicks from bots?

This may not be possible, given how bots work. Example: OBot actually enforces the positions of icons.

**Comment by VIKI155** [comment]
yes i think this

**Comment by absoIute** [comment]
this is a bug caused by the way I hook it, fixed for next update.

if you enable the cps counter & restart gd it should also work
