### ISSUE TITLE
Instant Mirror Portal

### ISSUE THREAD

**Issue by patrykchrymecki** [absoIute/Mega-Hack-Pro-Future#109]
{
            "name": "Instant Mirror Portal",
            "desc": "Makes reverse portals instant",
	    "cheat": true,
            "opcodes": [
	      {"addr": "0x20ACA3", "on": "C7 04 24 00 00 00 00", "off": "C7 04 24 00 00 00 3F"}
            ]
        },
(I know you can change "mirror speed" in variables but I found that after I got this.)

**Comment by Brittank88** [comment]
This is very cool still, though, if you can just set the speed, it seems a bit redundant (unless the speed value isn't saved? @absoIute? Sorry if this is a dumb question).

**Comment by absoIute** [comment]
yea, thanks, though it's already possible through variables -> player -> mirror speed -> save to 0!
