### ISSUE TITLE
Delete Start Positions

### ISSUE THREAD

**Issue by Kicek8632** [absoIute/Mega-Hack-Pro-Future#113]
This will delete all start positions in editor. With already set keybind for that will make it faster.
Also options with deleting furthest and recent start pos will make it better without finding them in level manually

**Comment by Brittank88** [comment]
There is already a button for deleting all in the vanilla game. Deleting first and last might be cool, but this feels too specific to add as its own feature (IMO).

If you're just wanting keybinds for deleting all start positions, BetterEdit has your back.

**Comment by absoIute** [comment]
^
