### ISSUE TITLE
Add pick up coins visually in practice mode

### ISSUE THREAD

**Issue by WEGFan** [absoIute/Mega-Hack-Pro-Future#12]
This can be helpful for levels having invisible free coins but you don't know you collected them in practice mode.

```json
{
    "name": "Pick Up Coins in Practice Mode",
    "desc": "",
    "opcodes": [
        {
            "addr": "0x204F10",
            "on": "90 90 90 90 90 90 90 90 90 90 90 90 90",
            "off": "80 BE 95 04 00 00 00 0F 85 DE 00 00 00"
        }
    ]
}
```

![unknown](https://user-images.githubusercontent.com/7558201/91641979-50191a00-ea5a-11ea-9ff3-48b0069c2ff6.png)

**Comment by Brittank88** [comment]
I love this idea. I really do.

**Comment by absoIute** [comment]
Will add soon, though I probably need to make things scrollable first because that Player tab is getting quite long

**Comment by absoIute** [comment]
added in v6.2.0-beta3, thanks!
