### ISSUE TITLE
Better Safe Mode

### ISSUE THREAD

**Issue by patrykchrymecki** [absoIute/Mega-Hack-Pro-Future#121]
So when you finish a level with safe mode on it will kick you out of the level it can be annoying sometimes.
So maybe Better Safe Mode could make it so it doesn't kick you out of the level?

Example:

	{
            "name": "Better Safe Mode",
            "desc": "Doesn't kick you out of levels when completed + disables progress, completion & verification of levels",
	    "cheat": true,
            "opcodes": [
                {"addr": "0x20A3B2", "on": "E9 9A 01 00 00 90 90", "off": "80 BB 94 04 00 00 00"},
                {"addr": "0x1FD40F", "on": "E9 13 06 00 00 90 90", "off": "83 B9 64 03 00 00 01"}
            ]
        },

**Comment by absoIute** [comment]
Implementation added for next update, thanks! It'll work how Noclip Accuracy's built-in Safe Mode works
