### ISSUE TITLE
In-built Macro Tab

### ISSUE THREAD

**Issue by DumbCaveSpider** [absoIute/Mega-Hack-Pro-Future#123]
## Mega Hack Pro 6 should add their own bot macro inside the hack instead of using third party like Echo or zBot etc.

I want the hack client to include like it own macro into the hack so I don't need to use Echo (a macro botting tool). Is it possible to add this feature and embeded it into the mega hack. This is so I don't have to install a third party program and inject it into the game as shown below.
![20210926180052_1](https://user-images.githubusercontent.com/56347227/134803260-d7146831-32ab-427d-8bb7-9e931bb51d48.jpg)

Can you add this feature into one (especially Echo). Thanks!

**Comment by patrykchrymecki** [comment]
https://github.com/absoIute/Mega-Hack-Pro-Future/issues/14

**Comment by absoIute** [comment]
Revisiting this, will look into adding a native bot either next update or the update after. It won't be as feature packed as other bots but should include basic features like frame-stepping (with backwards stepping)

**Comment by DumbCaveSpider** [comment]
> Revisiting this, will look into adding a native bot either next update or the update after. It won't be as feature packed as other bots but should include basic features like frame-stepping (with backwards stepping)

That's good enough for me. As long it can accurately navigate the level. I'm happy enough :)

**Comment by DumbCaveSpider** [comment]
> Revisiting this, will look into adding a native bot either next update or the update after. It won't be as feature packed as other bots but should include basic features like frame-stepping (with backwards stepping)

As long I includes basic features that the third party macro bot has, I'll be willing to test it. :)

**Comment by Brittank88** [comment]
> Revisiting this, will look into adding a native bot either next update or the update after. It won't be as feature packed as other bots but should include basic features like frame-stepping (with backwards stepping)

This sounds very exciting, though, also pursuing compat with existing bots would be extremely helpful, especially for those who have already purchased external bots and want to capitalise on all their features.

**Comment by absoIute** [comment]
Coming next update

**Comment by DumbCaveSpider** [comment]
Let's GOO!!
