### ISSUE TITLE
Auto-Pitch Feature

### ISSUE THREAD

**Issue by DaikonXD** [absoIute/Mega-Hack-Pro-Future#124]
Similar to how speedhack pitches songs based on speed when speedhack audio is enabled, add a feature that allows players to set a value to increase or decrease the pitch by. I see a lot of players pitching up or down songs, whether that be because they sound better, or to avoid copyright. Adding this into mega hack so that players don't need to use a program like audacity would be nice.

**Comment by absoIute** [comment]
Looking into pitching though FMOD makes it awkward to do so might be a while until it happens!

Not sure how effective that is at avoiding copyright these days though, song-detection algorithms have gotten a lot better

**Comment by absoIute** [comment]
Ready for next update, though limited to +/-1 octave since any more than that kills quality with FMOD

**Comment by Brittank88** [comment]
@absoIute For posterity - you said you were gonna try and apply the pitch multiple times to get around the octave limit?

Just wanna know if this should be reopened or if you've implemented that.

**Comment by absoIute** [comment]
I've decided to not include that after experimenting a bit, quality takes such a hit it's really just not worth it, so just gona experiment with other methods in the meantime

**Comment by CoderQCFromScraatch** [comment]
By, the way, what are the offsets/psuedocode you use to get Stable Pulse working? I have a GDPS (which for some reason doesn't load Mega Hack.)
