### ISSUE TITLE
Discord Rich Presence Bug

### ISSUE THREAD

**Issue by matsy190** [absoIute/Mega-Hack-Pro-Future#125]
There is a problem with the DiscordRich Presencefeature where it always displays my activity as Geometry Dash Browsing Menus, nothing else, even when the game is closed, I tried reinstalling GD but it did nothing. It even stays when I play a level, I have tried disabling the rich presence via the in-game menu, removing Geometry Dash from my Activity Status. Thanks in advance, -matsy
![image](https://user-images.githubusercontent.com/91593077/135225738-e9b7b4cd-4c39-43d6-b16c-f6a613710cf7.png)

**Comment by absoIute** [comment]
Check you don't have a sneaky background process that didn't close properly causing this.

**Comment by Brittank88** [comment]
I guess for now I'll mark this as closed - feel free to reopen if this keeps happening though.
