### ISSUE TITLE
Noclip Accuracy Damage Tint Colour

### ISSUE THREAD

**Issue by Fl1pNatic** [absoIute/Mega-Hack-Pro-Future#127]
I use noclip accuracy quite a lot, and I have this problem - Whenever I play levels with a lot of red in them(Hell levels) then it's kind of hard to see whether the screen tinted red because you hit something, or it's just pulse trigger.

Please add an option to change the color.

**Comment by absoIute** [comment]
Added in 7.0.0-beta1
