### ISSUE TITLE
Original Pulse Option For Recording Using Speedhack Audio

### ISSUE THREAD

**Issue by yoghurtbang** [absoIute/Mega-Hack-Pro-Future#132]
I was thinking maybe an option to allow you to revert to the original pulse patterns while using speedhack as when using very low speed it tends to pulse so much more than originally.

**Comment by Brittank88** [comment]
I also worry about the implications of making speedhacked runs even harder to identify.

**Comment by yoghurtbang** [comment]
> 
> 
> I also worry about the implications of making speedhacked runs even harder to identify.

I guess that is true.

I'm not a developer so I'm not completely sure how pulses are stored or even measured but my thoughts are instead of slowing the tempo down as well as lowering the pitch it can also slow the overall speed (without pitch changes) and detect the pulses from that and layer it over somehow.
I do think hacking may be less detectable but to be honest it's got to the point that unless you have raw footage and clicks the chances of it being accepted ( on major lists (demon list, challenge list etc)) AND how bots can completely bypass the pulses I don't believe the effect of it will be as big as it was a couple of years ago.
Also, there are some bots out there (replay bot) that can also fix the pulsing in playback (as I've heard) so chances are it already exists.

The main reason I'd want it is for showcasing purposes as when recording a macro in high quality you tend to need to slow the game down (usually to 0.25x speed or under) the pulses will instead play a lot bigger which when recording in such low speed is obvious and takes away how the level would be played or seen as played legit.

Again, not sure how it would be implemented or what the effect of it could be but I do think it could be handy for showcasers if implemented especially as it's becoming a much bigger part of geometry dash altogether.

I apologise for the paragraphs lol.

**Comment by absoIute** [comment]
#124 + Stable Pulse will achieve a close enough effect to this
