### ISSUE TITLE
Color 1 / Color 2 Pulse w/ BG / Pastel

### ISSUE THREAD

**Issue by LinkeddGD** [absoIute/Mega-Hack-Pro-Future#133]
Would be cool to see color 1 and 2 be able to pulse with the background. What I mean by this is to have another option in music flash, to also have bg, fade, pastel and rbg as options too. Could be cool idk

**Comment by absoIute** [comment]
Will add this as a sort of inverse fade, so the larger the music delta is, the less of a flash occurs

**Comment by absoIute** [comment]
Implemented, ready for next update
