### ISSUE TITLE
Input Display

### ISSUE THREAD

**Issue by RealBikas** [absoIute/Mega-Hack-Pro-Future#134]
There should be a "hack" that would create a circle in a corner of the screen (the specific corner could be chosen by the player), and everytime the player clicked/tapped, it would change color (both colors could also be customizable by the player). This would be great for recordings where u can't hear the mouseclicks, though it still wouldn't prove their legitemacy. The only thing I can't think of is how it would work on 2 player mode.

**Comment by Brittank88** [comment]
Btw if you have NohBoard here is a keyboard layout I made for GD: [Brittank88.zip](https://github.com/absoIute/Mega-Hack-Pro-Future/files/7333839/Brittank88.zip)

**Comment by absoIute** [comment]
Decided against it a bit ago since it's redundant with the CPS counter
