### ISSUE TITLE
"Lawful" YBot-Esque In-Overlay Macro Recorder / Player

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#14]
This is certainly a bigger thing to implement.

It would have the same functions as YBot (including the ability to record runs in practice mode), except that any time a macro is being played there is some small watermark or similar feature present to prevent these runs for being used for immoral purposes.

The macro data would have to be stored in such a way that they can't just be transferred to another macro program for playback.

Recording macros would of course need to be compatible with Mega Hack Pro's speedhack.

**Comment by absoIute** [comment]
Will be pretty bare-bones if added & will come with an appropriate "I am using a macro" watermark. Cannot guarantee that macros can't be transferred to other similar programs however.

**Comment by Brittank88** [comment]
Makes me wonder if there's a way to obfuscate the macro data using some key that the user would never be able to easily get access to unless they really knew what they were doing.

**Comment by absoIute** [comment]
API for hacks like YBot is implemented for v6.2
