### ISSUE TITLE
Hide All Objects, Show Only Physical Objects

### ISSUE THREAD

**Issue by BlockOG** [absoIute/Mega-Hack-Pro-Future#148]
The hide all objects hack would just... hide all objects
The show only objects with hitboxes hack would show only the objects which have a hitbox with no effects like color, opacity or anything, this hack would not be affected by the hid all objects hack
And also maybe use this for an auto layout hack out of a level, would be cool
This is useful for botting levels for example

**Comment by absoIute** [comment]
The layout-only option would be good for practicing levels & creating macros most likely, I'll probably add it when I add macros to Mega Hack since this & that seem to be quite popular suggestions

**Comment by BlockOG** [comment]
This would actually already be useful since there exist bots already, compatible with mhv6

**Comment by absoIute** [comment]
Added in v7
