### ISSUE TITLE
I want Mega Hack v6 to be free

### ISSUE THREAD

**Issue by El-Paraguas-YT** [absoIute/Mega-Hack-Pro-Future#151]
I want the hack (Mega Hack v6) to be free, so that some users who cannot pay $ 3.99 USD to take advantage of it (even once / 1 time) but it is not so necessary to spend something that possibly fails to put / install it in the root folder of the game (and that also the hack / mod can also be for people who did not buy the game on Steam, that is, they cracked it)

**Comment by Brittank88** [comment]
MHv6 costs money because Absolute puts genuine time and effort into it in order to benefit those who use it. If you want it and can't afford it, limited sharing may or may not be a thing you can fall back to, as per #139.

**Comment by absoIute** [comment]
> it is not so necessary to spend something that possibly fails to put / install it in the root folder of the game

If you're unable to install Mega Hack or just change your mind, there's a ~2 week change-of-mind period that I offer refunds for.

**Comment by Brittank88** [comment]
That's pretty cool - is that info in an easy-to-read place on the site? Might put some people at ease.

**Comment by El-Paraguas-YT** [comment]
> If you're unable to install Mega Hack or just change your mind, there's a ~2 week change-of-mind period that I offer refunds for.

I get it, I mean, it's for some users who liked hacks like RGB icon, Precision No-Clip, and more

But it is not necessary to spend $ 3.99 which in Colombia would be $ 15,450 COP (and in £ 3.99 it would be 20,850 COP), and I do not have any credit card or these payment options:

![Captura](https://user-images.githubusercontent.com/81331415/140580115-78a0d10d-8b41-4fe3-861d-3e349f185ce5.PNG)

I would love to pay it, also with a credit card, but I do not have it, I would like that on December 1 or 24 (or when a new version is released) the hack can be free

but I think this will not be possible

**Comment by Brittank88** [comment]
See #157 for how you might be able to get MHv6 in the future.

In terms of the website design, please suggest dark mode as a new issue so we can track that correctly.
