### ISSUE TITLE
Allow Pause During Finish Animation

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#152]
Currently, whilst you're being sucked into the finish line, you cannot pause the game. This is pretty annoying in circumstances where you didn't actually mean to finish the run (practising, etc).

**Comment by absoIute** [comment]
Definitely can look into, though next update also just implements Replay Last Checkpoint into the level complete screen to help with this

**Comment by Brittank88** [comment]
Oh, that's awesome!

**Comment by absoIute** [comment]
Added ready for next update!
