### ISSUE TITLE
Input Box Copy/Paste Support

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#153]
So, apparently, copy/paste for input boxes isn't natively supported by the extensions API - I genuinely think this would be extremely useful for any extension creators if it were available.

For example, NONG'd implemented pasting by recognising the string ".pst" and then replacing the input with the contents of the clipboard. This seems quite roundabout, and would definitely be smoother if it was just supported from the get-go.

**Comment by absoIute** [comment]
It's just not supported in Mega Hack as a whole, will look into it though due to how keybinds work right now it's just a bit awkward to implement

**Comment by Brittank88** [comment]
Awesome!

By the way @absoIute, the "Extensions API" label (as well as the "Site / Financial" label) are for categorisation so they're better off remaining, even on issues that are approved. Just makes it easier for you to filter by them later if you wanted to dedicate time to working on say, extensions API features or the functionality of the site / payment system, etc.

**Comment by absoIute** [comment]
adding with v7-beta1
