### ISSUE TITLE
Demonlist Update?

### ISSUE THREAD

**Issue by Smxrf** [absoIute/Mega-Hack-Pro-Future#155]

**Comment by Brittank88** [comment]
Hello, please provide more context before posting your issue. This doesn't mean anything to us. Is this an issue with the demonslist section not updating? Is this something else?

We cannot read minds, so please help us out. Thank you!

**Comment by Smxrf** [comment]
it is an issue with demonlist not updating

**Comment by absoIute** [comment]
The Demon List is updated manually by me whenever a change is made to pointercrate, though it can take a day or two for me to do this, will most likely move to an automated system soon enough

**Comment by Brittank88** [comment]
Oh wow, wasn't aware of that at all! Yeah, an API-based system would probably be better off.
