### ISSUE TITLE
Full-Height Menu Bug

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#158]
Menus are supposed to be full-height now if they can be. However, something is tricking MHv6 into thinking it has run out of vertical room (peep the scrollbar):
![image](https://user-images.githubusercontent.com/24266948/139612428-8c9e35e8-8a29-4add-bf64-ecf78c9ba95f.png)

I wonder if this is related to by use of Nvidia's DSR technology (which allows me to use 4K res despite a 1080p screen). Here are my basic resolution settings:
![image](https://user-images.githubusercontent.com/24266948/139612488-aad3ca99-a1f3-4eda-8c01-eff58946f985.png)

**Comment by absoIute** [comment]
It's a dumb implementation on myside, next update revamps the whole scaling system & allows for precise scaling + scrollable layouts taking up as much room as they can
