### ISSUE TITLE
Vocaloid-"Discord!"-Easter-Egg-Esque GD Thing

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#16]
See [this paragraph](https://discordapp.fandom.com/wiki/Easter_Eggs#:~:text=%E3%83%87%E3%82%A3,every%20time%20you%20open%20Discord.) for an outline of the Discord easter egg in question.

The GD equivalent would be toggling the easter egg by clicking the Geometry Dash logo 10 times in a row (disabled again by doing it 10 more times). Then, every time you enter the game a Vocaloid "Geometry Dash!" (or just "Dash!") sound effect is played.

A fun little thing. :P

**Comment by absoIute** [comment]
will add a couple easter eggs soon :p

**Comment by defaultacc30** [comment]
> will add a couple easter eggs soon :p

maybe you can direct send to rob? or just make it seperate (and free and open source) because it would be painful to spend $4 for a easter egg.

**Comment by Nicko2102** [comment]
This assumes that the easter egg is the only feature of MHV7, when it clearly isn't - nobody would buy MHV7 just for the easter eggs and nothing else (sorry absolute).

**Comment by Brittank88** [comment]
> > will add a couple easter eggs soon :p
> 
> maybe you can direct send to rob? or just make it seperate (and free and open source) because it would be painful to spend $4 for a easter egg.

![image](https://user-images.githubusercontent.com/24266948/155844159-e243776c-dc13-43fb-8411-02c053c0c267.png)
