### ISSUE TITLE
NONG songs

### ISSUE THREAD

**Issue by Smxrf** [absoIute/Mega-Hack-Pro-Future#160]
I don't necessarily know how this might be implemented, but maybe and option to paste in a song ID and a NONG song (probably a yt link) and the NONG song replaces the song ID you put in, this would save alot of hasle to me and other people, all good if its too hard to implement or not possible.

**Comment by absoIute** [comment]
Things like this go against YouTube's (and other services') ToS and are legally questionable at best, so it's just something I'd rather avoid messing with.

You could checkout this extension though https://github.com/paroxysms/nong-downloader-extension
