### ISSUE TITLE
Text Limit Bypass - Visible To All?

### ISSUE THREAD

**Issue by Smxrf** [absoIute/Mega-Hack-Pro-Future#162]
this is a dumb question, but I am unsure of weather mobile players or non MHV6 users can see the text you have written when going over the limit with bypass. can someone please clarify this?

**Comment by Brittank88** [comment]
Is this when bypassing the text in a text object placeable in the level?

**Comment by absoIute** [comment]
They can!

**Comment by Brittank88** [comment]
@absoIute just thought I should let you know that I am creating (and will go through all current issues to apply this to them) a FAQ label so that when you get around to setting up a proper faq page, you can just filter by this tag to see what should be added!
