### ISSUE TITLE
Blending Modes For Colour Options (+ P1 / P2 Swap)

### ISSUE THREAD

**Issue by Fl1pNatic** [absoIute/Mega-Hack-Pro-Future#167]
The title says it all. I wish you could make your icon color the same as level, but inversed. This could be really useful in nine circles levels.

**Comment by Brittank88** [comment]
Huh, I was actually thinking about this myself. I wanted to expand this to a general concept of blending modes though. For example, negation would cover this (unless you meant P1 and P2 but just swapped in comparison to the P1 and P2 the level uses, as that would be separate from blending modes).

**Comment by absoIute** [comment]
Possible in v7!
