### ISSUE TITLE
Set Scale Does Not Support Negative Values

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#17]

**Comment by absoIute** [comment]
It works for me, you may need to move the objects left then right for it to update visually, or am I missing something here?

**Comment by Brittank88** [comment]
I'll check again but if I type say, -1, set scale, move the object back and forth, it's still scale 1. Positive 1.

**Comment by Brittank88** [comment]
I can confirm that this is a valid bug.

Before:
![image](https://user-images.githubusercontent.com/24266948/91709644-604e0800-ebc6-11ea-8626-730c86995af8.png)
During:
![image](https://user-images.githubusercontent.com/24266948/91709685-6f34ba80-ebc6-11ea-9f77-24ee0fa9220d.png)
After:
![image](https://user-images.githubusercontent.com/24266948/91709715-7a87e600-ebc6-11ea-82fa-7f883e5075a1.png)

I did move the block around after using the hack and toggled the vanilla scale display - no change.

**Comment by absoIute** [comment]
ah the pointer used for objects seems to work on and off, so that's the issue, will fix in an update, thanks
