### ISSUE TITLE
Website Theming (Dark Theme)

### ISSUE THREAD

**Issue by El-Paraguas-YT** [absoIute/Mega-Hack-Pro-Future#172]
l like the darker mode in [Absolllute](https://absolllute.com/) page, i dont like the theme lol :P

**Comment by Brittank88** [comment]
You can just use [Dark Reader](https://darkreader.org/).

Keep this open though, as implementing an actual proper dark theme (+ the appropriate auto-detection implementation for it) would be cool to have.

**Comment by El-Paraguas-YT** [comment]
> You can just use [Dark Reader](https://darkreader.org/).
> 
> Keep this open though, as implementing an actual proper dark theme (+ the appropriate auto-detection implementation for it) would be cool to have.

XDDDDDDDD

**Comment by absoIute** [comment]
May add when I have time but not something that I feel is necessary or will happen anytime soon, since time spent on the site is limited anyway
