### ISSUE TITLE
Extensions not working

### ISSUE THREAD

**Issue by Md915** [absoIute/Mega-Hack-Pro-Future#176]
Half of my extensions are not working, some that the megahack detects dont work either, I had 12 extensions, the extensions are all in the extensions folder and they're not working, the game recognises 6 of them which 4 are working. What do i do?

**Comment by 4-Omega** [comment]
Copy the extensions somewhere else and copy them back. That fixed it for me.

**Comment by absoIute** [comment]
Put this DLL in your GD folder https://github.com/HJfod/minhook/releases/latest/download/minhook.x32.dll
