### ISSUE TITLE
Multiple hacks/mods cannot be set on the same key

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#177]
on v6 i had my key "s" set to activate both speedhack and show hitboxes. now on v7 when trying to set multiple hacks/mods on the same key, it will activate the hack/mod already set before instead of adding the new one, therefore the box stays empty with no key assigned
basically don't allow hotkeys to work while the ui is up

**Comment by absoIute** [comment]
Looking into it, thanks!

**Comment by absoIute** [comment]
fixed in beta5
