### ISSUE TITLE
Show hitboxes option "Show only after death" actually makes the hack work ONLY after death

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#178]
in megahack v7, when you toggle "only show after death" in the options for the show hitboxes hack, it won't allow you to see hitboxes in the middle of the level. instead you need to deactivate "show only after death" and then use the hack. it would be nice to not be "show **ONLY** after death" but "show **ALSO** after death", letting us see the hitboxes after death and toggle the hack itself whenever we want

**Comment by absoIute** [comment]
Intended behaviour, if you want to see hitboxes all the time (incl after death) just disable the option and enable Show Hitboxes
