### ISSUE TITLE
RGB icons speed setting is missing im MHv7

### ISSUE THREAD

**Issue by zohnannor** [absoIute/Mega-Hack-Pro-Future#180]
Apparently there is no way to set the speed for the colors of the icons or was it moved somewhere else? Can't find it

![image](https://user-images.githubusercontent.com/35764628/142491882-0e3deeef-a57a-46b8-8aaa-adf0098c3970.png)

**Comment by absoIute** [comment]
Will add back!

**Comment by absoIute** [comment]
Fixed since 7.0.0-beta4
