### ISSUE TITLE
(MegaHack v7) "Show layout" hack also shows invisible objects which were meant to be invisible for the entire level

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#182]
"show layout" shows those objects that weren't meant the be seen for the entire level, such as those portals that are used to move the camera when the gamemode is kind of doing an arc, to make it look cool you know, and maybe inside of this arc there is supposed to be an orb that needs to be clicked and i wouldn't know, because the portals would be on the object, which would be hidden.
maybe this could be hard, but adding an option to also hide those object who are meant to be hidden for the entire level would be great

**Comment by zohnannor** [comment]
I agree, the objects that are meant to be invisible should not be 100% visible, maybe  make them like 5% opaque instead?

**Comment by Nicko2102** [comment]
not sure how this could be coded though, like how would the hack know which objects to show and which to hide?

**Comment by zohnannor** [comment]
>  how would the hack know which objects to show and which to hide?

By their groups and alpha triggers.  It already does that with rotate trigger by not deleting the objects that is used as the origin of rotation

**Comment by Nicko2102** [comment]
I thought of that as well, such as if there is a group which is turned invisible at the start of a level and never turned back on, but that would make a lot of levels impossible as well, since some levels make the outlines of their blocks and spikes invisible in order to use custom ones made from 3D lines or non-hitboxed ramps, and since those are usually in the same group, the hack wouldnt be able to tell

**Comment by NewAlexGamer** [comment]
then we fall in the same problem: we either don't see or see too much
i'd prefer not seeing and use hitbox hack to see things instead of having my monitor full of useless stuff that also blocks me from understanding where hitboxes are

**Comment by Nicko2102** [comment]
Or even better, find the objects that are always invisible, then show the ones that are static/spikes but hide the ones that are special, such as orbs and portals

**Comment by NewAlexGamer** [comment]
Ok I think I figured it out:
Every object that is a block, spike or you know, the layout, has to be visible. Whatever is invisible since the beginning of the level will keep being visible
To solve the custom portals in transition, make every orb/portal visible IF they're not in a quick succession (spammed)
I think this should solve the issue

**Comment by Nicko2102** [comment]
> And since he managed to make the hack figure out which shape the layout takes in the level

?? what do you mean the "shape" he literally just hid everything that wasn't collidable

**Comment by absoIute** [comment]
This is intended behaviour, all physically interactable objects are set to 100% opacity, otherwise you wouldn't be seeing the full layout. May look into making those objects less opaque in the future but not planned for now
