### ISSUE TITLE
Disable Keybinds In Editor Not Working

### ISSUE THREAD

**Issue by Nicko2102** [absoIute/Mega-Hack-Pro-Future#185]
Wasn't sure how to title this, so I'll give an example: My restart keybind used to be "a", but after i set this in MH7, I can no longer use the 'a' key in the editor to move objects to the left. This goes for all the keys I have tried, including 'a', 'q', 'w', and 'f'. I also have BetterEdit installed, so that might be part of the issue, but I think more likely it is MHV7.

**Comment by No-obHub** [comment]
Have you tried enabling "Disable in Editor" in the keybinds section?

**Comment by Nicko2102** [comment]
That kind of fixed it (thanks btw), but i have to turn that option on and off again every time i enter the editor, which is super annoying, especially when im trying to playtest something

**Comment by Nicko2102** [comment]
Never mid its even worse, every time i playtest in the editor i have to turn it on and off again as well

**Comment by absoIute** [comment]
I believe this is a BetterEdit conflict, looking into it

**Comment by HJfod** [comment]
If it's a conflict with BetterEdit, this should be fixable once lilac is finished and comes with the custom keybinds API.
