### ISSUE TITLE
(MegaHack v7) Using start-pos switcher in normal mode crashes game, and crashes every time GD is opened until uninstalled.

### ISSUE THREAD

**Issue by sinc0s** [absoIute/Mega-Hack-Pro-Future#190]
I am not sure if this is a specific issue I had or something else, but when I used the start position switcher on a level that didn't have a start position, it crashed my game and every time I tried to load the game again it would crash, and cause 100s of OpenGL errors to pop-up one by one when I closed them until I force stopped the game in task manager. This is a pretty big issue as right now I have to go back to Mega Hack v6. I have tried restarting my computer, copying the mhv6 hack .json files into the hack folder, reinstalling mhv7, downloading mhv7 from the website again and installing it, and nothing seems to work. Here is the file of the crashlog of what I believe is the first crash that happened.

[crashlog_21-11-19_090919.txt](https://github.com/absoIute/Mega-Hack-Pro-Future/files/7568782/crashlog_21-11-19_090919.txt)
.

**Comment by absoIute** [comment]
Fixed in 7.0.0-beta2

**Comment by Brittank88** [comment]
@all-contributors please add @sinc0s for bug

**Comment by NewAlexGamer** [comment]
i wonder what you need to do to become an actual collaborator on the repository

**Comment by Brittank88** [comment]
I mean, just show that you really care about trying to solve issues, telling us if we missed marking an issue with the correct flairs, etc.

Work _with_ us until we can trust that you can work _like_ us, I guess.

**Comment by NefariousIntent2** [comment]
> I mean, just show that you really care about trying to solve issues, telling us if we missed marking an issue with the correct flairs, etc.
> 
> Work _with_ us until we can trust that you can work _like_ us, I guess.

Brittank, am I eligible for that position? I solves issues and takes care of the US/EST timezone. I correct people if they made errors (only if it could affect the person reading) and more.

**Comment by MainConMan** [comment]
imo, you should be! you have been very helpful. Up to Absolute and Brittank tho

**Comment by NewAlexGamer** [comment]
honestly i asked that question for this reason. i'm not that kind of guy who actively asks for it, i just want to earn it without having to annoy people about it all the time
although nefarious would be a great fit to this, seems to be pretty active and also has a lot of inside knowledge of the game that allows him to judge if things are doable already from the start without the need to wait. i think you should give him a chance

**Comment by NefariousIntent2** [comment]
> honestly i asked that question for this reason. i'm not that kind of guy who actively asks for it, i just want to earn it without having to annoy people about it all the time. i don't think it's happening tho because i've been minimodding for a while now and i hate it too, i just can't stop doing that for some reason, it's so frustrating although nefarious would be a great fit to this, seems to be pretty active and also has a lot of inside knowledge of the game that allows him to judge if things are doable already from the start without the need to wait. i think you should give him a chance

I do have inside knowledge. I know just about everything from how to make a Turing machine in GD, to obscure gimmicks, restoring of old levels, obscure gimmicks with the editor, types of values, a bit of assembly, c#, c++ and a tiny fragment of lua, and making post/get requests. However all of this wouldn't be possible if it wasn't for the communities I joined that know more knowledge before passing on to me. Even though I know absolute as a coder will know more then me at least I can patch up on US side and maybe explain some things faster then absolute can?

**Comment by NefariousIntent2** [comment]
However I think I will still mini mod. Quite sad, but its whatever.

**Comment by NefariousIntent2** [comment]
also on top of that i am in ru

**Comment by NefariousIntent2** [comment]
the original version not the new one

**Comment by NefariousIntent2** [comment]
@Brittank88 at the very least can I be added as contributor please read the comment above

**Comment by NefariousIntent2** [comment]
sorry to bug you but i feel like I should have gotten contributor a long time ago

**Comment by MainConMan** [comment]
If you keep begging for it you're not gonna get it.

**Comment by MainConMan** [comment]
It's up to Brittank or Absolute, if they want to they will, otherwise they won't.
