### ISSUE TITLE
"Message" status colour change

### ISSUE THREAD

**Issue by Fl1pNatic** [absoIute/Mega-Hack-Pro-Future#194]
Self-Explanatory

**Comment by Nicko2102** [comment]
Not self-explanatory at all lmao

**Comment by Nicko2102** [comment]
Oh wait do you mean the custom message that goes in the corner

**Comment by Fl1pNatic** [comment]
> Oh wait do you mean the custom message that goes in the corner

Yes

**Comment by absoIute** [comment]
May add customisation like font, opacity & size to status labels, but most likely not colour
