### ISSUE TITLE
MegaHack v7 on Linux

### ISSUE THREAD

**Issue by ThatsNotM3** [absoIute/Mega-Hack-Pro-Future#197]
Hello there! I have a question about running Mega Hack v7 under Linux. Previously I used Mega Hack v6 on my Fedora installation, and it worked perfectly. This Issue on GitHub helped me with installing MH on Linux - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/36

Now MH v7 has released. The problem is, when I try to launch the v7 installer with any Steam Proton version, it just don't do anything: no output, logs, etc. So is there any way of launching new Mega Hack v7 on Linux? Thanks!

(Fedora 35 Workstation, Wine 6.21-staging, tried with Proton 3.7 and 5.0)
![ksnip_20211119-165734](https://user-images.githubusercontent.com/60347034/142634677-4ac34b73-2ee4-4eea-a71a-73e600e28ba0.png)

**Comment by ThatsNotM3** [comment]
By the way, just found out that I am able to run the Installer with Wine itself(not Steam proton), but, as far as you know, you MUST run the installer with the same wineprefix(i.e. Steam Proton). Thats just funny, so the issue isn't in the installer itself? Is it just Proton not working?
![image](https://user-images.githubusercontent.com/60347034/142638168-cde32a37-95b3-49a8-b64f-d95ce0af4be5.png)

Also, I am still able to run Mega Hack v6 installer with Steam Proton without any issues.

**Comment by Felting** [comment]
#184 I tried to get it working using adafcaef dll injector but it didin't work.

**Comment by ToxicAven** [comment]
Bump here, tried to do the rename method that worked with MHv6, with no luck.

**Comment by ThatsNotM3** [comment]
Rename method worked for me. More in this comment - https://github.com/absoIute/Mega-Hack-Pro-Future/issues/184#issuecomment-974624276

**Comment by ToxicAven** [comment]
> Rename method worked for me. More in this comment - [#184 (comment)](https://github.com/absoIute/Mega-Hack-Pro-Future/issues/184#issuecomment-974624276)

The rename method for me worked to load the installer, but it did not load the mod into geometry dash upon installing.

**Comment by absoIute** [comment]
#184

**Comment by Brittank88** [comment]
Duplicate of #184
