### ISSUE TITLE
Noclip Accuracy Overridden By 0% Practice

### ISSUE THREAD

**Issue by Nicko2102** [absoIute/Mega-Hack-Pro-Future#198]
When noclip accuracy is enabled and you complete a level, it does not save your progress. However, if you use noclip accuracy in practice mode with the 0% practice complete turned on, beating the level will result in your 100% record being saved.

**Comment by absoIute** [comment]
Does this happen with Disable Progress enabled in Noclip settings?

**Comment by absoIute** [comment]
Fixed
