### ISSUE TITLE
[Suggestion] Option to toggle secret and user coin collected visibility

### ISSUE THREAD

**Issue by Conlinkin** [absoIute/Mega-Hack-Pro-Future#20]
I think there should be a option to make secret coins and user coins that the player has already collected look like they haven't been collected yet. 

Example is make coins from the first image turn into coins in the second image.

Image 1:
![Screenshot_20200903-141633_Geometry Dash](https://user-images.githubusercontent.com/24375555/92163211-8525c380-edf0-11ea-92b3-1fcf95f16298.png)

Image 2:
![Screenshot_20200903-141455_Geometry Dash](https://user-images.githubusercontent.com/24375555/92163366-ce761300-edf0-11ea-9d50-69eb0954547b.png)

**Comment by WEGFan** [comment]
```json
{
    "name": "toggle coins collected visibility",
    "desc": "",
    "opcodes": [
        {
            "addr": "0xE6706",
            "on": "8B C2 90",
            "off": "0F 44 C2"
        },
        {
            "addr": "0xE720F",
            "on": "8B D9 90",
            "off": "0F 44 D9"
        }
    ]
}
```

**Comment by absoIute** [comment]
added in v6.2-beta3, thanks!
