### ISSUE TITLE
Toggle for Free Window Resize and/or Save Resolution Settings

### ISSUE THREAD

**Issue by noeruchangd** [absoIute/Mega-Hack-Pro-Future#202]
During my time using v7, I've noticed that there doesn't seem to be a toggle for the Free Window Resize hack, and the hack stays on by default. As such, the option to disable and re-enable the hack at will would be a neat addition.

In addition, a way to save resolution settings between launches would also be a good addition, as this can potentially save a lot of time for players who use non-default resolution values such as myself.

**Comment by Nicko2102** [comment]
I'm pretty sure the toggle for window resize wav in MHV6, not sure why it's not in V7

**Comment by absoIute** [comment]
Working on it

**Comment by absoIute** [comment]
Fixed in beta4
