### ISSUE TITLE
Level Complete screen still plays after switching to another start position

### ISSUE THREAD

**Issue by noeruchangd** [absoIute/Mega-Hack-Pro-Future#203]
When using the Start Pos switcher hack, after completing a level, the level complete screen and fireworks animation still plays even after switching to a different start pos. 

An example can be seen here:
https://clips.twitch.tv/GiantYummyDiscTooSpicy-j0Q82Z4MCbqNQ6Nc

**Comment by absoIute** [comment]
Fixed in 7.0.0-beta2
