### ISSUE TITLE
Suggestion: Make pressing space on level complete screen start the level over

### ISSUE THREAD

**Issue by Fl1pNatic** [absoIute/Mega-Hack-Pro-Future#208]
So, right now, if you press space on level complete screen - You will be sent back to the last checkpoint, which I don't really find comfortable, because pressing space always started the level over. 

I want to only return to the last checkpoint if I click the checkpoint button, and start the level over if I press space.

**Comment by absoIute** [comment]
Added back in 7.0.0-beta2!
