### ISSUE TITLE
"Inject DLL" File Menu Memory / Favourites System

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#21]
The file menu that opens when you inject a DLL should remember the last place a DLL was opened at, and re-open there. This means that people don't have to navigate to the same place every time just to use the same DLL.

A "Favourite DLLs" system would also be cool too - means you can just load it directly from the overlay without needing to navigate directories, as long as the DLL remains in the same path.

**Comment by Brittank88** [comment]
Update: The file dialog _is_ actually remembering the last location... it just took some time to start doing that apparently? Not sure whether to leave this open or not...

**Comment by absoIute** [comment]
it only saves location after you inject a DLL, not if cancelled
