### ISSUE TITLE
Suggestion: Legit Indicator

### ISSUE THREAD

**Issue by GDSaneS** [absoIute/Mega-Hack-Pro-Future#210]
So, Cheat Indicator can't be used for telling if a completion is legit, since you can't know if the hack is enabled or disabled, i suggest an option to add a green dot when there are no cheats enabled.

**Comment by litecave** [comment]
I guess nice suggestion, but it's kinda dumb. If you wanna be seen legit - just unpatch and after playing patch again. Or just off every shortcut, show it and show that every unlegit cheats are off and play.

**Comment by Nicko2102** [comment]
It's not dumb at all, actually a really good idea! 

>just unpatch and after playing patch again 

 The whole point is to make things easier, and unpatching/patching every time you want to record seems like absolllute waste of time

>Or just off every shortcut, show it and show that every unlegit cheats are off and play.

Do you know how long this would take with V7? it would be much easier to just add a green dot

**Comment by absoIute** [comment]
Will add an option for this!

As it stands the Cheat Indicator works like:
Red - Cheats
Orange - Cheats + Safe Mode
Green - Safe Mode

Will change it to:
Red - Cheats:
Orange - Cheats + Safe Mode
Yellow - Safe Mode
Green - No Cheats & Safe Mode (optional)

**Comment by absoIute** [comment]
added in 7.0.0-beta3
