### ISSUE TITLE
Rainbow Icon fails to fully work on Robot and Spider gamemodes.

### ISSUE THREAD

**Issue by mrhotmadm** [absoIute/Mega-Hack-Pro-Future#211]
I recently downloaded Mega Hack V7 and turned on all my previous settings. But, when I went to turn on the rainbow icon setting, the glow or outline of the robot and spider gamemodes did not change. No matter what setting I chose for the glow (invert, reverse, flash, pastel, rgb, etc.), the outline always stayed as my secondary color.

If you need a picture of this, please let me know.

**Comment by absoIute** [comment]
Fixed in 7.0.0-beta2
