### ISSUE TITLE
Game is extremely unstable

### ISSUE THREAD

**Issue by Fl1pNatic** [absoIute/Mega-Hack-Pro-Future#216]
My game can crash due to anything.
E.g. 
I turned on Invert Colors in Icons menu
I tried going to user's levels and the game crashed
I tried to uncomplete the level

All these actions are causes of crashes, and they occur randomly. Please fix

**Comment by absoIute** [comment]
Could you send the crashlogs generated in GD's folder?

**Comment by Fl1pNatic** [comment]
> Could you send the crashlogs generated in GD's folder?

1. Which file?
2. Now my game starts with a runtime error, but if I ignore it, then the game starts and works normally, unless I press "Ok" or close the runtime error, then my game crashes.

**Comment by absoIute** [comment]
The latest one in the crashlogs folder, I believe that should be fixed in an update, just reinstall Mega Hack from the installer

**Comment by Fl1pNatic** [comment]
> The latest one in the crashlogs folder, I believe that should be fixed in an update, just reinstall Mega Hack from the installer

yep it is
