### ISSUE TITLE
[MHv7] CPS/FPS Display completely broken

### ISSUE THREAD

**Issue by Kenar-f** [absoIute/Mega-Hack-Pro-Future#218]
When I enable CPS or FPS Display it doesn't show. When I reenable it it pops up, but the value on both of them is set to "0".

**Comment by Nicko2102** [comment]
it might be an issue with multiple extensions, because it works perfectly fine for me

**Comment by Kenar-f** [comment]
> it might be an issue with multiple extensions, because it works perfectly fine for me

the problem is, i don't have any extensions.

**Comment by Nicko2102** [comment]
does it keep showing 0 FPS when you're playing a level? also what operating system do you use?

**Comment by absoIute** [comment]
Send screenshots of your enabled hacks, GD folder & extension folder

**Comment by absoIute** [comment]
Fixed since 7.0.0-beta4
