### ISSUE TITLE
Checkpoint / Startpos Frame Skip Fix

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#22]
In certain levels, when respawning from a start position or practice checkpoint, a bunch of frames are skipped and it makes it nearly impossible to not die. it's actually pretty crippling when you're trying to playtest or practice a level.

It would be nice if there was an option to fix this by halting the movement of the icon until the game is actually ready to play smoothly.

I believe the frame skip occurs because each time you respawn the game is recalculating all the effects of triggers that have already been passed by the player. This is just a theory though.

**Comment by absoIute** [comment]
looking into this, along with avoiding skipped frames caused by lag

**Comment by absoIute** [comment]
Added ready for next update

**Comment by ThePandoroxTP** [comment]
Related to this, can we get a bug fix/feature for fixing lag spike with in editor playtest? I am building an XL sync based layout and the issue is starting to become really apparent, would be nice if there was a fix.
