### ISSUE TITLE
Authorizing in-Game.

### ISSUE THREAD

**Issue by litecave** [absoIute/Mega-Hack-Pro-Future#220]
So, this is probably mostly for linux because proton, wine and other things. 
Patching GD using Wine (not Proton) will cause error of authorization. Renaming GD and MH installator isn't always working. So, this suggestion is perfect fix for this problem.

**Comment by absoIute** [comment]
I don't plan on changing the authentication system anytime soon, but may look into making linux installation simpler, like including a legacy installer that uses' v6's loader with v7, which should definitely help.

**Comment by litecave** [comment]
> I don't plan on changing the authentication system anytime soon, but may look into making linux installation simpler, like including a legacy installer that uses' v6's loader with v7, which should definitely help.

Thank you!

**Comment by litecave** [comment]
Before legacy installer I think I'm gonna dualboot windows. Anyways, again, thank you.
