### ISSUE TITLE
Phantom wave trail visible when using Wave Trail Bugfix + StartPos Switcher

### ISSUE THREAD

**Issue by CreeperSword** [absoIute/Mega-Hack-Pro-Future#224]
When using wave trail bugfix and startpos switcher, a wave trail is visible behind you if you are not in wave mode when playing from a startpos. This bug only happens when both mods are enabled, and does not happen if you have not switched start positions since re-enabling the mod. This bug does not affect wave, and does not affect levels that do not have wave parts.

![20211122203858_1](https://user-images.githubusercontent.com/93549710/142959680-a2047a62-1d5d-42a1-b7a6-22d9a3c8de99.jpg)
![20211122203903_1](https://user-images.githubusercontent.com/93549710/142959681-d1541f01-343e-4578-8cca-c899d6f1c7e2.jpg)
![20211122204120_1](https://user-images.githubusercontent.com/93549710/142959698-5336e7a4-2ff1-40be-865e-c1d98de3f220.jpg)
![20211122210844_1](https://user-images.githubusercontent.com/93549710/142961607-6cab04c6-2007-437a-afc4-af1f2d3f5de4.jpg)

**Comment by absoIute** [comment]
fix ready for 7.0.0-beta4
