### ISSUE TITLE
Certain Keys Showing Up As OEM1 - 9 In Jump Keybinds

### ISSUE THREAD

**Issue by MattiMakkara** [absoIute/Mega-Hack-Pro-Future#227]
These Keys Do This:
/
;
'
[
]
\

**Comment by Nicko2102** [comment]
Those are just the key names - they have to be called that since different keyboards do different things with those keys, so if you write "/", then someone with a different language keyboard will see "/" come up when they press something else

**Comment by absoIute** [comment]
Expected behaviour, different regions have different layouts, so instead of accounting for all of them that's what's displayed. May look into changing that in the future but likely not
