### ISSUE TITLE
Auto Low Detail Mode - Dynamic

### ISSUE THREAD

**Issue by nrbxyz** [absoIute/Mega-Hack-Pro-Future#235]
So this is a feature that would probably be really difficult to implement considering how many scenarios there are, and it will probably never be perfect, but what it could do is to check your gpu/cpu and under broad categorization(like maybe 3-4 classes of gpus automatically made). Then it removes unnecessary objects in the level when opening it.

This would be hard to perfect and also not approvable by the demons list but would be incredibly useful

**Comment by absoIute** [comment]
Seems a bit complex to implement, though if you know your device isn't too powerful Auto LDM exists
