### ISSUE TITLE
Hacks popups on hotkeys

### ISSUE THREAD

**Issue by Fl1pNatic** [absoIute/Mega-Hack-Pro-Future#24]
It would be useful to add popups when you activate hacks via hotkeys. It might be helpful for people that have hacks like "noclip" set on hotkeys, to know if they accidentally activate it.

**Comment by Brittank88** [comment]
Seconding this issue - we've all heard stories of people thinking they've beaten a level, or have gotten near the end of one, and realising that they were in noclip.

Maybe it could activate the testmode text by default?

**Comment by Fl1pNatic** [comment]
> Seconding this issue - we've all heard stories of people thinking they've beaten a level, or have gotten near the end of one, and realising that they were in noclip.
> 
> Maybe it could activate the testmode text by default?

Could be a good idea, but would be confusing. Because people would think that they put startpos somewhere and will try to get rid of non-existing startpos.

**Comment by Brittank88** [comment]
Hmm.. I see your point. Something in the bottom left would work well because that's generally out of the way of anything that you'd need to see, whilst still being visible enough.

**Comment by absoIute** [comment]
added cheat indicator to v6.2-beta3!
