### ISSUE TITLE
Custom Comment Color for other MHv7 Users

### ISSUE THREAD

**Issue by ImmensityHQ** [absoIute/Mega-Hack-Pro-Future#240]
When using MHv7, other users that own MHv7 have custom comment colors. This could either be a default color or customized by the user.

**Comment by zohnannor** [comment]
I'm pretty sure this is impossible because gd servers can't store the information about color of the comment's text.

**Comment by ImmensityHQ** [comment]
Think like how Mods' comments have custom colors. The way it probably would work is you link your GD account to your Absolllute account, and MHv7 uses that to change the color of comments left by users that own MHv7.

**Comment by zohnannor** [comment]
That way there needs to be a server up and running constantly so that whenever some player is checking comments under some random level, the game client will ask the server if some comments should be colored.

**Comment by zohnannor** [comment]
Unless the colors are included in the comment itself with something like a text formatting tho I don't know if that's true.

**Comment by absoIute** [comment]
Yeah not possible on vanilla, don't really want to dedicate server resources to something like that sorry
