### ISSUE TITLE
"Player Trail" Does Nothing

### ISSUE THREAD

**Issue by zohnannor** [absoIute/Mega-Hack-Pro-Future#245]
![player trail](https://user-images.githubusercontent.com/35764628/143676296-f55faa3e-4599-4950-b1e3-6cb8a3bddf7c.gif)

**Comment by absoIute** [comment]
Working on it!

**Comment by JhonnyRice** [comment]
Yea-

**Comment by JhonnyRice** [comment]
same problem

**Comment by absoIute** [comment]
Fixed in beta6
