### ISSUE TITLE
"Fill Hitbox" Multiple Application Bug

### ISSUE THREAD

**Issue by zohnannor** [absoIute/Mega-Hack-Pro-Future#246]
Clicking "Fill hitbox" while paused applies hitbox filling multiple times, resets after unpausing
![fill hitbox](https://user-images.githubusercontent.com/35764628/143676430-8afbf775-c4fe-4203-b8c8-5c46d5776088.gif)

**Comment by absoIute** [comment]
Working on it

**Comment by absoIute** [comment]
fixed next update
