### ISSUE TITLE
Dash Orb Fire, Robot Glow, Spider Glow Are Secondary Color/Glow Even If Those Are RGB

### ISSUE THREAD

**Issue by Sloweneuh** [absoIute/Mega-Hack-Pro-Future#247]
I couldn't find an open issue on that so I opened one. Dunno if it's just on my end tho.

**Comment by absoIute** [comment]
Working on it

**Comment by Sloweneuh** [comment]
ok thx

**Comment by absoIute** [comment]
Fixed, dash orb is expected behaviour right now
