### ISSUE TITLE
"Disable In Editor" Option In Shortcut Section Works When Playing The Level From Menu > Save and Play

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#248]
when i enter a level in the editor and the "Disable in editor" option for the shortcuts is enabled, and i go to the button in the top right corner (pause, menu, idk what it should be called) and do "Save and play", it thinks i'm still in the editor, therefore it disables the hotkeys

**Comment by absoIute** [comment]
working on it

**Comment by absoIute** [comment]
fixed in beta5
