### ISSUE TITLE
Visible Level Previews

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#249]
i believe this is a bangers idea:
after loading a level, create an image or whatever that shows what the level looks like instead of directly go and play the level

explained better: a button that shows some kind the level in some kind of editor, where you only have a slider and a zoom. the slider let's us go trough the level like preview mode in the actual editor works when moving in the editor.
this can be done to levels that area already loaded, like the saved ones or the creator ones to make it more manageable

it can literally be a smaller editor but just with slider and zoom that loads immediately if you want to imagine this as a simpler idea

i believe this could be more of a "extension" suggestion because of its complexity, but why no try to suggest it anyways

**Comment by Brittank88** [comment]
Making an image of a level (whilst I'm sure it is possible) might be difficult because, for example, a lot of levels teleport the player upwards straight away, or at least rather quickly. You might just end up with a still photo of... nothing.

**Comment by ImmensityHQ** [comment]
perhaps create a low-level simulation of the level that wouldn't take up as many resources as playing the actual level, and take a screenshot of what the level would look like a few seconds after the beginning.

**Comment by Brittank88** [comment]
Simulating a level without actually being in it might also be difficult, I mean, this is in some ways just piggybacking off of the code points that GD already has. Absolute knows more about the possibility of all of this but the overhead and implementation time may overpower the worth of the feature here.

**Comment by absoIute** [comment]
Seems a bit redundant when you can use the Editor + Hide UI, probably not something I'd look into

**Comment by Brittank88** [comment]
Yeah, I figured that this was probably more effort than it's worth.
