### ISSUE TITLE
Dual Mode Per-Icon Noclip

### ISSUE THREAD

**Issue by ItsMajestiX** [absoIute/Mega-Hack-Pro-Future#25]
Pretty much exactly what the title says. The regular noclip button could be used on player one, while a separate button could toggle the noclip on player two. This would be useful when using Mega Hack in conjunction with a macro recording program when recording duals to record one player at a time without having to do inputs on the other player.

**Comment by Fl1pNatic** [comment]
This is a useful idea, but it won't be used too often and neither it will be used by regular players.

**Comment by Brittank88** [comment]
Actually, for any situation where you wish to bot a 2-player dual, this may be useful. It depends on what techniques can be developed from it that actually improve efficiency.

**Comment by absoIute** [comment]
Added ready for next update!

**Comment by Nicko2102** [comment]
this would be super useful for doing 2-player levels actually, for example my friend and I are going to try to beat Multition II, and we need to practice our parts separately since we wont see each other for a while, and this would be perfect for that

**Comment by MainConMan** [comment]
This needs the "upcoming" label.
