### ISSUE TITLE
Speedhack Value Resetting?

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#250]

**Comment by Brittank88** [comment]
Future reference - try to summarise the issue in the title, and then explain it further in the body of the issue. I'll fix the title, and the body text should have been something like:
`The speed value for speedhack is reset every time the game is restarted.`

**Comment by NewAlexGamer** [comment]
i believe the title was self explanatory enough but ok

**Comment by absoIute** [comment]
fix ready for next update

**Comment by Brittank88** [comment]
> i believe the title was self explanatory enough but ok

I was never saying it wasn't - the title was bloated and some of it should have gone into the description.
