### ISSUE TITLE
Dll errors on running installer

### ISSUE THREAD

**Issue by Felting** [absoIute/Mega-Hack-Pro-Future#252]
When I try to run the mega hack v7 install it says "The code execution cannot proceed because MSVCP140.dll was not found. Reinstall the program may fix this problem." also "The code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstall the program may fix this problem." When I downloaded the files from dll-files.com it gave a memory address error

**Comment by absoIute** [comment]
install https://aka.ms/vs/17/release/vc_redist.x86.exe
