### ISSUE TITLE
Nine Circles List

### ISSUE THREAD

**Issue by AndreySt2008** [absoIute/Mega-Hack-Pro-Future#260]
How about making a Nine Circles list in Mega Hack v8 Professional?

**Comment by Brittank88** [comment]
This is cool but there'd have to be some standard of quality/authenticity/relevance for the levels added to that list. Some kid's "Sonic Wave Infinity X Deluxe" should not end up there, lmao.

**Comment by AndreySt2008** [comment]
Yeah

**Comment by absoIute** [comment]
only plan on looking into popular lists with the community right now, like the ILL
