### ISSUE TITLE
AutoSave Not Working

### ISSUE THREAD

**Issue by ImmensityHQ** [absoIute/Mega-Hack-Pro-Future#268]
AutoSave should automatically save what hacks we are using for the next session, however it's not working for whatever reason. For a while, Noclip would be enabled whenever I loaded up the game, regardless if I had turned it off in the last game session. To fix it I had to manually save.

EDIT: just found out this issue has already been found.

**Comment by zohnannor** [comment]
If it's a duplicate (#255) then close this issue.

**Comment by Brittank88** [comment]
Duplicate of #255

**Comment by Brittank88** [comment]
(I know it was already said but saying "Duplicate of X" is literally how you mark it as a duplicate lmao)

**Comment by zohnannor** [comment]
@Brittank88 Oh thanks I didn't know that for some reason
