### ISSUE TITLE
MHv7 Not Working

### ISSUE THREAD

**Issue by patrykchrymecki** [absoIute/Mega-Hack-Pro-Future#276]
Mega Hack v7 worked fine until I reset my pc now every time I run it errors show up here are what they say (I also reinstalled multiple times)
1. MSVCP140.dll Missing.
2. MSVCP140_1.dll Missing.
Any thing I could do?

**Comment by patrykchrymecki** [comment]
(MHv6 works fine)

**Comment by zohnannor** [comment]
See https://github.com/absoIute/Mega-Hack-Pro-Future/issues/252#issuecomment-981115430

**Comment by patrykchrymecki** [comment]
Thanks.

**Comment by willy12337** [comment]
mega hack v7 is cool but when i use noclip on a level and finish it does not give stars coins and orbs pleas help me

**Comment by NewAlexGamer** [comment]
check if "safe mode" or "auto safe mode" are enabled when using any hack

**Comment by PooPooAss527** [comment]
to will12337 when u use noclip in v7 it automatically has a force safe mode but in v8 it has been made optional
