### ISSUE TITLE
Suggestion: Level Record, Play Bot

### ISSUE THREAD

**Issue by C1intOn110309** [absoIute/Mega-Hack-Pro-Future#277]

**Comment by C1intOn110309** [comment]
if you press record, it will record your clicks and if you die, it saves your clicks and deletes the mistaken click and keeps recording until you beat the level. the bot and speedhack combination is the best for impossible levels. when you play, the bot plays the clicks ingame.

**Comment by zohnannor** [comment]
Why'd you explain a bot features in such details lmao, everyone knows what's a bot is.

See https://github.com/absoIute/Mega-Hack-Pro-Future/issues/123#issuecomment-931721579

**Comment by C1intOn110309** [comment]
i get it lol

**Comment by absoIute** [comment]
Duplicate #123

**Comment by Brittank88** [comment]
Duplicate of #123
