### ISSUE TITLE
Extension Development Tutorials?

### ISSUE THREAD

**Issue by ExplodingBill** [absoIute/Mega-Hack-Pro-Future#280]
I know that this isn't an issue or anything but can someone comment a link to a tutorial on how to make extensions for mega hacks v7.

**Comment by zohnannor** [comment]
https://github.com/absoIute/Mega-Hack-Extensions#getting-started

**Comment by zohnannor** [comment]
Pretty sure you can't use Megahack functions in your extension other than adding elements of interface to the window. Megahack allows you to just load your dll to the game and not to call functions for enabling/disabling hacks.

### To make an extension you will need to:

1. Get `hackpro_ext.h`/`hackpro_ext.hpp` from absolute/Mega-Hack-Extensions.
2. Include it to your source file and wait for Megahack to initialize itself like `basic.c`/`basic.cpp` does.
3. Write your own functions for your extension and call them in the callbacks you just created.
    3.1. I just realized I know little to nothing about GD Modding infrastructure and tooling so just check popular modders' repos to find any info 😳
[HJfod](https://github.com/HJfod), [PoweredByPie](https://github.com/poweredbypie), [mat](https://github.com/matcool), [nekitdev/gd.py](https://github.com/nekitdev/gd.py)
    <details>Or just use my Rust library when it'll come out 😃😃😃 (not advertising)</details>
4. Compile your code to dll: 
    * C: `gcc`/`clang`/`mingw`:
    ```bash
    gcc -c -o your_ext_obj.o your_ext_source.c
    gcc -o your_ext.dll -s -shared your_ext_obj.o -Wl,-- subsystem,windows
    ```
    * C++: something similar
    * Visual Studio: google
5. Put it in `extensions` folder

**Comment by ExplodingBill** [comment]
thanks for the info on how to compile
