### ISSUE TITLE
Auto Safe Mode

### ISSUE THREAD

**Issue by fedqq** [absoIute/Mega-Hack-Pro-Future#281]
Pretty self explanatory but basically an option that makes it so that when you turn on any hack it turns on safe mode automatically, and deactivates it after you turn off all the hacks you have enabled (It should only work for hacks which aren't considered legit such as noclip or speedhack). Also safe mode should ask you whether you want to keep the progress at the end of a completion in case someone accidentally leaves it on and completes something hard.

**Comment by zohnannor** [comment]
Duplicate of #191

**Comment by Brittank88** [comment]
Duplicate of #191
