### ISSUE TITLE
[V7] Config doesn't save

### ISSUE THREAD

**Issue by Fl1pNatic** [absoIute/Mega-Hack-Pro-Future#285]
A week ago, I turned on noclip. But now, each time I open the game, noclip is still on. Even if I turn it off and spam "Save" button. I have no idea why it's like that. Please do something about it.

**Comment by zohnannor** [comment]
Duplicate of #255

**Comment by Fl1pNatic** [comment]
> Duplicate of #255

Welp, in my defence Jump Hack also turns on

**Comment by absoIute** [comment]
fixed in beta5/6

**Comment by Brittank88** [comment]
Duplicate of #255
