### ISSUE TITLE
Stop Move Triggers on Death

### ISSUE THREAD

**Issue by MainConMan** [absoIute/Mega-Hack-Pro-Future#286]
The mod would stop moving objects when you die, so its easier to see how you died if a moving object killed you.

**Comment by NewAlexGamer** [comment]
this would be kinda hot ngl

**Comment by MainConMan** [comment]
> triggers like alpha, color, pulse, you get the idea, can easily cover the screen and the entire purpose of stopping move triggers after death is to understand how the death happened. so might as well stop them from working too

This gave me a better idea! #445

**Comment by Brittank88** [comment]
For the sake of #445 being a better issue, I'll mark this as a duplicate of that.

**Comment by Brittank88** [comment]
Duplicate of #445
