### ISSUE TITLE
Icon Effects do not work on spider or robot's glows

### ISSUE THREAD

**Issue by Aktimoose** [absoIute/Mega-Hack-Pro-Future#289]
Having a custom glow colour does not work when in the spider or robot gamemodes. (This is likely because the their glows are stored separately)

![image](https://user-images.githubusercontent.com/44620677/146416962-a267b7ea-3f07-4106-804b-60b766bf1f93.png)
Glow effect is set to OBJ (aqua) in this screenshot yet it appears red (which is my icon's actual glow colour)

**Comment by absoIute** [comment]
fixed in beta5

**Comment by Brittank88** [comment]
Duplicate of #247
