### ISSUE TITLE
Hack Tooltips

### ISSUE THREAD

**Issue by zohnannor** [absoIute/Mega-Hack-Pro-Future#29]
It will be very useful for new users or just to remind yourself what specific toggle is doing. Just hover over it (and maybe wait for a bit or press some key) and popup appears with a text explaining what would happen if you toggle it.

**Comment by Brittank88** [comment]
Little delayed tooltips could be nice. Is this hard to implement with the OpenGL library?

**Comment by Zohnannor** [comment]
Haven't touched OpenGL yet but I think implementing this would be pretty easy for Absolute's level of skill :)

**Comment by absoIute** [comment]
added in v6.3.0-beta5
