### ISSUE TITLE
Speedhack Resets Back To 1x No Matter What Your Speedhack Is Set To Every Time I Reenter Geometry Dash | Possible Fix?

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#291]
![20211216200107_1](https://user-images.githubusercontent.com/60493629/146487049-ca322653-2809-43df-96b0-e8fcf2329838.jpg)

**Comment by ExplodingBill** [comment]
this is probably to stop issues

**Comment by absoIute** [comment]
fixed in beta5

**Comment by Brittank88** [comment]
Duplicate of #250
