### ISSUE TITLE
Add The Song Bypass Back To MHV7?

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#292]

**Comment by totallyphysicallypossible** [comment]
but
![Screenshot 2021-12-18 143619](https://user-images.githubusercontent.com/94307704/146633478-5775c225-0ddc-4f40-8374-2bbce9c45a07.png)

**Comment by zohnannor** [comment]
https://github.com/absoIute/Mega-Hack-Pro-Future/issues/85#issuecomment-910861055

**Comment by Brittank88** [comment]
Duplicate of #85
