### ISSUE TITLE
Start Pos At The Endscreen Is 1% Off

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#297]
![20211219101200_1](https://user-images.githubusercontent.com/60493629/146686002-9705182f-c65c-4d67-b742-de633bf4d358.jpg)

**Comment by totallyphysicallypossible** [comment]
honestly i dont know how that would affect you much

**Comment by NewAlexGamer** [comment]
i'm pretty sure it's one of those errors where if you do -1 in the code it won't work because it's calculating the % wrong, because it works on my side

**Comment by absoIute** [comment]
Fix ready for next update

**Comment by MainConMan** [comment]
@Brittank88 This needs upcoming label. This is the last time, I promise!

**Comment by Brittank88** [comment]
> @Brittank88 This needs upcoming label. This is the last time, I promise!

Please remind me if something needs a label, I'd prefer to know! Thanks for the heads up!

**Comment by MainConMan** [comment]
> > @Brittank88 This needs upcoming label. This is the last time, I promise!
> 
> Please remind me if something needs a label, I'd prefer to know! Thanks for the heads up!

I meant this is the last time I'll find one, because I finished the dates on the table. Sorry for miscommunication.
