### ISSUE TITLE
Suggestion: Change of color text

### ISSUE THREAD

**Issue by kidronnie2** [absoIute/Mega-Hack-Pro-Future#298]
Be able to change the color of text such as fps counter, cps counter, message and all text that mhv7 has

**Comment by absoIute** [comment]
I feel that just looks tacky, white text just works with everything

**Comment by kidronnie2** [comment]
> I feel that just looks tacky, white text just works with everything

idk if i should reply twice since youve already closed it, but the main reason i want this is that maybe because if you are playing a white themed level, or something with a white background or something like that, and it would be difficult to see the text. thanks anyways tho

**Comment by absoIute** [comment]
Could add a black text option to help with that tbf
