### ISSUE TITLE
Beta 6 with no changelog?

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#299]
i saw the changelog for beta 5 literally 5 minutes ago and didn't know about it. then i reinstalled v7 to see what was new about that and it said it was beta 6 and not 5. did you forget to announce about beta 6 or you misstyped?

**Comment by absoIute** [comment]
Didn't think it was worth posting since it was released pretty soon afterwards & basically just fixed 2 bugs caused by beta5 + 1 minor change

Changes/Additions:
- Last % status -> Best Run

Fixes:
- Fixed show layout not resetting colours (beta6)
- Fixed levels crashing on some triggers (beta6)
