### ISSUE TITLE
Pickup Trigger Crashes Game. 

### ISSUE THREAD

**Issue by MainConMan** [absoIute/Mega-Hack-Pro-Future#300]
Whenever a pickup trigger happens, it crashes my game. Heres an example level that I made "76699153"
[crashlog_21-12-20_004527.txt](https://github.com/absoIute/Mega-Hack-Pro-Future/files/7742877/crashlog_21-12-20_004527.txt)

I tested this even with no hacks enabled and with no extensions, but it still crashed.

**Comment by ExplodingBill** [comment]
this level doesn't exist

**Comment by MainConMan** [comment]
nvm, I updated to beta 6 and it fixed,...
