### ISSUE TITLE
Maybe Adding "View Player Trail In Editor" Feature

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#302]
This suggestion says that since you can view the player trail in-game, why not manage to view it in the editor?

**Comment by absoIute** [comment]
Not something I see being particularly useful sorry

**Comment by Brittank88** [comment]
@BrownieGamingX5 You can already do this by toggling "Trail Always On".

**Comment by Brittank88** [comment]
Btw @absoIute whilst not terribly useful I did find myself fond of being able to see the trail in the editor 😋

**Comment by absoIute** [comment]
oops need to fix that
