### ISSUE TITLE
Make Respawn Time Work With Practice Mode

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#303]
Example: Set Respawn Time To Be 0.25, Practice Respawn Time Would Be 0.25

**Comment by Brittank88** [comment]
@BrownieGamingX5 This is a good suggestion, but in future, please don't bloat the title with examples, etc. Your example would be better placed in the description. It just makes things neater.

**Comment by Nicko2102** [comment]
ik im late, but i think it would be even better if they were two separate variables

**Comment by absoIute** [comment]
added ready for next update (fast practice reset modifier)
