### ISSUE TITLE
Set Labels/Status Opacity

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#304]
![20211221231301_1](https://user-images.githubusercontent.com/60493629/147050933-84bf9b1a-1500-4ceb-b4ea-52a80019de49.jpg)

**Comment by absoIute** [comment]
Don't want to add specific opacity settings so people can't easily fake things like the FPS counter for the Demon List but will add a low opacity setting for labels.

**Comment by BrownieGamingX5** [comment]
Maybe limit the opacity limit to 25-100% because if somebody puts it at 0%, you cant see it, so limiting it to 25% would be the way to go.

**Comment by absoIute** [comment]
actually might just make all status labels except the message one variable up to the current opacity

**Comment by BrownieGamingX5** [comment]
ok

**Comment by absoIute** [comment]
Added for next update
