### ISSUE TITLE
Face reveal program?

### ISSUE THREAD

**Issue by succmydecc** [absoIute/Mega-Hack-Pro-Future#306]
https://www.youtube.com/watch?v=k8Anu8z3ygQ the first link says a face reveal is this a joke or not? I went on to archive.org, downloaded the program, decompiled it to get 66645559 as the answer. Then I decode the base64 and it leaves me with J]^EIZ2Y]ZYS]]JDIlFOJM^LI]AS^ZMSO:NI]|JDIgN6. I have no clue what to do at this point and I dont want to spend hundreds of hours to find something that could lead to a rickroll.

**Comment by succmydecc** [comment]
@absoIute

**Comment by totallyphysicallypossible** [comment]
what

**Comment by succmydecc** [comment]
I was scrolling through absolute's videos and I found mega hack v2, I look in the description and it is the only video with face reveal, I click on the pastebin and it is deleted, so I go to archive.org and find the download then it asks me for a answer. I stopped for a month or so and then I decided to debug it, by searching for all string references and on 5E122F that is the answer. I type it in and get a base64, so I decode it, then I get J]^EIZ2Y]ZYS]]JDIlFOJM^LI]AS^ZMSO:NI]|JDIgN6, and I didn't know what to do next so I posted here.

**Comment by BrownieGamingX5** [comment]
how would this work?

**Comment by absoIute** [comment]
I don't remember lmao

**Comment by succmydecc** [comment]
OH COME ON

**Comment by succmydecc** [comment]
@absoIute i swear to god i will come to your house and strangle you alive

**Comment by totallyphysicallypossible** [comment]
BRO LMAO

**Comment by Brittank88** [comment]
@succmydecc Bro don't say stuff like that, or you'll become the first person banned from the tracker 😄

**Comment by multiwastaken** [comment]
_This comment was marked as disruptive content_
