### ISSUE TITLE
Speedhack icon, cheat engine table, change icon

### ISSUE THREAD

**Issue by succmydecc** [absoIute/Mega-Hack-Pro-Future#307]
In your website can you include a download to a cheat engine table (a verification would go by inputing a key when downloading and putting that key into a table that verifies you) the speedhack can be either a speedhack or just the icon speedhack (inspired by mhv2 and video if your confused @absoIute https://youtu.be/k8Anu8z3ygQ?t=28) and finally a option to change the icon in variables

**Comment by absoIute** [comment]
Already exists in v5 & up, I won't be making any Cheat Tables as they're redundant to me now Mega Hack exists

**Comment by succmydecc** [comment]
@absoIute what where

**Comment by Brittank88** [comment]
@succmydecc Speedhack literally has its own category in MHv6/7.

**Comment by succmydecc** [comment]
@Brittank88 No I mean, the icon speed. Not the whole game is speedhacked but the icon.

**Comment by zohnannor** [comment]
@succmydecc you can edit the speed of the player via Variables category
![image](https://user-images.githubusercontent.com/35764628/147943435-874892b0-97fe-4bc8-b685-fb28de41bd9d.png)
