### ISSUE TITLE
"Disable In Editor" Option For Shortcuts Doesn't Work Properly

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#309]
so ye it's the same, nothing changed, apart from it working when it's not enabled if you haven't closed the hack menu yet
video here https://youtu.be/sf4jesYlGCQ
ok i don't know why the video is so bad in quality this time, but still i think you can understand what's happening

**Comment by Brittank88** [comment]
Hey, the way you discuss this happening again makes me think that you already raised an issue about this in the past. In future, please comment on the original issue as we can reopen it and continue with the full context of everything that was discussed so far.

**Comment by absoIute** [comment]
Could you see if it happens without BetterEdit? might be a conflict between the two mods.

**Comment by NewAlexGamer** [comment]
ok you're right, with betteredit it bugs, without the mod it works

**Comment by zohnannor** [comment]
So the issue can be closed?
