### ISSUE TITLE
Borderless Fullscreen Fails

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#31]
This is a photo of the window when borderless fullscreen is activated:
![image](https://user-images.githubusercontent.com/24266948/111575961-9fab1180-8803-11eb-8c61-d9ccc883c91c.png)

As you can see, the window still has a slight border, more so at the top. You can also see that it isn't even stretching to the full dimensions of my screen. It also does not appear above my taskbar or fit next to it at least.

**Comment by absoIute** [comment]
fixed!
