### ISSUE TITLE
[v7] "Icons" module doesn't work fast enough(I guess)

### ISSUE THREAD

**Issue by Fl1pNatic** [absoIute/Mega-Hack-Pro-Future#311]
In MHv6 if you turned on the "Icons" module in Bypasses, even if you restarted the game, icons you picked would stay and not reset if you don't have them unlocked. But in v7 it resets, as if you didn't use the module. Please change that

**Comment by absoIute** [comment]
Fixed in beta6

**Comment by Brittank88** [comment]
Duplicate of #296
