### ISSUE TITLE
Customize Opening

### ISSUE THREAD

**Issue by succmydecc** [absoIute/Mega-Hack-Pro-Future#314]
Customize the opening of mhv7 when loading.

**Comment by Brittank88** [comment]
Could you be more specific as to what you mean? Do you mean the animation of the windows in the overlay?

**Comment by succmydecc** [comment]
The animation

**Comment by Brittank88** [comment]
What

**Comment by Brittank88** [comment]
@absoIute, I am just going to assume he is referring to the module windows' animation when you open the overlay.

**Comment by absoIute** [comment]
Yea looks like it, reverted to only the old animation for now while I work on the internal keyframes code, so no plans now
