### ISSUE TITLE
"Logged Out" Error - Provide Means To Sign In?

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#315]
Instead of having to leave the game when this occurs, go to the installer, and log in again, why not just allow the player to sign in directly from the game menu?

**Comment by absoIute** [comment]
Because of the way v6/v7 load it makes it a bit tedious to do this so it hasn't really been worth the effort, though it'd probably be a nice QoL thing, will probably consider it for v8 when the UI engine is updated but no plans for now
