### ISSUE TITLE
Frame Advance Mode

### ISSUE THREAD

**Issue by Fre1re** [absoIute/Mega-Hack-Pro-Future#316]
Add this function as a subcategory of speedhack. it will be very useful to see the frames through which the player passes

**Comment by Brittank88** [comment]
I think this might be included in #123 but I can actually see the merit of having it as its own feature in the speedhack category.

**Comment by absoIute** [comment]
Fairs, will consider for the bot

**Comment by CodeKid0** [comment]
> Fairs, will consider for the bot

Bot for megaheck? 👀

**Comment by Brittank88** [comment]
> > Fairs, will consider for the bot
> 
> Bot for megaheck? 👀

#123

**Comment by absoIute** [comment]
Implemented ready for next update
