### ISSUE TITLE
Suggestion: Don't Un-deafen When Level Complete 

### ISSUE THREAD

**Issue by MainConMan** [absoIute/Mega-Hack-Pro-Future#317]
An option for auto-deafen that would make it so it doesn't un-deafen you when you beat the level.

**Comment by succmydecc** [comment]
a good way is to use cheat engine and set the value above 100% so that you wont auto undeafen

**Comment by NewAlexGamer** [comment]
i still don't get why you would want that

**Comment by absoIute** [comment]
Why would you want to do this?

**Comment by MainConMan** [comment]
Gonna be honest, I forgot why I even wanted it lol... it doesn't make much sense
