### ISSUE TITLE
Random Icons seems to rotate in a predetermined order?

### ISSUE THREAD

**Issue by TheTruePringle** [absoIute/Mega-Hack-Pro-Future#318]
I have been a user of megahack for months now, and one of my favourite features about it is the icon randomizer. But since  I downloaded megahack v7, I’ve noticed that ive been getting the same icon sets over and over again. It turns out that everytime I close the game then open to play it again, the icons will change in the exact same order of when I played a different session. For example, the first 3 cubes everytime i open the game will always be Steamrolling cube, back on track cube, and iron man cube, and it will always be that order. I know this isn’t a very big problem but it doesn’t feel like a randomizer anymore since the icon sets seem to be predetermined somehow.

**Comment by Brittank88** [comment]
I wonder if Absolute used a PRNG algorithm (AKA pseudo-random) and it's kinda not doing a very good job of being random.

**Comment by TheTruePringle** [comment]
Some additional info on this, everytime I open the megahack menu, it seems to go into another rotation. These rotations also seem to have the same order if you were to open megahack the same amount of times and have the same amount of attempts during the session. Ex. Opening V7 2 times before doing first attempt after launch, will be the same icon set if you enter again and open the menu 2x before first attempt.Just wanted to say in case it can help in any way.

**Comment by absoIute** [comment]
Turns out seeding rand() is thread-local which is why it wasn't working, fixed for next update!
