### ISSUE TITLE
"Best Run" Text Doesn't Show Runs From X% To End

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#319]
the "best run" text doesn't show the run from x% to end after restart from last checkpoint and the normal restart from the beginning of the level, during and after practice. also happens while using startpos with and without practice. basically it doesn't show the x% to end run in any case and scenario

**Comment by Brittank88** [comment]
Yeah, I think it more accurately is "best run from 0%" right now, but having a separate "best run by length" would be cool.

**Comment by BrownieGamingX5** [comment]
Best Run is buggy with noclip. When you clip through an object, it saves where ever you are in the level. It is very weird.

**Comment by NewAlexGamer** [comment]
i mean that isn't a best run anymore if you noclip

**Comment by absoIute** [comment]
Fixed next update, best run should be "best run by length" in beta6!
