### ISSUE TITLE
Speedhack Value In Scientific Notation Prevents Speeds > 1

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#322]
how to replicate: set the scale of the menu at 0.75 or below (haven't tried to see which is the specific and precise value), insert a speed below 1 which has at least 7 or 8 digits (haven't tried this too), it won't give any problems, restart the game, it will start to give you the scientific notation for the speed.
example: speed = 0.0000005, restart the game, output = 5e-06
how to **MAYBE** fix: set the scale of the menu back to 1 or higher, restart the game and **MAYBE** you'll start to see the entire number again
how to actually fix: set whatever you can set in there to just 1, restart the game and you'll start to see the entire number again or use the scroll wheel on the number so you get to 0 and notation is gone
the problem with this is: if you don't know the fix, you're stuck at using low speeds and you can't go faster in any way possible
![image](https://user-images.githubusercontent.com/86263500/147573990-defe9b90-7dd6-41fa-ab2e-188bb279ee18.png)

**Comment by succmydecc** [comment]
If this is a self answering issue (aka a q&a) then please change it to along the lines of "how to fix the speedhack being shown in scientific notation". But a better way, is to dm absolllute so he can put it in faq/docs or fix it

**Comment by NewAlexGamer** [comment]
it doesn't fail, still works but only for speeds below 1

**Comment by Brittank88** [comment]
Oh, interesting.

**Comment by absoIute** [comment]
looking into it, thanks!

**Comment by absoIute** [comment]
current fix requires just using your scroll wheel or deleting characters from the '-' and back

**Comment by Brittank88** [comment]
I merged #391 into here, and I do believe it is important to note from that discussion that actual support for scientific notation would be appreciated.

**Comment by absoIute** [comment]
fix ready for next update!

**Comment by MainConMan** [comment]
This also needs the "Upcoming" Label, Unless it isn't used with bugs.

**Comment by Brittank88** [comment]
Done.

Hmm, the only difficulty with an "upcoming" label is that they all need to be switched to "added" when they are well... added.

**Comment by absoIute** [comment]
Hm that's true, maybe it'll be better to have an approved & implemented label instead

**Comment by Brittank88** [comment]
> Hm that's true, maybe it'll be better to have an approved & implemented label instead

I've gone for approved, upcoming and implemented. You can read their descriptions to see how the general flow goes (it's basically approved => upcoming => implemented).

I might be able to use Github Actions to automate that flow; it's something I'll investigate later.

**Comment by absoIute** [comment]
Yeah that's the best way of having it work, very clear then

Automating it would be cool too if that's possible
