### ISSUE TITLE
Verify hack also lets you bypass you cant share a empty level.

### ISSUE THREAD

**Issue by succmydecc** [absoIute/Mega-Hack-Pro-Future#323]
The verify hack doesn't bypass "You cant share a empty level", simple as that. @absoIute please bypass and @Brittank88 assign @absoIute add the labels of enhancement or bug

**Comment by NewAlexGamer** [comment]
place any object out of camera so the player doesn't see it, simple as that

**Comment by succmydecc** [comment]
That still counts as a object

**Comment by absoIute** [comment]
not something I really see any use of adding

**Comment by succmydecc** [comment]
I REALLY NEED THO

**Comment by succmydecc** [comment]
just silently add it with the verify hack

**Comment by absoIute** [comment]
what would you need it for?

**Comment by NewAlexGamer** [comment]
other than flexing the "i uploaded an empty level" there's no real use for it lol

**Comment by succmydecc** [comment]
I need it to test

**Comment by succmydecc** [comment]
@absoIute Please look in to this more. You dont need to add a new option, just implement within verify hack.

**Comment by Brittank88** [comment]
> The verify hack doesn't bypass "You cant share a empty level", simple as that. @absoIute please bypass and @Brittank88 assign @absoIute add the labels of enhancement or bug

Don't tell us how to run our tracker. We'll handle your (and anyone else's) issues however they should be handled. Also, stop @mentioning us, it's not going to make us act on things faster. Look at how many issues there are. Absolute is a human being, he can't magically give his attention to all of them at once. Be patient.

**Comment by Brittank88** [comment]
Furthermore, this feature is basically useless and would allow people to bloat the GD servers with random empty levels (unless it does what it should whereby it just refuses the level serverside anyways).
