### ISSUE TITLE
MegaHack with BlueStacks

### ISSUE THREAD

**Issue by TheBigBoiPenguin** [absoIute/Mega-Hack-Pro-Future#326]
I use BlueStacks because the Steam version of Geometry Dash doesn't work correctly on my PC. Is there a way to use MegaHack V7 Pro or MegaHack v5 with BlueStacks?

**Comment by succmydecc** [comment]
How does the steam version of GD doesn't work? Is it a save file error?

**Comment by TheBigBoiPenguin** [comment]
It wasn't opening, so I searched the internet for solutions. I've tried everything I saw, including the save file fix application.

**Comment by NewAlexGamer** [comment]
when this used to happen to me, reinstalling till it started was working

**Comment by succmydecc** [comment]
@TheBigBoiPenguin you shouldn't have deleted everything with gd. If you delete your CCGameManger.dat and CCLocalLevels.dat then you will have wiped all your progress and created levels. https://steamcommunity.com/app/322170/discussions/0/133256240740158903/ see if this works for you, if not then I don't know what to do at that point. Also @absoIute said he will never create a bluestack version, so yeah.

**Comment by absoIute** [comment]
No plans to support Mega Hack on Android anytime soon

**Comment by TheBigBoiPenguin** [comment]
@succmydecc i have copies of the cc files.
