### ISSUE TITLE
Dark mode for your site

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#327]
ever thought of putting dark mode on the site so we don't burn our eyes? ( ͡° ͜ʖ ͡°)

**Comment by succmydecc** [comment]
dark reader

**Comment by NewAlexGamer** [comment]
sure but the site owner editing the css is surely more reliable than an extension based on "i read code and i guess what is supposed to be dark"

**Comment by absoIute** [comment]
#172

**Comment by Brittank88** [comment]
Duplicate of #172
