### ISSUE TITLE
Behaviour of "NoClip Accuracy"

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#33]
I feel that instead of the setting enabling and disabling NoClip itself, it should just enable or disable the accuracy meter _for when you have NoClip or Experimental NoClip enabled_. That way, I can leave it on, and simply use it when I turn NoClip or Experimental NoClip on. It also fixes the fact that it's technically a duplicate feature in some ways.

**Comment by absoIute** [comment]
added support for experimental noclip accuracy ready for next update, though it can still be used as a separate option to regular noclip
