### ISSUE TITLE
Suggestion: Auto Deafen at List %

### ISSUE THREAD

**Issue by multiwastaken** [absoIute/Mega-Hack-Pro-Future#331]
Basically auto deafen at [something]% except you automatically set it to the level's list record required percentage (if it's a list demon ofc)

**Comment by zohnannor** [comment]
Why would you need that? Just set it by hand

**Comment by absoIute** [comment]
Not something I plan on doing right I'm afraid, would complicate auto-deafen & it isn't usually where people want to deafen
