### ISSUE TITLE
Verify hack doesnt seem to do anything

### ISSUE THREAD

**Issue by Shashamove** [absoIute/Mega-Hack-Pro-Future#333]

**Comment by NewAlexGamer** [comment]
it visually doesn't do anything, but when you try to upload a level that you haven't verified, the game will tell you to verify it. with verify hack on you don't need to verify the level
![image](https://user-images.githubusercontent.com/86263500/147825497-2599f077-d702-48b4-bb25-f3c55ad56a73.png)
