### ISSUE TITLE
Geometry Dash Steam broken for me.

### ISSUE THREAD

**Issue by TheBigBoiPenguin** [absoIute/Mega-Hack-Pro-Future#337]
This isn't directly related to MegaHack, but this issue is stopping me from using MegaHack so I thought I'd put it here anyway.
Geometry Dash on Steam wasn't opening, so I searched the internet for solutions. I've tried everything I saw, including the save file fix application.
I then deleted everything on my computer with the name "Geometry Dash" on it. I reinstalled the game but it still didn't open. Then I saw that there was nothing in my AppData folder even though I have copies of the cc. files so I didn't lose anything. When I put the copies in the Appdata folder, nothing happened. Can someone please help me with this issue, because at the moment I'm using BlueStacks to play Geometry Dash but I really want to use MegaHack and MegaHack isn't available on BlueStacks.

Also I don't know how to add a label to this post :P

**Comment by succmydecc** [comment]
Stop annoying absoIute, he will never have plans to make a android version. By doing so, you can get banned (and will be the first person to do so) off the repo

**Comment by multiwastaken** [comment]
> Stop annoying absoIute, he will never have plans to make a android version. By doing so, you can get banned (and will be the first person to do so) off the repo

he never asked for megahack on android bro read the goddamn post

**Comment by NewAlexGamer** [comment]
on the official geometry dash discord server there's a channel called "support". there you can ask people about this problem. there they will surely know more about the problem with live reaction from someone and detailed reports

**Comment by TheBigBoiPenguin** [comment]
Alright, thanks for the help!

**Comment by ExplodingBill** [comment]
When you first open the game and it asks for admin perms, have you allowed it, it needs admin to install needed libraries onto your computer for it to work

**Comment by TheBigBoiPenguin** [comment]
> When you first open the game and it asks for admin perms, have you allowed it, it needs admin to install needed libraries onto your computer for it to work

No, It doesn't ask me for admin permissions and it doesn't open even if I give it admin permissions.
