### ISSUE TITLE
Allow "Flicker Fix" With FPS Bypass?

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#338]

**Comment by absoIute** [comment]
Flicker Fix is meant to help mitigate Mega Hack's UI flickering on certain AMD/ATI graphics, nothing to do with screen tearing

**Comment by Haiplay12** [comment]
hello everyone, why don't I even have such a function, I have the 8th version of the megahack, but there is no such function. There are only unlock fps, unlock tps, advanced, Vsync, Borderless Classic, fullscreen and Exclusive, but there is no flicker fix
