### ISSUE TITLE
Top Ground Bugs Out In A Couple Levels

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#339]
Was playing the unnerfed version of "Stereo Demoness" by MaJackO, and while playing it with "Smart Start Pos" on, the top ground completely disappeared.
![20220101202859_1](https://user-images.githubusercontent.com/60493629/147866274-f585a2a6-4ab9-4f59-9a72-cec82af7f6e9.jpg)

**Comment by absoIute** [comment]
Where did you put the StartPos exactly? (send a screenshot)

**Comment by BrownieGamingX5** [comment]
![20220103110800_1](https://user-images.githubusercontent.com/60493629/147969714-a99ab118-85c7-494f-92d8-3add34783bbe.jpg)

**Comment by absoIute** [comment]
Uncheck ship in the StartPos, Smart StartPos current can't switch to cube mode (it just does nothing), but a fix is ready for next update
