### ISSUE TITLE
"Player" Hack Menu Scrollable When Not Required

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#34]
In v6.2.0 beta, the "Player" hacks menu has a scroll bar to fit all items... yet it could actually just fit all of them without a scroll bar:
![image](https://user-images.githubusercontent.com/24266948/111576458-a423fa00-8804-11eb-822f-12697329d97f.png)

I feel, if possible, the maximum length of hack menus should take into account the height of the window.

**Comment by absoIute** [comment]
since v6.3.0-beta4 they now scale dynamically to your resolution!
