### ISSUE TITLE
Robot Gamemode Doesn't Work With "Practice Big Fix"

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#340]
The robot gamemode doesn't store the momentum in practice mode, just like all other gamemodes. And yes, I found this out a while ago, but forgot to send it since then.

**Comment by NewAlexGamer** [comment]
it works, simply when you put a checkpoint while you hold the game can't know if you'll still hold or release at that exact moment. if you actually test it you can see the robot doing that small jump if you placed the checkpoint while holding, and the robot falling as it should when you place after releasing
we just have to learn when to put checkpoints with the robot, never while holding or clicking, but before and after
