### ISSUE TITLE
Persisting Attempt Variables

### ISSUE THREAD

**Issue by succmydecc** [absoIute/Mega-Hack-Pro-Future#349]
have a option that allows for variables to stay between attempts

**Comment by Brittank88** [comment]
What would be the purpose of this? A lot of the variables (that reset) only make sense when they reset after each attempt.

**Comment by succmydecc** [comment]
I feel the use of this mainly because, I want to change my icon speed persistently without the annoyance of having to do it again.

**Comment by succmydecc** [comment]
@Brittank88

**Comment by Brittank88** [comment]
> @Brittank88 just for you to know I replied

It notifies me anyways, you don't need to do that.

**Comment by Brittank88** [comment]
> I feel the use of this mainly because, I want to change my icon speed persistently without the annoyance of having to do it again.

..I must be misunderstanding what these "variables" are entire. I thought this referred to the information display you can configure the entries of.

**Comment by succmydecc** [comment]
simply add a option in the variable window and add for persisting variables (any variable in the window)

**Comment by absoIute** [comment]
You can just set the attempts variable to what it was before, freeze the attempts or use total attempts for the count to be persistent between sessions, don't see the need for a per-session total attempts mod

**Comment by succmydecc** [comment]
What do you mean? I freeze the attempts and variables arent consistent

**Comment by absoIute** [comment]
Then just use the variable setter, I just don't feel like this needs its own separate mod

**Comment by succmydecc** [comment]
I dont get what you mean. I want a mod in the varaibles window that allows for variables to be persistent. Aka when you set your speed, once you die it changes back to default. Make it so that it wont change after dying.

**Comment by succmydecc** [comment]
@absoIute I dont get what you mean. I want a mod in the varaibles window that allows for variables to be persistent. Aka when you set your speed, once you die it changes back to default. Make it so that it wont change after dying.

**Comment by succmydecc** [comment]
Also sorry if i sound really aggressive.

**Comment by absoIute** [comment]
Ohh I see what you mean, not something I want to bring to the Variables window but may implement it for some aspects in the future as a separate featuere
