### ISSUE TITLE
Clicking On Geometry Dash Icon Won't Open 

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#350]
https://user-images.githubusercontent.com/60493629/148162406-155b5c3c-839d-4fa0-8590-a512f10bdcdc.mp4

If you click on the Geometry Dash icon in the taskbar, it won't open up just like all other tabs. You have to manually click the "Play"  button in your Steam library. If there was a fix for this, this would be so much easier to open Geometry Dash that way.

**Comment by zohnannor** [comment]
If I drag the executable file (`E:\Steam\steamapps\common\Geometry Dash\GeometryDash.exe` or the shortcut to this file) to the taskbar then I can open the game by clicking the icon.
Maybe you are pinning the shortcut Steam created for you? (it contains `steam://rungameid/322170`)

**Comment by BrownieGamingX5** [comment]
Maybe give me a video for a visual on how to do that?

**Comment by zohnannor** [comment]
????
![image](https://user-images.githubusercontent.com/35764628/148267760-3332d046-f0a6-47fc-bff0-587aac5a859f.png)
![image](https://user-images.githubusercontent.com/35764628/148267898-7f4c0b45-47cb-4907-94c9-863ad4a0d0fa.png)

**Comment by BrownieGamingX5** [comment]
That's what I did, but it didn't work. I had it already pinned to my taskbar before doing it.

**Comment by zohnannor** [comment]
Idk, it works for me but only if I pin executable and not the Steam shortcut

**Comment by hackercat27** [comment]
this is because opening the geometry dash executable directly doesn't work for reasons that i personally don't understand (steam maybe? idk) but there's a text file that you can put in your geometry dash directory that solves this issue

**Comment by Brittank88** [comment]
Closing as invalid because this is not a Mega Hack bug, this just a thing that happens with certain games. @zohnannor @hackercat27 feel free to continue the conversation here if you want, if it can help out Brownie.
