### ISSUE TITLE
Geometry Dash not opening on Steam

### ISSUE THREAD

**Issue by TheBigBoiPenguin** [absoIute/Mega-Hack-Pro-Future#351]
This isn't directly related to MegaHack, but this issue is stopping me from using MegaHack so I thought I'd put it here anyway.

Geometry Dash on Steam wasn't opening, so I searched the internet for solutions. I've tried everything I saw, including the save file fix application.
I then deleted everything on my computer with the name "Geometry Dash" on it. I reinstalled the game but it still didn't open. Then I saw that there was nothing in my AppData folder even though I have copies of the cc. files so I didn't lose anything. When I put the copies in the Appdata folder, nothing happened. Can someone please help me with this issue, because at the moment I'm using BlueStacks to play Geometry Dash but I really want to use MegaHack and MegaHack isn't available on BlueStacks.

**Comment by succmydecc** [comment]
Stop spamming the repo with gd not opening on steam. This will get you banned. Please ask in the appropriate communites.

**Comment by NewAlexGamer** [comment]
#337

**Comment by Brittank88** [comment]
You have literally posted a direct clone of this issue on the same tracker.

**We will not get to your issue faster because you posted it more than once.**

This isn't even a valid issue because it is not caused by MH. This is not a GD issues forum, this is a tracker for MH-related issues.
