### ISSUE TITLE
Speedhack Game Crash Reset

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#352]
Note: This is an example. 

If you set your speedhack from 0.5x to 0.25x, then the game crashes for some reason, you enter back into Geometry Dash, the speedhack value would still be 0.5x (in this case). The same happens with anything you set it to when the game crashes. And yes, I have just tested this.

**Comment by totallyphysicallypossible** [comment]
You might need a crashlog when something like this has never happened to anyone

**Comment by Brittank88** [comment]
This is because data saving probably occurs on game open/close. Not sure if this behaviour could (or even should...) be adjusted.

**Comment by absoIute** [comment]
Fixed in GM1, was only an issue with the classic speedhack
