### ISSUE TITLE
Auto Extension Loader

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#353]
The title says it all.

**Comment by NewAlexGamer** [comment]
it has been a thing for about 1 year and more

**Comment by BrownieGamingX5** [comment]
wdym?

**Comment by Brittank88** [comment]
This is already a feature. Just put the correct DLLs into the `extensions` folder in the Geometry Dash installation folder.

**Comment by succmydecc** [comment]
@Brittank88, the post used to say "I want to inject a extension but I don't want to close the game to load the extension. Having a option to load the extension without having to close the game would be appreciated. Thanks"

**Comment by succmydecc** [comment]
TL;DR: load a extension without exiting the game

**Comment by Brittank88** [comment]
In that case it might not even be possible and is very likely to be more hassle to implement than its worth. It's literally just a game restart, for an extension you'd only install once on average.
