### ISSUE TITLE
Switching Startpos should not affect attempt count

### ISSUE THREAD

**Issue by crewly** [absoIute/Mega-Hack-Pro-Future#355]
I'm practicing a level and I put around 10 startpos there. After some time, I realized that everytime I switch positions, it adds 1 to my attempt count. This has caused me to waste 500+ attempts on a level, just by switching back and forward. You may find a video down below demonstrating it.

https://user-images.githubusercontent.com/32331530/148649040-a039d1ce-b081-46d7-ba09-5b6c64b6e7c5.mp4

**Comment by absoIute** [comment]
It's a bug if you have "Freeze Session Attempts" enabled in Freeze Attempts, even when that mod is off, fix ready for next update
