### ISSUE TITLE
Remove The MHV7 Watermark 

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#358]
![20220108135804_1](https://user-images.githubusercontent.com/60493629/148661292-66fa274c-407e-4b2d-9034-7b882bb02d45.jpg)

**Comment by zohnannor** [comment]
why

**Comment by NewAlexGamer** [comment]
used to tell which version you have, also people can literally steal the thing saying: ye that's mine btw

**Comment by BrownieGamingX5** [comment]
maybe put it in the "Mega Hack Pro" tab.

**Comment by absoIute** [comment]
It's there & big so when I'm dealing with issues I can tell what version it is clearly, sometimes hard to tell when it's buried in a small text box especially on compressed video
