### ISSUE TITLE
Port Mega Hack V6 to Linux

### ISSUE THREAD

**Issue by Astro-re** [absoIute/Mega-Hack-Pro-Future#36]
It seems difficult but a lot of people play Geometry Dash on Linux and frankly it would be a change that doesn't do a LOT but it's something that will make just a few more people happy. I've also already purchased and used MHV6 on Windows but after switching to Linux (which I cannot get out of) I simply can't play GD the same on Linux without a MHV6 port. Thanks for reading :D

**Comment by Brittank88** [comment]
This is fair enough, but I have no idea what the limitations or difficulty of this are.

**Comment by RootRobo** [comment]
i think you need to install wine and run the Mega Hack Patcher on your steam directory for GD ((steam folder)/steamapps/common/Geometry Dash), as steam uses proton to run the Windows version of GD on Linux, so it should work that way

**Comment by Brittank88** [comment]
That would be awesome and miraculous if that just worked with no weirdness

**Comment by Astro-re** [comment]
I actually tried that method, and I did several times, came with no success.

**Comment by RootRobo** [comment]
I just want to give an update, I managed to get it working. I extracted the MegaHack zip File in the Desktop of the Wine Prefix (`/home/USER/.steam/debian-installation/steamapps/compatdata/322170/drive_c/users/steamuser/Desktop`) and then ran the following commands:

`cd ~/.steam/debian-installation/steamapps/compatdata/322170/pfx`

`STEAM_COMPAT_DATA_PATH="/home/USER/.steam/debian-installation/steamapps/compatdata/322170" WINEPREFIX=$PWD \
"/home/USER/.steam/root/steamapps/common/Proton 3.7/proton" run ./drive_c/users/steamuser/Desktop/MegaHackProPatcher_620_beta1/MegaHackPro.exe`

(Make sure to copy paste the last 2 lines as one command and replace USER with your username)

I got these commands from here: https://gist.github.com/michaelbutler/f364276f4030c5f449252f2c4d960bd2

**Comment by Astro-re** [comment]
> I just want to give an update, I managed to get it working. I extracted the MegaHack zip File in the Desktop of the Wine Prefix (`/home/USER/.steam/debian-installation/steamapps/compatdata/322170/drive_c/users/steamuser/Desktop`) and then ran the following commands:
> 
> `cd ~/.steam/debian-installation/steamapps/compatdata/322170/pfx`
> 
> `STEAM_COMPAT_DATA_PATH="/home/USER/.steam/debian-installation/steamapps/compatdata/322170" WINEPREFIX=$PWD \ "/home/USER/.steam/root/steamapps/common/Proton 3.7/proton" run ./drive_c/users/steamuser/Desktop/MegaHackProPatcher_620_beta1/MegaHackPro.exe`
> 
> (Make sure to copy paste the last 2 lines as one command and replace USER with your username)
> 
> I got these commands from here: https://gist.github.com/michaelbutler/f364276f4030c5f449252f2c4d960bd2

You are an absolute legend, thank you so much for doing this.

**Comment by Brittank88** [comment]
> I just want to give an update, I managed to get it working. I extracted the MegaHack zip File in the Desktop of the Wine Prefix (`/home/USER/.steam/debian-installation/steamapps/compatdata/322170/drive_c/users/steamuser/Desktop`) and then ran the following commands:
> 
> `cd ~/.steam/debian-installation/steamapps/compatdata/322170/pfx`
> 
> `STEAM_COMPAT_DATA_PATH="/home/USER/.steam/debian-installation/steamapps/compatdata/322170" WINEPREFIX=$PWD \ "/home/USER/.steam/root/steamapps/common/Proton 3.7/proton" run ./drive_c/users/steamuser/Desktop/MegaHackProPatcher_620_beta1/MegaHackPro.exe`
> 
> (Make sure to copy paste the last 2 lines as one command and replace USER with your username)
> 
> I got these commands from here: https://gist.github.com/michaelbutler/f364276f4030c5f449252f2c4d960bd2

How in the heck did you figure this out lmao

Very nice work!

**Comment by Brittank88** [comment]
Figured I should pin this issue so people looking to use MHv6 on Linux can see that there is indeed a way to run it. Thanks again @RootRobo for figuring this out!

**Comment by TheDIGS** [comment]
Does this method work for v5 as well?

**Comment by Brittank88** [comment]
Could always experiment and find out! This seems like quite a complex process though, involving both Wine and Steam's own solution for running non-Linux stuff on Linux.

**Comment by absoIute** [comment]
as long as the installer is ran under the same version/instance of Proton as GD it should install fine!

**Comment by Tytanium13** [comment]
> I just want to give an update, I managed to get it working. I extracted the MegaHack zip File in the Desktop of the Wine Prefix (`/home/USER/.steam/debian-installation/steamapps/compatdata/322170/drive_c/users/steamuser/Desktop`) and then ran the following commands:
> 
> `cd ~/.steam/debian-installation/steamapps/compatdata/322170/pfx
> 
> `STEAM_COMPAT_DATA_PATH="/home/USER/.steam/debian-installation/steamapps/compatdata/322170" WINEPREFIX=$PWD \ "/home/USER/.steam/root/steamapps/common/Proton 3.7/proton" run ./drive_c/users/steamuser/Desktop/MegaHackProPatcher_620_beta1/MegaHackPro.exe`
> 
> (Make sure to copy paste the last 2 lines as one command and replace USER with your username)
> 
> I got these commands from here: https://gist.github.com/michaelbutler/f364276f4030c5f449252f2c4d960bd2

Does this work with V5 also? I do not have the money currently to buy V6 just yet, but if it works for V5 also then heck yes!

**Comment by RoootTheFox** [comment]
> > I just want to give an update, I managed to get it working. I extracted the MegaHack zip File in the Desktop of the Wine Prefix (`/home/USER/.steam/debian-installation/steamapps/compatdata/322170/drive_c/users/steamuser/Desktop`) and then ran the following commands:
> > 
> > `cd ~/.steam/debian-installation/steamapps/compatdata/322170/pfx
> > 
> > `STEAM_COMPAT_DATA_PATH="/home/USER/.steam/debian-installation/steamapps/compatdata/322170" WINEPREFIX=$PWD \ "/home/USER/.steam/root/steamapps/common/Proton 3.7/proton" run ./drive_c/users/steamuser/Desktop/MegaHackProPatcher_620_beta1/MegaHackPro.exe`
> > 
> > (Make sure to copy paste the last 2 lines as one command and replace USER with your username)
> > 
> > I got these commands from here: https://gist.github.com/michaelbutler/f364276f4030c5f449252f2c4d960bd2
> 
> Does this work with V5 also? I do not have the money currently to buy V6 just yet, but if it works for V5 also then heck yes!

it should work fine for megahack v5, just try it and see. If it doesnt work im pretty sure there is some way to make it run.

**Comment by Brittank88** [comment]
@All-Contributors please add @absoIute for platform.

**Comment by Brittank88** [comment]
@all-contributors please add @RoootTheFoxold for platform, question, research, tutorial.

**Comment by Brittank88** [comment]
@RoootTheFox oops didn't notice you have a new account - have noticed your Linux-related help for v6/7 though and wanted to give you credit! ❤️

**Comment by Brittank88** [comment]
@all-contributors please add @RoootTheFox for platform, question, research, tutorial.

**Comment by Brittank88** [comment]
@all-contributors please remove @RoootTheFoxold

**Comment by Brittank88** [comment]
@All-Contributors please add @RoootTheFox for userTesting.

(Missed one!)

**Comment by torzod** [comment]
there's a pretty easy way to do this that i've been using for ages: rename GeometryDash.exe to something else, replace it with the megahack executableby renaming megahack to GeometryDash.exe, run the game through steam as normal, and it will pull up the MH installer. select whatever you renamed the actual game executable to, install, and you're good to rename things back to what the should be, and the game and hacks will work just fine.

**Comment by Brittank88** [comment]
> there's a pretty easy way to do this that i've been using for ages: rename GeometryDash.exe to something else, replace it with the megahack executableby renaming megahack to GeometryDash.exe, run the game through steam as normal, and it will pull up the MH installer. select whatever you renamed the actual game executable to, install, and you're good to rename things back to what the should be, and the game and hacks will work just fine.

I'm honestly surprised this works. Nice find.

**Comment by torzod** [comment]
absolute and i labbed it out a while back together, but this was mostly my
idea

**Comment by Brittank88** [comment]
https://github.com/all-contributors please add @torzod for userTesting, platform, question, research, tutorial.

**Comment by Brittank88** [comment]
@all-contributors please add @torzod for userTesting, platform, question, research, tutorial.

**Comment by torzod** [comment]
if needed i can also be contacted on discord @ouroya#5680

**Comment by fwookerton** [comment]
if anyone needs it, I (and ChatGPT) made a script that makes installing Mega Hack very easy on Linux. Hopefully this resolves a lot of headaches.
[https://github.com/fwookerton/mega-hack-linux-installer](https://github.com/fwookerton/mega-hack-linux-installer)

**Comment by RoootTheFox** [comment]
I've made such a script too (that tries to be user-friendly while having v7 support); putting the link here for completeness' sake: https://github.com/RoootTheFox/Linux-MegaHack-Installer
