### ISSUE TITLE
2-Player Mode Gravity Reverse

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#360]
When you play a 2-player mode level, then go into a cube or robot portal, your gravity reverses and you are upside down. This is incredibly annoying when testing something that contains 2-player mode in it.

**Comment by totallyphysicallypossible** [comment]
This is a vanilla issue and fixing this could either provide an advantage or a disadvantage.

**Comment by absoIute** [comment]
Not something I'm going to add since it'd just break certain levels, not messing with game physics like that
