### ISSUE TITLE
on mhv6, if I disable 3 or more hacks at the same time, geometry dash crashes. it is only possible by keybinds

### ISSUE THREAD

**Issue by C1intOn110309** [absoIute/Mega-Hack-Pro-Future#363]
for example, if I disable hitboxes, No Death Effect, and speedhack at the same time, it crashes.

**Comment by NewAlexGamer** [comment]
I believe v6 won't get any other updates since v7 is an update of v6. Doesn't require any other purchase in case you didn't know, simply download the v7 installer from the website and reinstall it

**Comment by absoIute** [comment]
v7 doesn't have this issue, update
