### ISSUE TITLE
best run end percentage can sometimes show 102, 101, 103, etc because of level lenght

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#364]
this is a 5 seconds level just for contest
![Screenshot_2](https://user-images.githubusercontent.com/86263500/148800684-3655cd1a-cd17-4166-9418-c5e1481a4a50.png)

**Comment by absoIute** [comment]
fix ready for next update

**Comment by MainConMan** [comment]
@Brittank88 IDK if you saw, (if you did I'm sorry) but this should also have the upcoming label.
