### ISSUE TITLE
Make OBS Work Better With MHV7

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#367]
1. Make the OBS preview show MegaHackV7 instead of just going into windowed mode to show it.

2. Make Geometry Dash on OBS load up instantly, instead of waiting for up to 30 seconds for it to load.

**Comment by ExplodingBill** [comment]
both of those are issues with obs, for #1, you can't just record the window in fullscreen, you have to make it record the whole screen and for #2 that just depends on the speed of your computer

**Comment by BrownieGamingX5** [comment]
damn it dude.

**Comment by totallyphysicallypossible** [comment]
1. Go to OBS, Select the capture for GD, then enable "Capture third-party overlays (such as steam)".
2. PC Issue

**Comment by BrownieGamingX5** [comment]
Thank you! It worked!
