### ISSUE TITLE
Implement Cheat Engine Speedhack

### ISSUE THREAD

**Issue by jojo989** [absoIute/Mega-Hack-Pro-Future#37]
add the Cheat engine speedhack

**Comment by Brittank88** [comment]
In future, please give your issues a proper title and try to be as descriptive as you can (this includes _why_ a feature should be implemented).

**Comment by Brittank88** [comment]
In this case, I can see the merit of being able to decide which speedhack 'method' to use, as it might allow for better compatibility with other programs such as ybot or zbot.

**Comment by absoIute** [comment]
added in v6.3.0-beta1
