### ISSUE TITLE
Physics FPS Bypass (Like GDHM & Itailian APK Downloader On Android)

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#370]

**Comment by totallyphysicallypossible** [comment]
there's a mod for that
https://github.com/matcool/small-gd-mods/releases/download/mods/fps-multiplier.dll

**Comment by BrownieGamingX5** [comment]
ik, but i want it integrated into gd, and not an extension
=

**Comment by totallyphysicallypossible** [comment]
What's the problem with a seperate extension?????????

**Comment by absoIute** [comment]
use the extension
