### ISSUE TITLE
auto like/dislike and rate on levels

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#371]
a hack/hacks that likes or dislikes and rates the level upon entering it, actually playing or just in the menu
purpose: mainly to make achievements and icons less annoying and boring to get

**Comment by succmydecc** [comment]
Well, i dont think absolllute would like to give you free hacks as he mostly focuses on gameplay

**Comment by NewAlexGamer** [comment]
oh ye right sorry
![Screenshot_1](https://user-images.githubusercontent.com/86263500/149355757-4fde19c6-5f8d-4524-8f1f-96717c1a85f5.png)
![Screenshot_2](https://user-images.githubusercontent.com/86263500/149355766-40ed3bbc-a560-45a7-9ef9-1c5df85d98c5.png)

**Comment by RuanauR** [comment]
> also #239 is approved and #154 is considering, and since this is very similar do both, kind of, there are more chances of this getting actually added than discarded

This is a bad idea, I dont like the Idea of being able to bot dislikes.

**Comment by NewAlexGamer** [comment]
you can like/dislike a level once in your lifetime, and if you are planning on dislike/like botting, chances are you already have a script to enter the level, like/dislike, exit the level, scroll, enter a new level

**Comment by absoIute** [comment]
Not something I'd really want to do, I feel liking/disliking a level is something you should do after playing the level yourself

**Comment by succmydecc** [comment]
Thanks @absoIute.
