### ISSUE TITLE
Camera Craziness 

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#372]
I don't even get how this happens.

https://user-images.githubusercontent.com/60493629/149230990-8945d752-ff0f-4a6a-b59a-b7c4589c7d5b.mp4

**Comment by succmydecc** [comment]
The level does that, not mhv7

**Comment by absoIute** [comment]
Seems like a GD bug and not something specific to do with Mega Hack
