### ISSUE TITLE
No Death Effect Sub-Option To Disable Death Effect Shake

### ISSUE THREAD

**Issue by hackercat27** [absoIute/Mega-Hack-Pro-Future#374]
I know there's an option in gd vanilla settings to disable all shake effects, but i would prefer to not have shake triggers and such be disabled because without them a lot of levels feel a lot emptier, but having the shake effects on makes the death animation feel kinda clunky

**Comment by totallyphysicallypossible** [comment]
this
![image](https://user-images.githubusercontent.com/94307704/150093319-f90c7c4b-312d-428a-92af-aa08edcd65ba.png)

**Comment by Brittank88** [comment]
@totallyphysicallypossible You're saying this already exists in GD right? In that case, I'll close this as invalid (no hard feelings!).
