### ISSUE TITLE
Demonlist | Erebus Positioning?

### ISSUE THREAD

**Issue by Nicko2102** [absoIute/Mega-Hack-Pro-Future#375]
Erebus by BoldStep and ErebuS by Platnuu seem to be switched lol
![image](https://user-images.githubusercontent.com/83476899/149962982-e67fb501-7d34-45d1-9bdd-f968ad47752d.png)
![image](https://user-images.githubusercontent.com/83476899/149963011-1f01eb66-3e2e-4277-ad34-bc51608c41ac.png)

**Comment by Brittank88** [comment]
Must be case-sensitivity issues + non-guaranteed ordering...

**Comment by zohnannor** [comment]
> Oh wait don't you manually add them to the list Absolute? Lol

That'd be very strange of Absolute cause there is literally [pointercrate REST API documentation](https://pointercrate.com/documentation/index) so I don't know the true reason those 2 levels are swapped.

**Comment by Nicko2102** [comment]
I dont think he uses the API though, since it takes quite some time for the in-game list to be updated and it doesnt happen in real time

**Comment by zohnannor** [comment]
Fair enough

**Comment by succmydecc** [comment]
Use adafs way, fetch the demonlist, impossible levels list, challenge list. just ask adaf, no need to prove your the big guy absolute by doing every thing on your own.

**Comment by zohnannor** [comment]
What about you won't tell absolute what to do? This is his project, his issue tracker and he can do whatever he decide to do and in what way.

**Comment by Nicko2102** [comment]
hes salty that hes not mod, hes been trying so hard

**Comment by Brittank88** [comment]
Trying so hard to be a PITA maybe. Tagging Absolute and me unnecessarily, creating junk issues, spurring off-topic conversation (technically includes this one), having an attitude when their suggestions aren't """listened to""".

**Comment by Brittank88** [comment]
That said, I'm locking this as off-topic because I think enough about the actual issue here has been said and it is indeed going in an entirely different direction of conversation.

**Comment by absoIute** [comment]
added fix (probably won't be needed much longer now ErebuS is almost off the list)
