### ISSUE TITLE
Migrate Issue/Suggestion Tracker

### ISSUE THREAD

**Issue by succmydecc** [absoIute/Mega-Hack-Pro-Future#378]
I want this github to be moved over to the offical website so that more people will recongize it. This will add a ton of suggestions which will be uncomfortable for @absoIute but this will help mhv7 as a whole.

**Comment by Brittank88** [comment]
For the love of God please stop mentioning Absolute.

Also yes, we have discussed the concept. The difficulty lies in finding an appropriate self-hostable issue tracker that does not cost too much (or ideally is free). We're looking into it.

**Comment by succmydecc** [comment]
How else am I supposed to get his attention. Also use freenom domains.

**Comment by Brittank88** [comment]
I appreciate the research but it's not about domains/hosting, it's about the issue tracker software.

**Comment by succmydecc** [comment]
What?

**Comment by Brittank88** [comment]
We need software to emulate how this Github issue tracker works, that we can host locally on Absolute's website. Github cannot be self-hosted.

**Comment by succmydecc** [comment]
Just make a simple website with a few designs from JSParticles, specifically triangle because its the most coolest. Next just add a new issue button and assign you with permissions. Then tweet about it, and maybe make a youtube video. Then put it next to projects below mega hack v7. Then make a search with a few filters. Use the above websites (porkbun). Your done.

**Comment by Brittank88** [comment]
That's hilarious that you think it's that easy...

**Comment by succmydecc** [comment]
eh, its a simplification

**Comment by succmydecc** [comment]
but also can I get mod on this repo btw, i think out of my heart I can be a good issue helper? ive commented a ton giving solutions.

**Comment by succmydecc** [comment]
Also can I have mod for this repo, ive helped out a lot 😭

**Comment by NewAlexGamer** [comment]
first rule to become a mod: not ask for mod

**Comment by zohnannor** [comment]
lmao
![image](https://user-images.githubusercontent.com/35764628/150405430-2ab9b207-41e9-4097-9a22-7759283cc2bf.png)

**Comment by Nicko2102** [comment]
lmao x2
![image](https://user-images.githubusercontent.com/83476899/150441021-fbfc7611-a173-4df6-b488-885aa4e43994.png)

**Comment by succmydecc** [comment]
I do.

**Comment by absoIute** [comment]
It's something to consider but not anything I have the time for right now with my uni workload on top of already maintaining Mega Hack & other projects, though definitely looking into it

**Comment by Brittank88** [comment]
I get you, man - uni is such a big weight...

**Comment by Brittank88** [comment]
Dear god. Please put your mental health above stuff like this. Lmk if I can help in any way.

**Comment by Brittank88** [comment]
Rolled into #431!
