### ISSUE TITLE
View All Keybinds

### ISSUE THREAD

**Issue by Nicko2102** [absoIute/Mega-Hack-Pro-Future#379]
Is there any way to simply see all your keybinds? If not, can you make it possible?

**Comment by NewAlexGamer** [comment]
actually this was a thing in v6, apparently it got removed. this reminds me once again that the new keybinds system is really slow to use and often takes me 1 full minute to assign a key to any hack lol

**Comment by zohnannor** [comment]
#201, https://github.com/absoIute/Mega-Hack-Pro-Future/issues/168#issuecomment-973244257

**Comment by Nicko2102** [comment]
> #201
That issue was authored by me as well (I forgot about it) , now I'm simply wondering about the keybind viewing system since the old way of assigning keybinds doesn't seem to be coming back sadly :(
Also absolute, why did you change the keybind assigning system in the first place? I'm not trying to hate, I'm actually just curious if there was an issue with the old one of if you found this easier or something.

**Comment by absoIute** [comment]
The way the old system worked was a mess internally, the new one works a lot cleaner, what I'll probably end up doing for v7.1/.2 is have some hybrid system which brings some features of the old keybind system back like View Keybinds

**Comment by Brittank88** [comment]
Duplicate of #201
