### ISSUE TITLE
minor glitch: useless button in editor

### ISSUE THREAD

**Issue by Underkirby** [absoIute/Mega-Hack-Pro-Future#383]
there is a random button in the editor that has no purpose

[Link to video](https://youtu.be/r3wrJD86aLQ)

**Comment by Nicko2102** [comment]
oh i thought that was betteredit but i guess not lol, might have been added accidentally while absolute was changing the custom object thing or it might be for favourites, not sure

**Comment by Underkirby** [comment]
Yeah, I agree with your guess

**Comment by absoIute** [comment]
lmao did not mean to leave that there, fix ready for next update
