### ISSUE TITLE
MegaHackV7 Scaling Bug(?)

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#387]
If you have the tab at 1x scale, the right side of the screen has a big gap.
![20220121141130_1](https://user-images.githubusercontent.com/60493629/150607068-546d84ad-7deb-4032-a148-30f901e0f66d.jpg)

**Comment by NewAlexGamer** [comment]
that's why i use exactly x0.78

**Comment by absoIute** [comment]
Intended behaviour, no other tabs can fit in that gap
