### ISSUE TITLE
New "Added" Label

### ISSUE THREAD

**Issue by Nicko2102** [absoIute/Mega-Hack-Pro-Future#389]
Maybe it would be nice to add an "added" label so we can see which features from this repo have been added and are in the program, so we don't have to scroll through the changelog or randomly discover them. I know the "Approved" tag exists, but currently there's no distinction between features that are being worked on and features that are completed and included in the program. the only issue i can see with this is having to add every old thing that has been added, but i think just adding completed ones going forward would be fine

**Comment by Brittank88** [comment]
Search string: `is:issue is:closed label:approved`

**Comment by Brittank88** [comment]
Let me know if you feel the label could still be beneficial - if you make a good case I'm happy to add it, otherwise it's an extra thing to remember to do that could be avoidable.

**Comment by Nicko2102** [comment]
> Search string: `is:issue is:closed label:approved`

ok that's fair, just that some of those haven't been added, and/or aren't actually hacks, but instead q/a stuff. But i do see your point.

**Comment by succmydecc** [comment]
it would still be benefical because, it just helps overall or pin this ig

**Comment by succmydecc** [comment]
britank88, there are closed issues/suggestions but not added. @Brittank88 this would be very useful also sorry for pinging you

**Comment by Nicko2102** [comment]
already mentioned that

**Comment by zohnannor** [comment]
> there are closed issues/suggestions but not added

that's why `label:approved` in there

**Comment by Nicko2102** [comment]
> that's why 'label:approved' is in there

Still, some of the approved and closed hacks were not added due to other factors

**Comment by zohnannor** [comment]
Then the repo owners should go through closed issues and fix broken labels if they want to, imo... Anyway, it's up to the repo owners' to decide.

**Comment by Brittank88** [comment]
> > that's why 'label:approved' is in there
> 
> Still, some of the approved and closed hacks were not added due to other factors

Which ones? I would like to fix this.

**Comment by Nicko2102** [comment]
#213, #286, and it would also help in differentiating between "ready for next update" and "in current update"

**Comment by Brittank88** [comment]
> it would also help in differentiating between "ready for next update" and "in current update"

I see where you're coming from, I'll have to try and find a clean solution to this given the volume of issues at this point...

**Comment by Brittank88** [comment]
> #213, #286

Hmm, it is a little confusing if they're closed and approved yet the features weren't actually added...unless they were? @absoIute would love your input on this.

**Comment by absoIute** [comment]
Can just add an 'upcoming' label for implemented suggestions for next update

**Comment by absoIute** [comment]
don't know why #213 was closed but #286 is implemented in the cosmetics tab!

**Comment by Brittank88** [comment]
> Can just add an 'upcoming' label for implemented suggestions for next update

In that case, what's the overall system? Is it...
"approved" | This is currently planned for implementation but hasn't actually been implemented yet.
"upcoming" | This is implemented for the next update.

**Comment by absoIute** [comment]
Yeah

**Comment by Brittank88** [comment]
> > Label	Meaning
> > approved	This is approved but hasn't actually been implemented yet.
> > upcoming	This is implemented for the next update.
> 
> then for features that are in the current update, would that be a separate label, or is that where the milestones thing comes in handy

I think it makes sense to have an implemented label, because if you just have it in the milestone, what do you do about the labels? Removing approved and/or upcoming is ambiguous.
