### ISSUE TITLE
Discord RPC Customization

### ISSUE THREAD

**Issue by Fl1pNatic** [absoIute/Mega-Hack-Pro-Future#39]
It would be really cool to customize your discord presence with MHv6. Something like changing these strings to something else would be enough.
![image](https://user-images.githubusercontent.com/41564630/116430891-11e22d80-a869-11eb-97ef-3a673d392238.png)

**Comment by Brittank88** [comment]
Isn't this RPC added by another DLL? I believe I have it installed myself, though I have RPC turned off right now (lol).

Not sure if MHv6 is able to easily modify the behaviour of another external DLL, though, I guess it could just replace the functionality.

Or maybe MHv6 comes with RPC and I literally just haven't noticed?

**Comment by Fl1pNatic** [comment]
> Isn't this RPC added by another DLL? I believe I have it installed myself, though I have RPC turned off right now (lol).
> 
> Not sure if MHv6 is able to easily modify the behaviour of another external DLL, though, I guess it could just replace the functionality.
> 
> Or maybe MHv6 comes with RPC and I literally just haven't noticed?

![image](https://user-images.githubusercontent.com/41564630/116776809-5f8ab000-aa8c-11eb-9151-de2513daa4b2.png)
yea it uses custom dll

**Comment by RootRobo** [comment]
> > Isn't this RPC added by another DLL? I believe I have it installed myself, though I have RPC turned off right now (lol).
> > 
> > Not sure if MHv6 is able to easily modify the behaviour of another external DLL, though, I guess it could just replace the functionality.
> > 
> > Or maybe MHv6 comes with RPC and I literally just haven't noticed?
> 
> ![image](https://user-images.githubusercontent.com/41564630/116776809-5f8ab000-aa8c-11eb-9151-de2513daa4b2.png)
> yea it uses custom dll

thats just Discord's API DLL fir the rich presence. If you want to customize MegaHack's RPC you should just disable it and use [this](https://github.com/kyurime/gdrpc) along with MegaHack.

**Comment by Brittank88** [comment]
Yeah, just place that in the GD directory and add the DLL name to the "absolutedlls" file.

Gonna mark this as invalid and close for now given that it's technically unrelated to MHv6.
