### ISSUE TITLE
Scientific Notation In Text Inputs & Text Length

### ISSUE THREAD

**Issue by succmydecc** [absoIute/Mega-Hack-Pro-Future#391]
For example if i set my attempt count to 9999999999 it will display 9.999999E+06, and I cant interact with it. Allow for decimal precision in text inputs and allow for text length to be infinite?

**Comment by Nicko2102** [comment]
i think that might have happened because the attempt count is an int not a float

**Comment by succmydecc** [comment]
smh do you even know what your talking about

**Comment by Nicko2102** [comment]
there was literally no reason for you to say that

**Comment by Nicko2102** [comment]
also...
![image](https://user-images.githubusercontent.com/83476899/150665470-11d28996-9d04-4c2f-9543-dcc15b79ac2f.png)

**Comment by succmydecc** [comment]
I wasn't attempting to be rude yk

**Comment by Nicko2102** [comment]
what was the point of saying that then

**Comment by zohnannor** [comment]
Duplicate of #322

**Comment by Nicko2102** [comment]
I knew i saw it somewhere and was looking for it, thanks

**Comment by succmydecc** [comment]
@zohnannor no, thats a issue about scentific notation, this is to allow scentific notations

**Comment by Nicko2102** [comment]
your original question is unclear, you reference scientific notation and decimal precision which are two very different things

**Comment by succmydecc** [comment]
Sorry, I meant decimal.

**Comment by Nicko2102** [comment]
np

**Comment by Brittank88** [comment]
I'm going to move this into #322 and suggest support for scientific notation numbers be implemented.

**Comment by Brittank88** [comment]
Duplicate of #322
