### ISSUE TITLE
Reordering Hack Menu Items

### ISSUE THREAD

**Issue by SadShikawa** [absoIute/Mega-Hack-Pro-Future#396]
So basically there would be a button to reorder the hacks in their categories. Might not be too hard to implement, and it is a cool enhancement / feature.

Tag as an enhancement, low priority

**Comment by Brittank88** [comment]
...in what order particularly? Or just free choice? You describe it as a single button so I'm not sure how that would translate to free reordering. Would you go into more detail on how you imagine this being implemented?

**Comment by Nicko2102** [comment]
first thing that came to mind as something like this (inspired by apple music's way of ordering), with an edit button in the top that makes the hacks draggable within the window, or makes them scrollable (scrolling up will move the hack being hovered over up one space)
![image](https://user-images.githubusercontent.com/83476899/150815737-92ba192d-ae09-4d9d-9461-ec34893fb462.png)

**Comment by absoIute** [comment]
Not something I plan on implementing due to limitations with the UI engine I'm afraid, using the Favourites tab should work for mods you want to be able to access quickly
