### ISSUE TITLE
Pause During Complete And Restarting The Level 

### ISSUE THREAD

**Issue by zohnannor** [absoIute/Mega-Hack-Pro-Future#398]
If you enable "Pause During Complete", complete a level, pause during animation and restart the level, the "Level Complete" screen shows up.

https://user-images.githubusercontent.com/35764628/150803464-eef9c0a9-2bcf-4826-bdf3-78d1184d9666.mp4

Possible fix: prevent user from restarting the level? (via in-game button or MH's shortcut) Or restart the level but keep it completed/verified.
Upd: MH's shortcut doesn't restart the level, only button does.

**Comment by NewAlexGamer** [comment]
#324

**Comment by Brittank88** [comment]
Duplicate of #324
