### ISSUE TITLE
Level Data Manipulator

### ISSUE THREAD

**Issue by succmydecc** [absoIute/Mega-Hack-Pro-Future#402]
Allow for level data (gd levels) to be manipulated directly. Not a CCLocalLevels decrypter, but a individual level decrypter.

**Comment by absoIute** [comment]
GDShare does this

**Comment by absoIute** [comment]
Wait no I can't read, but directly editing level strings is still something out-of-scope for Mega Hack

But you can still do: GDShare -> decrypt levels -> edit it

**Comment by succmydecc** [comment]
where is that option?

**Comment by Nicko2102** [comment]
Part of GDShare, not megahack

**Comment by succmydecc** [comment]
@Nicko2102 no i mean how to decrypt gd levels?

**Comment by Nicko2102** [comment]
level decryption is part of GDShare, which is a different mod. I've never used that aspect so i don't know

**Comment by succmydecc** [comment]
What? No
