### ISSUE TITLE
Opacity For Wave

### ISSUE THREAD

**Issue by succmydecc** [absoIute/Mega-Hack-Pro-Future#405]
1.) allow for custom opacity in RGB icons
2.) allow for brightness & HUD to be decreased

**Comment by Nicko2102** [comment]
wdym the HUD? that seems like a separate issue

**Comment by succmydecc** [comment]
@Nicko2102 well, https://www.youtube.com/watch?v=HJ5cKyKySnQ i want the RGB in this wave at the start. However mhv7 doesn't allow me to do that.

**Comment by Nicko2102** [comment]
![image](https://user-images.githubusercontent.com/83476899/151100288-9aed364d-221b-4402-b279-f861c83c2606.png)

**Comment by Nicko2102** [comment]
also that doesn't have anything to do with HUD

**Comment by succmydecc** [comment]
@Nicko2102 what about opacity.

**Comment by succmydecc** [comment]
Nvm, solid wave needs a exit and reenter.

**Comment by succmydecc** [comment]
Reopening as, and it may make me look like a idiot, but @Nicko2102 why does my icon invert on enabling icon effects?

**Comment by succmydecc** [comment]
Nvm.

**Comment by zohnannor** [comment]
Offtopic: please stop @mentioning everyone, the users participating in the issue are automatically subscribed to notifications about new comments/events.

**Comment by Nicko2102** [comment]
yes please. Also especially stop mentioning Brittank and Absolute
