### ISSUE TITLE
Layout Mode When HHL

### ISSUE THREAD

**Issue by succmydecc** [absoIute/Mega-Hack-Pro-Future#407]
layout mode when hhl? Add in options / subcategory

**Comment by Nicko2102** [comment]
what's HHL?

**Comment by absoIute** [comment]
HHL?

**Comment by succmydecc** [comment]
how do you not know what HHL means?

**Comment by absoIute** [comment]
bruh

**Comment by absoIute** [comment]
just answer the question

**Comment by succmydecc** [comment]
smh

**Comment by succmydecc** [comment]
HHL means

**Comment by succmydecc** [comment]
hit his line

**Comment by absoIute** [comment]
I still don't get what you mean then, could u elaborate?

**Comment by succmydecc** [comment]
https://youtu.be/ZaTGx5ubzH8?t=416

**Comment by succmydecc** [comment]
smh how do you not know

**Comment by absoIute** [comment]
what would the point of that be?

**Comment by succmydecc** [comment]
Memory demons.

**Comment by absoIute** [comment]
but show hitboxes just shows what you need to do anyway, so like what would the advantage be?

**Comment by succmydecc** [comment]
Well, for memory demons it would be flashy, so this is where it would be useful

**Comment by zohnannor** [comment]
> hit his line

HHL means "**H**ow **H**ard the **L**evel is" I belei and it's an abbreviation crated by Exen

**Comment by succmydecc** [comment]
🤦

**Comment by Brittank88** [comment]
This is just ridiculous. If you won't bother to properly explain what you're talking about from the beginning, why should we bother to service your issue?

We're not all-knowing beings. Stop being insufferable.

**Comment by absoIute** [comment]
^
also still don't really see a use in it, just seems like a gimmick
