### ISSUE TITLE
Editor zoom control on scroll wheel

### ISSUE THREAD

**Issue by Fl1pNatic** [absoIute/Mega-Hack-Pro-Future#41]
Can you add, so we can zoom and unzoom using scrolling wheel? It will be very useful.

**Comment by Brittank88** [comment]
I'm not sure if any of this already exists in the editor, but I believe it would be good to implement it like this:
- Scroll moves vertically
- Shift + scroll moves horizontally
- Ctrl + scroll zooms in / out

**Comment by Fl1pNatic** [comment]
> I'm not sure if any of this already exists in the editor, but I believe it would be good to implement it like this:
> 
> * Scroll moves vertically
> * Shift + scroll moves horizontally
> * Ctrl (or CMD for OSX I guess...) + scroll zooms in / out

That would be awesome

**Comment by absoIute** [comment]
available in https://github.com/HJfod/BetterEdit !
