### ISSUE TITLE
Extension Load Order Rework

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#412]
There are two main issues currently:

1. [ ] Changing the load order in-game is very clunky because you only have "Load First" and "Load Last". It should really be a system where you can move items up or down one position at a time.
2. [ ] You can only change the load order in-game. This means that two extensions that cause a crash when loaded in the wrong order will prevent you from just adding them both and fixing their load order. You currently have to add one, open the game, make it load first, and then close the game, and add the other. It's long-winded and could be easily avoided by allowing the load order to be configured outside of the game, or at least before the extension loading stage.

**Comment by Brittank88** [comment]
I've turned these two points into checkboxes so you can track the completion of this issue in terms of the two individual suggestions. 😄

**Comment by absoIute** [comment]
thanks :p will change that, not sure why I chose load first/last in the first place

**Comment by Brittank88** [comment]
Even cooler is if you let the menu items in the list be draggable, similar to [this behaviour](https://codepen.io/Defatul/pen/LYEjdzG).

**Comment by Nicko2102** [comment]
> [this behaviour](https://codepen.io/Defatul/pen/LYEjdzG).

~~who is charlie and why is he bravo~~
this could also be implemented in changing the order of the status labels from issue #400

**Comment by absoIute** [comment]
added ready for next update (might also move to that sortable list behaviour but we'll see)

**Comment by Nicko2102** [comment]
Jusn wondering, is there a way to get notified of a new update

**Comment by NewAlexGamer** [comment]
either twitter notifis for his messages are on or autoupdate should do its thing after a couple of minutes from release

**Comment by Brittank88** [comment]
> Jusn wondering, is there a way to get notified of a new update

There is an entry in #431 relating to this.
