### ISSUE TITLE
Don't Fade + Don't Enter/disable transition effects (Client Side)

### ISSUE THREAD

**Issue by Nicko2102** [absoIute/Mega-Hack-Pro-Future#413]
just an option that disables transition effects / makes everything look like it has don't fade don't enter. The thing is, the level isn't changed at all, like the triggers and stuff are still there, but when playing it looks as if the effects are off. Not entirely sure this is possible but it's worth a shot

**Comment by Nicko2102** [comment]
note: I made a really simple mod that sets everything in a level to don fade/dont enter (and no glow), so i know that can be done, but I'm not sure how to get the visual effect without changing the properties of the objects themselves

**Comment by absoIute** [comment]
Already exists in the cosmetic tab!

**Comment by Nicko2102** [comment]
lmao im so dumb, i already have one of them enabled and i didnt even notice, thanks
