### ISSUE TITLE
Change "No Force Glow" Label To "No Force Player Glow"

### ISSUE THREAD

**Issue by Nicko2102** [absoIute/Mega-Hack-Pro-Future#417]
It took me a while to realize this was even a feature, simply because how similar these two mods sound, and I think a simple label change could fix that.
![image](https://user-images.githubusercontent.com/83476899/151422842-f0f68098-17a5-40b4-bd6a-592ba379b33b.png)

**Comment by absoIute** [comment]
changed, ready for next update
