### ISSUE TITLE
quick apology

### ISSUE THREAD

**Issue by insufferablebeing** [absoIute/Mega-Hack-Pro-Future#418]
sorry for being pretty much insufferable. doesn't mean after this apology i am right. and yes, call me a liar for realizing my mistakes very early on. and @Brittank88 go add the invaild label idc

**Comment by Brittank88** [comment]
I'm sorry man, I kinda feel bad for this but truthfully you are just too disruptive. Between unrelated content, lying and talking about things as if they are facts, etc. it's just a nuisance. At the same time, it doesn't mean we have to hate you or anything, it's just that we don't think you're really.. compatible with this tracker I guess. It's just an extra hassle and you haven't been listening to us when we asked you to stop doing certain things.

**Comment by Brittank88** [comment]
Best of luck with whatever you do in future, but for now, goodbye.
