### ISSUE TITLE
Edit The Opacity Of The MHV7 Watermark

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#419]
This option could be available in the "Mega Hack Pro" tab.
![20220127185332_1](https://user-images.githubusercontent.com/60493629/151479182-31208d38-ea3f-4872-a810-272af40267dc.jpg)

**Comment by zohnannor** [comment]
Sorry but you already opened similar issue and the answer was "no":  https://github.com/absoIute/Mega-Hack-Pro-Future/issues/358#issuecomment-1011314668
Why would you need that? This is just a label in the corner that goes layer behind hack menu and does not interfere with it visually

**Comment by Nicko2102** [comment]
like zohannor said this is a duplicate, and a reason was already given for why it's there

**Comment by Brittank88** [comment]
Duplicate of #358
