### ISSUE TITLE
Options for "Auto Pickup Coins"

### ISSUE THREAD

**Issue by MainConMan** [absoIute/Mega-Hack-Pro-Future#420]
A drop-down on Auto Pickup Coins that would let you choose which coins it gives you. 

This could be useful if you beat a level on a copy or LDM, and collect only the 2nd and 3rd coins, you could use Instant Complete and Auto Pickup Coins without getting the 1st coin illegitimately.

**Comment by Nicko2102** [comment]
love this idea

**Comment by absoIute** [comment]
Added ready for next update!
