### ISSUE TITLE
Glowy Wave Trail

### ISSUE THREAD

**Issue by totallyphysicallypossible** [absoIute/Mega-Hack-Pro-Future#422]
completely dumb and useless but i thought it would be cool

and yeah this is pretty much stolen from temp's glowy wave
https://youtu.be/8Ag2LuzAgTg

and if this was already suggested before then I am incredibly sorry

**Comment by MainConMan** [comment]
This would look so cool with RGB wave trail! I hope this gets added!

**Comment by Nicko2102** [comment]
> completely dumb and useless but i thought it would be cool

It is "useless" gameplay-wise but then again so are half the hacks in mega hack, this is a really good cosmetic idea and i could see a lot of people using it

**Comment by absoIute** [comment]
Everything cosmetic is dumb, but they're still some of the most used hacks!

**Comment by Nicko2102** [comment]
> Everything cosmetic is dumb, but they're still some of the most used hacks!

exactly my point!

**Comment by Brittank88** [comment]
Glowy icon stuff in general would be super cool. Basically bloom effect (AKA any """RTX: ON""" video lmao).

**Comment by MainConMan** [comment]
That would also look cool on the spider dash imo.

**Comment by Nicko2102** [comment]
> In fact should this issue just be updated to suggest a general bloom effect applicable to levels, icons, etc?

I like this idea, and would just add that it might be a good idea to make them toggleable separately, such as having icon/wave trail bloom without level bloom or vice versa, i think you could get some cool visual effects from having "RTX: OFF" icons in an "RTX: ON" level

**Comment by Brittank88** [comment]
Agreed. I think I'll roll this into a new issue that has a checklist for each different aspect that could have bloom applied.

**Comment by Brittank88** [comment]
Rolled into #434!
