### ISSUE TITLE
(Meta) Issue Tracker Suggestions

### ISSUE THREAD

**Issue by zohnannor** [absoIute/Mega-Hack-Pro-Future#423]
1. Someone could compile a list of all the added features that were suggested by users on the tracker and put it in the readme so new users will see how community is helping MegaHack grow!
2. Similar to point 1: add a changelog listing additions/fixes for each new version, also there is Releases section on GitHub, it can be used to notify users of new update

What do you think?

**Comment by absoIute** [comment]
Will work on this!

**Comment by Nicko2102** [comment]
this seems like a better version of #389 , not saying its a duplicate though

**Comment by MainConMan** [comment]
> 1. Someone could compile a list of all the added features that were suggested by users on the tracker and put it in the readme so new users will see how community is helping MegaHack grow!

I went through all issues and made the list, with the usernames of who suggested it. Hope this helps :)

[MHv7 Added Suggestions.txt](https://github.com/absoIute/Mega-Hack-Pro-Future/files/7964481/MHv7.Added.Suggestions.txt)

**Comment by Brittank88** [comment]
> > 1. Someone could compile a list of all the added features that were suggested by users on the tracker and put it in the readme so new users will see how community is helping MegaHack grow!
> 
> I went through all issues and made the list, with the usernames of who suggested it. Hope this helps :)
> 
> [MHv7 Added Suggestions.txt](https://github.com/absoIute/Mega-Hack-Pro-Future/files/7964481/MHv7.Added.Suggestions.txt)

It's absolutely wonderful of you to compile this list for us, thank you <3

**Comment by Brittank88** [comment]
Rolled into #431!

**Comment by zohnannor** [comment]
> I went through all issues and made the list, with the usernames of who suggested it. Hope this helps :)

You absolute legend! Good job
