### ISSUE TITLE
Show Wave Trail After Death

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#424]

**Comment by absoIute** [comment]
What's would be the use of this?

**Comment by NewAlexGamer** [comment]
so when you die during a wave, you clearly cannot see where you've been to get there, you just see the icon itself where it died, if you have death explosions disabled. when the "stop every trigger after death" gets implemented, this can help to see what we did and in case we were way too close to death like the second before, we can now correct the timings so we don't die there in the future, because we now know about the death almost got into the face
also this applies especially in memory demons, where the only point of reference is the deco and no actual gameplay is show (in heavy memory based demons of course)
ye this actually took me a while to think of after i realized how hard it was to answer the question xD

**Comment by NewAlexGamer** [comment]
also this https://github.com/absoIute/Mega-Hack-Pro-Future/issues/422#issuecomment-1024595146 could also happen with this in case it gets implemented

**Comment by Nicko2102** [comment]
also, a few days ago I died at a wave part and couldnt tell if i clicked too early or let go too late, and this option would fix things like that

**Comment by Brittank88** [comment]
I agree that this is actually a cool idea. Combined with disabling the death effect, your wave icon and trail would kinda just freeze on the spot and allow you to see the exact position and _position 'history'_ of it.

**Comment by absoIute** [comment]
Added ready for next update
