### ISSUE TITLE
LDM Editor Entrance

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#425]
Maybe there could be feature of where you can enter the level in the editor with LDM on. This could be useful to enter levels with very high and dense object counts.

**Comment by Nicko2102** [comment]
i like this idea, i think maybe if you turn on LDM in the menu, it should automatically go to ldm in the editor (with the option turned on ofc)

**Comment by zohnannor** [comment]
Possibly #206 dup

**Comment by Nicko2102** [comment]
> Possibly #206 dup

I think this is quite different, Layout mode and LDM aren't really the same thing

**Comment by Brittank88** [comment]
This is INCREDIBLY useful for testing in-level LDM systems, however, it already exists as a BetterEdit feature (`View -> LDM` in the editor).

So for now, I'll close this as it duplicates an existing feature offered by a mainstream extension.

**Comment by BrownieGamingX5** [comment]
But, I want this integrated into a separate feature in Mega Hack. BetterEdit is extremely buggy, and it is very annoying. There has been random crashes from BetterEdit.

**Comment by Brittank88** [comment]
There is something to be said about avoiding feature overlap, plus, MH is less of a creation tool and this feels like it lies a little out of the scope.

If it's buggy, issues related to that should go to HjFod so they can be fixed. I've personally never experienced any crashes. You should be careful that it's not related to any other extensions you may have installed, or the load order of said extensions.
