### ISSUE TITLE
Random Editor Tab Bug

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#426]
The "tab" is right next to the custom objects tab for the people who don't know this. I feel like it has something to do with Mega Hack or something like that. None of the extensions I have don't make this happen by the way.
![20220128180249_1](https://user-images.githubusercontent.com/60493629/151643079-a1355bad-b664-40b8-857f-bb698f222b4e.jpg)

**Comment by Nicko2102** [comment]
Duplicate of #383, fix is apparently already lined up for next update :)

**Comment by Brittank88** [comment]
Duplicate of #383
