### ISSUE TITLE
Smarter Best Run (Accounting For New Startpos)

### ISSUE THREAD

**Issue by Nicko2102** [absoIute/Mega-Hack-Pro-Future#428]
Let's say you get a really good run, and you want to start playing from a new startpos. the best run tracker wont record any of your runs from that point unless you get really far. I think there should be a way to reset the best run counter without having exit out of the level.

**Comment by MainConMan** [comment]
Great idea, would help me a lot!

**Comment by Brittank88** [comment]
Alternative solution: Multiple best runs are listed, grouped by the startpos they started from.

**Comment by Nicko2102** [comment]
Yes this is so good, thank you

**Comment by absoIute** [comment]
Listing them all might get too long but I will probably change it so it only shows the best run from the startpos you're using

**Comment by Nicko2102** [comment]
even better

**Comment by Nicko2102** [comment]
just adding, can there still be a way to reset it (just for the startpos you're on, not for all of them)?

**Comment by absoIute** [comment]
ready for next update, including a reset button (within Best Run options)

**Comment by Nicko2102** [comment]
Let's go thank you!
