### ISSUE TITLE
Megahack v6 beta5 crashing frequently

### ISSUE THREAD

**Issue by Amber-a2cc** [absoIute/Mega-Hack-Pro-Future#43]
After getting the auto update for megahack v6 beta5, in the editor my game has been quite frequently crashing for seemingly no reason. My best guess is maybe a conflict with betteredit with some of the features overlapping, but I'm still not sure.

**Comment by absoIute** [comment]
could you go to Event Viewer -> Windows Logs -> Application after a crash & send me the last Error by GD?

**Comment by Amber-a2cc** [comment]
> 
> 
> could you go to Event Viewer -> Windows Logs -> Application after a crash & send me the last Error by GD?

Fault bucket 1481022409116384680, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: GeometryDash.exe
P2: 0.0.0.0
P3: 5a13638c
P4: libcocos2d.dll
P5: 0.0.0.0
P6: 5a1360bc
P7: c0000005
P8: 0009fc98
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2032.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER20EF.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER20FF.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER20FF.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2120.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_GeometryDash.exe_ca9bab4df89faafc09cb7758a38fa14e64ac947_59ed2ec6_916f2596-5311-4b18-8975-9729e63b7f40

Analysis symbol: 
Rechecking for solution: 0
Report Id: e5e64baf-8f62-4ce1-9687-0c2d1dcc2d38
Report Status: 268435456
Hashed bucket: c970b02eb17824f8848da608c7c67da8
Cab Guid: 0

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-07-30T21:27:02.1298726Z" /> 
  <EventRecordID>1853683</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>LAPTOP-DEQ6HTS3</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>1481022409116384680</Data> 
  <Data>1</Data> 
  <Data>APPCRASH</Data> 
  <Data>Not available</Data> 
  <Data>0</Data> 
  <Data>GeometryDash.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5a13638c</Data> 
  <Data>libcocos2d.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5a1360bc</Data> 
  <Data>c0000005</Data> 
  <Data>0009fc98</Data> 
  <Data /> 
  <Data /> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2032.tmp.dmp \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER20EF.tmp.WERInternalMetadata.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER20FF.tmp.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER20FF.tmp.csv \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2120.tmp.txt</Data> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_GeometryDash.exe_ca9bab4df89faafc09cb7758a38fa14e64ac947_59ed2ec6_916f2596-5311-4b18-8975-9729e63b7f40</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>e5e64baf-8f62-4ce1-9687-0c2d1dcc2d38</Data> 
  <Data>268435456</Data> 
  <Data>c970b02eb17824f8848da608c7c67da8</Data> 
  <Data>0</Data> 
  </EventData>
  </Event>
  
Here's everything it showed in the event viewer, for now I've reverted to the non-beta version because the crashing was making it very hard to build in. I don't know if this specific crash is even related to beta5 cuz I just searched "Geometry" into the event viewer

**Comment by absoIute** [comment]
cheers

**Comment by absoIute** [comment]
fixed in 6.3.0-GM1
