### ISSUE TITLE
Random Game Freezing (Audio Unaffected)

### ISSUE THREAD

**Issue by CoolDawg08** [absoIute/Mega-Hack-Pro-Future#44]
I don't know if it's only me that has this, but whenever I use Mega Hack v6 of any sort, (beta or not) my game will randomly freeze from time to time but the music still plays, and when it unfreezes, I immediately die if I'm in a level, this never happened when I had Mega Hack v5, and I know it's not due to my currently activated hacks because I tested it out with zero hacks and it still freezes. If you can fix this bug, that would be greatly appreciated.

**Comment by absoIute** [comment]
NVIDIA Control Panel -> 3D Program Settings -> Geometry Dash -> Disable Threaded Optimisation seems to fix it for most people, if not next update should have this fully resolved.
