### ISSUE TITLE
Better sorting for status text

### ISSUE THREAD

**Issue by Underkirby** [absoIute/Mega-Hack-Pro-Future#441]
Idk why but I would kinda like the status text to be ordered from widest to thinnest like a Minecraft Hacked client would, it just looks nicer :D

![2022 Jan 31 16-32-37 1](https://user-images.githubusercontent.com/95105680/151744677-7555ccbb-ffda-41a2-a31a-27418175698f.png)

**Comment by Nicko2102** [comment]
duplicate of #400

**Comment by Brittank88** [comment]
Duplicate of #400

**Comment by Brittank88** [comment]
However, I will note within #400 that live sorting by total line length would be cool.

**Comment by Nicko2102** [comment]
> However, I will note within #400 that live sorting by total line length would be cool.

good point, because it can change over time

**Comment by Brittank88** [comment]
> for example, if your cps thing is almost the same length as something else, then any time you get to 1 cps or off it it would flip the order, which could be very distracting.

Quite true. There's probably ways to minimise this though, like a 'cooldown' on flipping the same two lines.

Either way, it's one option of a few, and could be disabled in favour of a different method.

**Comment by Underkirby** [comment]
Yeah, that makes sense. It could be very distracting.

**Comment by absoIute** [comment]
It might be better to just stick to the manual reordering then instead, so everything's just where it's expected
