### ISSUE TITLE
Hitbox Trail: Draw Skipped?

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#442]
As you can see here, one 'frame' of the trail is missing:

![image](https://user-images.githubusercontent.com/24266948/151770578-e6e9c221-049c-4577-a8bd-b77bfe8a1dad.png)

This is a miniscule bug but I figured I may as well record it whilst the stars have aligned for it to happen to me.

**Comment by MainConMan** [comment]
This sometimes happens to me when my FPS drops, maybe that is the cause of the bug. I'm not 100% sure though.

**Comment by absoIute** [comment]
Happens when a lag spike occurs, cocos will adjust the next frame's delta so the player takes a bigger step next frame, not much to be done about this

Smooth Fix / Force Smooth Fix can reduce the times this happens

**Comment by Brittank88** [comment]
> Happens when a lag spike occurs, cocos will adjust the next frame's delta so the player takes a bigger step next frame, not much to be done about this
> 
> Smooth Fix / Force Smooth Fix can reduce the times this happens

Ohhh tysm for the explanation!
