### ISSUE TITLE
Disable/Re-Enable All Hacks Option

### ISSUE THREAD

**Issue by Nicko2102** [absoIute/Mega-Hack-Pro-Future#444]
This would just be a button (keybindable) that toggles off all the hacks. However, instead of actually "turning them off", i think it could "grey them out", meaning you can still see which hacks are enabled (and you can toggle them on and off), but they don't actually do anything. The main thing is that when this option is toggled off, the hacks that you had enabled before will be enabled, along with any changes that were made while the option was on.

For Example: 
Start - Noclip is on
Disable option enabled - Noclip shows as on/greyed out but still on, does nothing
Speedhack enabled - also shows as on/greyed out, but does nothing
Disable option disabled - Noclip and Speedhack are now on and active

**Comment by MainConMan** [comment]
I really like this idea! I'll finally be able to prove to my friends that I can infact beat stereo madness without any cosmetic hacks!

**Comment by Brittank88** [comment]
> I really like this idea! I'll finally be able to prove to my friends that I can infact beat stereo madness without any cosmetic hacks!

<img alt="He clearly has many years of experience. An expert move." src="https://c.tenor.com/UDg2giQFms8AAAAM/cat.gif" />

**Comment by Nicko2102** [comment]
> > I really like this idea! I'll finally be able to prove to my friends that I can infact beat stereo madness without any cosmetic hacks!
> 
> ![He clearly has many years of experience. An expert move.](https://camo.githubusercontent.com/726948b9ed1e99dcfde2d4ddb4da0e432d50b7340ae573280e56310df1c84791/68747470733a2f2f632e74656e6f722e636f6d2f55446732676951466d7338414141414d2f6361742e676966)

![image](https://user-images.githubusercontent.com/83476899/152210326-d423bada-136e-4e17-8b03-802c8abb912f.png)

**Comment by MainConMan** [comment]
> > > I really like this idea! I'll finally be able to prove to my friends that I can infact beat stereo madness without any cosmetic hacks!
> > 
> > ![He clearly has many years of experience. An expert move.](https://camo.githubusercontent.com/726948b9ed1e99dcfde2d4ddb4da0e432d50b7340ae573280e56310df1c84791/68747470733a2f2f632e74656e6f722e636f6d2f55446732676951466d7338414141414d2f6361742e676966)
> 
> ![image](https://user-images.githubusercontent.com/83476899/152210326-d423bada-136e-4e17-8b03-802c8abb912f.png)
> 

I'm saving that one lol

**Comment by Nicko2102** [comment]
> > > > I really like this idea! I'll finally be able to prove to my friends that I can infact beat stereo madness without any cosmetic hacks!
> > > 
> > > 
> > > ![He clearly has many years of experience. An expert move.](https://camo.githubusercontent.com/726948b9ed1e99dcfde2d4ddb4da0e432d50b7340ae573280e56310df1c84791/68747470733a2f2f632e74656e6f722e636f6d2f55446732676951466d7338414141414d2f6361742e676966)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/83476899/152210326-d423bada-136e-4e17-8b03-802c8abb912f.png)
> 
> I'm saving that one lol

the irony. stealing my meme about stealing memes. how the turntables...

**Comment by Brittank88** [comment]
> > > > > I really like this idea! I'll finally be able to prove to my friends that I can infact beat stereo madness without any cosmetic hacks!
> > > > 
> > > > 
> > > > ![He clearly has many years of experience. An expert move.](https://camo.githubusercontent.com/726948b9ed1e99dcfde2d4ddb4da0e432d50b7340ae573280e56310df1c84791/68747470733a2f2f632e74656e6f722e636f6d2f55446732676951466d7338414141414d2f6361742e676966)
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/83476899/152210326-d423bada-136e-4e17-8b03-802c8abb912f.png)
> > 
> > 
> > I'm saving that one lol
> 
> the irony. stealing my meme about stealing memes. how the turntables...

https://user-images.githubusercontent.com/24266948/152264160-aec60308-9a4f-405a-9b3c-e766024c8c42.mp4

**Comment by Nicko2102** [comment]
> > > > > > I really like this idea! I'll finally be able to prove to my friends that I can infact beat stereo madness without any cosmetic hacks!
> > > > > 
> > > > > 
> > > > > ![He clearly has many years of experience. An expert move.](https://camo.githubusercontent.com/726948b9ed1e99dcfde2d4ddb4da0e432d50b7340ae573280e56310df1c84791/68747470733a2f2f632e74656e6f722e636f6d2f55446732676951466d7338414141414d2f6361742e676966)
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/83476899/152210326-d423bada-136e-4e17-8b03-802c8abb912f.png)
> > > 
> > > 
> > > I'm saving that one lol
> > 
> > 
> > the irony. stealing my meme about stealing memes. how the turntables...
> 
>  Letrak.mp4

"hey girl, are you uuhhhh..." *starts beatboxing the leyak song*

**Comment by absoIute** [comment]
Will be possible when #443 is implemented, though there won't be a dedicated feature for it!
