### ISSUE TITLE
Automatically Search Hacks/Modules

### ISSUE THREAD

**Issue by ImmensityHQ** [absoIute/Mega-Hack-Pro-Future#450]
EDIT: Automatically select search when typing while the hack menu is open, similar to Minecraft hack clients.

**Comment by MainConMan** [comment]
That's a thing in the very top of the "Mega Hack Pro" tab!

**Comment by Brittank88** [comment]
MainConMan is right - this exists! I get if it's a bit hard to see amongst all the menus though.

**Comment by Brittank88** [comment]
Actually... _modules_, not _individual hacks_...

That's an interesting thought. I'll reopen.

**Comment by Brittank88** [comment]
I assume what you mean @ImmensityHQ is that you can search for entire modules to find the right one?

Like if I did `m:Player` it would darken every module window except the Player module's window?

**Comment by absoIute** [comment]
Why would you need that though 🤔 they're big and obvious

**Comment by MainConMan** [comment]
> Actually... _modules_, not _individual hacks_...

Oops, I thought they meant hacks. So sorry about that.

**Comment by Brittank88** [comment]
> Why would you need that though 🤔 they're big and obvious

This is true but it might be helpful if more modules are introduced (we know at least the macro module will exist at some point, plus you get even more module windows if you have certain extensions).

**Comment by absoIute** [comment]
True would definitely help with extensions, I could probably add an option to auto-select the search box on TAB so you can instantly just start finding your hacks too

**Comment by ImmensityHQ** [comment]
Maybe a better title would've been something like "Automatically search hacks/modules". I know the functionality already exists, but if you could automatically start searching when you start to type (see almost any Minecraft hacked client as an example), that would be much easier.

**Comment by ImmensityHQ** [comment]
Actually it seems like Brittank88 already mentioned this in #463

**Comment by Brittank88** [comment]
@All-Contributors please add @ImmensityHQ for bug, ideas, maintenance.

**Comment by Brittank88** [comment]
@ImmensityHQ Keep up the good work in making sure issues aren't duplicate:



> Actually it seems like Brittank88 already mentioned auto-selecting the search bar in #463

As well as recommending how things could be described better:



> Maybe a better title would've been something like "Automatically search hacks/modules". I know the functionality already exists, but if you could automatically start searching when you start to type (see almost any Minecraft hacked client as an example), that would be much easier.

I appreciate it! 😄

**Comment by ImmensityHQ** [comment]
Thank you! Glad I could help ;D

**Comment by MainConMan** [comment]
This should be closed and labeled upcoming. :)

https://twitter.com/absolllute/status/1489656097745129474?s=20&t=G4PKqanv2q1wRzOiqypZ9Q
