### ISSUE TITLE
Adding Contributors

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#453]
This is where I'll perform my testing whilst I get All-Contributors to work correctly.

Need to add the following people:

- [x] Absolute
- [x] Brittank88 (me!!!)
- [x] MainConMan
- [x] Nicko2102
- [x] Zohnannor

**Comment by Brittank88** [comment]
@All-Contributors please add @absoIute for bug, business, code, content, doc, design, financial, fundingFinding, ideas, infra, maintenance, projectManagement, question and security.

**Comment by Brittank88** [comment]
It keeps making PRs where it doesn't even add to the file...

**Comment by zohnannor** [comment]
> It keeps making PRs where it doesn't even add to the file...

Hm. Just before you closed it's PR, a new repo branch appeared that had changes to `.all-contributorsrc` file. I wonder why merging the PRs #451 & #454 didn't update the file despite it having the changes🤔

**Comment by Brittank88** [comment]
> > It keeps making PRs where it doesn't even add to the file...
> 
> Hm. Just before you closed it's PR, a new repo branch appeared that had changes to `.all-contributorsrc` file. I wonder why merging the PRs #451 & #452 didn't update the file despite it having the changes🤔

It has to create a new branch in order to request a PR between that branch and main. It's just the standard process - it adds contributor entries to `.all-contributorssrc` each time, like an internal listing.

**Comment by Brittank88** [comment]
@All-Contributors please add @absoIute for bug, business, code, content, doc, design, financial, fundingFinding, ideas, infra, maintenance, projectManagement, question and security.

**Comment by Brittank88** [comment]
..So it needs to exist but when it exists it doesn't even add anything. Okay then...

I'll try creating the file with some existing structure there for it to update?

**Comment by Brittank88** [comment]
@All-Contributors please add @Brittank88 for bug, content, doc, ideas, maintenance, mentoring, projectManagement and question.

**Comment by Brittank88** [comment]
Okay I've got it now!!!

**Comment by Brittank88** [comment]
@All-Contributors please add @absoIute for bug, business, code, content, doc, design, financial, fundingFinding, ideas, infra, maintenance, projectManagement, question and security.

**Comment by Brittank88** [comment]
@All-Contributors please add @Brittank88 for bug, content, doc, ideas, maintenance, mentoring, projectManagement and question.

**Comment by Brittank88** [comment]
@All-Contributors please add @absoIute for review

**Comment by Brittank88** [comment]
@all-contributors please add @Brittank88 for review

**Comment by Brittank88** [comment]
Okay so finally at least us two should be sorted.

**Comment by Brittank88** [comment]
@all-contributors please add @zohnannor, @Nicko2102, @MainConMan for bug, ideas, maintenance, question.

**Comment by Brittank88** [comment]
Darn, was hoping that would work.

**Comment by Brittank88** [comment]
@all-contributors please add @zohnannor and @Nicko2102 and @MainConMan for bug, ideas, maintenance and question.

**Comment by Brittank88** [comment]
Don't worry about the other two I guess LMAO

**Comment by Brittank88** [comment]
@all-contributors please add @Nicko2102 for bug, ideas, maintenance and question.
@all-contributors please add @MainConMan for bug, ideas, maintenance and question.

**Comment by Brittank88** [comment]
@all-contributors please add @Nicko2102 for bug, ideas, maintenance and question.

**Comment by Brittank88** [comment]
@all-contributors please add @MainConMan for bug, ideas, maintenance and question.

**Comment by zohnannor** [comment]
> Don't worry about the other two I guess LMAO

"The bot will use basic Natural Language Parsing to determine your intent.", they say😄

**Comment by Brittank88** [comment]
> > Don't worry about the other two I guess LMAO
> 
> "The bot will use basic Natural Language Parsing to determine your intent.", they say😄

To be fair, they're working on it: https://github.com/all-contributors/app/pull/127
