### ISSUE TITLE
Dual Sync Bug

### ISSUE THREAD

**Issue by ElMintus** [absoIute/Mega-Hack-Pro-Future#46]
When you are Playtesting/Practicing a level, the dual gamemode starts going out of sync, if this could be patched, it would be very helpful

**Comment by Brittank88** [comment]
Could you describe how it becomes out of sync? I'm not sure I fully understand what that means. Do they have different X positions? Does it make the level come out of sync with the music?

**Comment by absoIute** [comment]
While the bug is definitely there changing the physics like this could break certain levels so isn't something I'd want to do
