### ISSUE TITLE
Editor Hitbox Rotation Fix

### ISSUE THREAD

**Issue by Nicko2102** [absoIute/Mega-Hack-Pro-Future#466]
In vanilla GD, any rotated object will leave its hitbox unchanged (unless it is rotated to a multiple of 90º). Not sure if it's possible, but if there's a way to implement a fix for this that would be super helpful :D

**Comment by zohnannor** [comment]
There already is a hack that allows you to rotate any object, however, it's just local change: once you upload the level and users download it they will have objects like normal, bc game doesn't store that rotation anywhere.

**Comment by NewAlexGamer** [comment]
If I got what you're saying, absolute fixed the hitboxes not rotating in the editor. He only said that in a Twitter post tho, and maybe other discord servers I'm not in

**Comment by Brittank88** [comment]
This would absolutely be suited for BetterEdit rather than this. It's a shame though that it seems BE updates are on hold right now, and I have no idea when HJFod is going to resume them.

**Comment by Brittank88** [comment]
> If I got what you're saying, absolute fixed the hitboxes not rotating in the editor, it should be implemented for the next update. He only said that in a Twitter post tho, and maybe other discord servers I'm not in

Can someone confirm this by linking that post?

**Comment by MainConMan** [comment]
> > If I got what you're saying, absolute fixed the hitboxes not rotating in the editor, it should be implemented for the next update. He only said that in a Twitter post tho, and maybe other discord servers I'm not in
> 
> Can someone confirm this by linking that post?

https://twitter.com/absolllute/status/1481401377842778116?s=20&t=7hET1agzxHE0VlTTGHX3hw

**Comment by Brittank88** [comment]
> > > If I got what you're saying, absolute fixed the hitboxes not rotating in the editor, it should be implemented for the next update. He only said that in a Twitter post tho, and maybe other discord servers I'm not in
> > 
> > 
> > Can someone confirm this by linking that post?
> 
> https://twitter.com/absolllute/status/1481401377842778116?s=20&t=7hET1agzxHE0VlTTGHX3hw

In that case I'll apply the appropriate labels and close.

**Comment by Nicko2102** [comment]
> > > > If I got what you're saying, absolute fixed the hitboxes not rotating in the editor, it should be implemented for the next update. He only said that in a Twitter post tho, and maybe other discord servers I'm not in
> > > 
> > > 
> > > Can someone confirm this by linking that post?
> > 
> > 
> > https://twitter.com/absolllute/status/1481401377842778116?s=20&t=7hET1agzxHE0VlTTGHX3hw
> 
> In that case I'll apply the appropriate labels and close.

oh i didn't know that, thanks guys!
