### ISSUE TITLE
Can't Open GD w/ v6.3/7

### ISSUE THREAD

**Issue by youngchongos** [absoIute/Mega-Hack-Pro-Future#467]
It literally will load, then crash when the progress bar fills.

It usually says it's an access code violation from the hackpro dll. can you help me

**Comment by Brittank88** [comment]
> It literally will load, then crash when the progress bar fills.
> 
> It usually says it's an access code violation from the hackpro dll. can you help me

When I experienced this it was because of a conflict between two extensions. Do you have any installed extensions? If so, please try without them first.

If that works, I'm still happy to try to give you a hand - sometimes it is resolvable.

**Comment by Nicko2102** [comment]
also, there should be a file called "absolutedlls" in your geometry dash folder and it should contain one line of text that reads "hackpro.dll". if this isn't the case, then that might be the issue

**Comment by MainConMan** [comment]
> also, there should be a file called "absolutedlls" in your geometry dash folder and it should contain one line of text that reads "hackpro.dll". if this isn't the case, then that might be the issue
> 

Only in v6 though, not v7.

**Comment by absoIute** [comment]
Send a crashlog if any are generated in your GD folder!

**Comment by youngchongos** [comment]
there's no crashlogs. v6.3 says the hackpro.dll is a violation and the v7 doesn't have a valid crashlog, but likely for the same reason

**Comment by youngchongos** [comment]
no extensions are loaded, and ive reinstalled the game multiple times (ive even moved all my songs to a backup folder and deleted all my levels and completely wiped all the gd saves)

here's a .zip containing every dll in my game folder

**Comment by youngchongos** [comment]
but ill send a screenshot of my dlls first

**Comment by youngchongos** [comment]
![image](https://user-images.githubusercontent.com/98948316/152577837-65a96ec5-912e-4454-886d-dd43bed47961.png)

**Comment by absoIute** [comment]
core.json needs to be in the /data/ folder

**Comment by youngchongos** [comment]
i fixed it by reinstalling the entire os and upgrading to windows 11

no, i did the os upgrade for other reasons (because i like the aesthetic better)

**Comment by absoIute** [comment]
most likely was just an antivirus issue then
