### ISSUE TITLE
Hitbox Module Failure // Hitbox Toggle Crash

### ISSUE THREAD

**Issue by pesetz** [absoIute/Mega-Hack-Pro-Future#47]
The Show Hitboxes module doesn't work in 6.3.0-beta5. Also, upon disabling it while in a level the game crashes.

https://youtu.be/f24GR9VTDvs

**Comment by absoIute** [comment]
What extensions do you have?

**Comment by pesetz** [comment]
none

**Comment by pesetz** [comment]
also it hasn't happened since so i guess this can be closed

**Comment by Brittank88** [comment]
Feel free to reopen if you start experiencing this again!
