### ISSUE TITLE
Move Trigger/Start Pos Clash

### ISSUE THREAD

**Issue by ImmensityHQ** [absoIute/Mega-Hack-Pro-Future#471]
That one bug in GD where if you have a move trigger and a start position on the same x position, the move trigger is activated twice.

Thanks [Twitter person](https://twitter.com/Biz_z_/status/1489666145875636229).

**Comment by MainConMan** [comment]
Duplicate of #469

**Comment by ImmensityHQ** [comment]
just noticed that, thanks

**Comment by Brittank88** [comment]
Duplicate of #469
