### ISSUE TITLE
Automatically Input Recording Keybind

### ISSUE THREAD

**Issue by ImmensityHQ** [absoIute/Mega-Hack-Pro-Future#472]
When a level is finished or beaten in one attempt in practice/noclip accuracy/new best run, the Geforce Experience instant replay keybind (or whatever keybind the user decides) is automatically inputted.

EDIT: not a bug, it's a feature suggestion

**Comment by Nicko2102** [comment]
What key do you have set to the replay?

**Comment by ImmensityHQ** [comment]
For me at least, Alt-Shift-F10 which is the default Geforce Experience instant replay capture keybind.

**Comment by Nicko2102** [comment]
and i'm guessing that same keybind isn't set to any of your hacks.... have you tried it with mega hack disabled? or tested without extensions?

**Comment by ImmensityHQ** [comment]
Oh no this isn't a bug, It's a feature suggestion. I probably should phrase it differently in the future lol

**Comment by Nicko2102** [comment]
OOOOHHHHHHH that makes wayy more sense lmao

**Comment by absoIute** [comment]
Auto-Deafen could be used for this by setting deafen to 99/100%, I'm looking a few other things that could achieve this too but no plans for another dedicated keybind pressing mod

**Comment by Nicko2102** [comment]
Why not change auto-deafen to auto-keybind with multiple options? and users can put whatever key(s) they want in there, so they can use it for multiple things at once, such as deafening, capturing, or even turning on/off hacks for specific sections of a level?

**Comment by Brittank88** [comment]
> Why not change auto-deafen to auto-keybind with multiple options? and users can put whatever key(s) they want in there, so they can use it for multiple things at once, such as deafening, capturing, or even turning on/off hacks for specific sections of a level?

I like this a lot, I feel this could be very useful. It pairs well with #549.
