### ISSUE TITLE
Restart From Last Checkpoint Breaks at the End of a Level

### ISSUE THREAD

**Issue by ImmensityHQ** [absoIute/Mega-Hack-Pro-Future#477]
Restarting from last checkpoint with a checkpoint very close to the end of the level prevents you from beating the level.

**Comment by Nicko2102** [comment]
My guy you're going off with the issues lmao

**Comment by ImmensityHQ** [comment]
Sometimes I sit in bed and do nothing but think for hours. Last night was one of those nights lol (this issue isn't related to that however, I just happened to find this today)

**Comment by Nicko2102** [comment]
lmao that's fair, a lot of times i think of things even during the day then i forget what they are during the 20 second walk to my computer

**Comment by absoIute** [comment]
Bug was already fixed with v7!

**Comment by Brittank88** [comment]
@All-Contributors add @ImmensityHQ for bug, ideas.

**Comment by Brittank88** [comment]
Oh, LOL
