### ISSUE TITLE
Editor death effect?

### ISSUE THREAD

**Issue by Nicko2102** [absoIute/Mega-Hack-Pro-Future#481]
Not sure if or why this would be useful, mainly wondering if it's even possible because i think it could be cool/funny

**Comment by absoIute** [comment]
It'd probably just require you to setup the particle systems & then call the death effect code, but isn't really something I'd be interested in sorry

**Comment by Nicko2102** [comment]
no worries

**Comment by Brittank88** [comment]
@absoIute There is actually a proper use-case for this, potentially. When you die, that big fat red X covers the entire area where you die and you can't see anything (it's annoying af for playtesting and the like).

Replacing that with your death effect that just plays out and disappears would be a much cleaner option imo.

**Comment by absoIute** [comment]
Can just add a simpler option to disable the big red X!
