### ISSUE TITLE
Finite Control of "Copy Values" / "Paste Values"

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#5]
Individual types of information for an editor object should be able to be blacklisted / whitelisted when using "copy values" or "paste values".

This 'filter' would allow for toggling of:

- [ ] Groups
- [ ] Colours
    - [ ] Primary Colour
    - [ ] Secondary Colour
- [ ] Rotation
- [ ] Scale (please remember to support negatives lol)
- [ ] Rotation speeds for rotating objects (including orbs, which can have their rotation speed changed!)
- [ ] Z-layer
- [ ] Editor layer (and secondary editor layer)

**Comment by Brittank88** [comment]
**Note from Absolute:**
An entirely different copy-paste system is used for copying values, hence this will not be as trivial to implement as previously imagined.

**Comment by absoIute** [comment]
Would be quite tedious to implement due to the way the copy-value system works so will probably not add, may add to Creator Hacks if enough people want the feature though.
