### ISSUE TITLE
FPS Bypass Failure (Despite Vsync Disabled)

### ISSUE THREAD

**Issue by Royaltycorza** [absoIute/Mega-Hack-Pro-Future#50]
FPS bypass is not applying in-game. Even with v-sync off, the bypass locks at 61fps or lower.

**Comment by Brittank88** [comment]
Have you checked the appropriate control panel for your graphics card? You may also need to disable Vsync there.

**Comment by absoIute** [comment]
This happens due to conflicting programs or the above mentioned control panel settings, the FPS Bypass works fine when not handicapped
