### ISSUE TITLE
Solid Colour Failure [Beta]

### ISSUE THREAD

**Issue by NEM3S** [absoIute/Mega-Hack-Pro-Future#53]
With Mega Hack V6.2 PRO, the option Solid Colour worked very well but when I updated it to Mega Hack V6.3.0 (BETA 4)
The Colour 1 doesn't sync with the Colour 2 same for the Main Glow and Main Wave

this bug can be fix?  Thank you for your consideration.

**Comment by absoIute** [comment]
fixed since beta5
