### ISSUE TITLE
"Sort Windows" Bug 

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#550]
Sometimes clicking the "Sort Windows" in the "Mega Hack Pro" tab sometimes shuffles the tabs in a completely different orientation than before. It is hard to really explain this because it is pretty rare.

**Comment by absoIute** [comment]
Happens when windows have the same amount of elements, so whichever window was in-focus last takes priority, will fix

**Comment by absoIute** [comment]
Fix ready for next update
