### ISSUE TITLE
The Label Opacity Doesn't Work With The "Message" Label

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#561]
![20220208161927_1](https://user-images.githubusercontent.com/60493629/153098009-8331cf52-32cd-447e-b2e9-ce301c3de427.jpg)

**Comment by absoIute** [comment]
Intended behaviour as requested by the Demon List

**Comment by absoIute** [comment]
Intended behaviour

**Comment by Nicko2102** [comment]
could a separate opacity control be added? also why was it intended like that in the first place?

**Comment by absoIute** [comment]
change was made on the request of the Demon List so it's not trivial to fake the FPS counter

**Comment by Nicko2102** [comment]
ohh good reason that's smart
