### ISSUE TITLE
Is allowed to use mega-hack account with friend or friends?

### ISSUE THREAD

**Issue by cub-has-injected** [absoIute/Mega-Hack-Pro-Future#562]
Just a question.

**Comment by Nicko2102** [comment]
Do you mean mega hack account sharing?

**Comment by cub-has-injected** [comment]
Yeah

чт, 10 февр. 2022 г., 09:19 Nicko2102 ***@***.***>:

**Comment by absoIute** [comment]
Not allowed as per the agreement 3.1 of the EULA https://absolllute.com/store/mega_hack_eula
