### ISSUE TITLE
Don't steal GDHM mods?

### ISSUE THREAD

**Issue by defaultacc30** [absoIute/Mega-Hack-Pro-Future#568]
GDHM has a lot of customization features that make it good, however I see a lot of people on this repo stealing those ideas and submitting to mhv7. In the GDHM discord server, adaf limited mods to mods that weren't in mhv7. So please do the same to GDHM.

**Comment by Nicko2102** [comment]
what is GDHM?

**Comment by totallyphysicallypossible** [comment]
I honestly can't even tell which ones were taken from GDHM, if you're talking about changing the menu color then that's stupid because it's common and most likely has been suggested before GDHM even came out.

also i saw someone stole a suggestion from the repo so that's kinda funny

**Comment by Nicko2102** [comment]
> if you're talking about changing the menu color then that's stupid because it's common and most likely has been suggested before GDHM even came out.

as the one who suggested that i'm not sure when GDHM game out, but i can confirm it was not stolen as i had no idea what GDHM was or that it even existed

**Comment by defaultacc30** [comment]
> I honestly can't even tell which ones were taken from GDHM, if you're talking about changing the menu color then that's stupid because it's common and most likely has been suggested before GDHM even came out.
> 
> also i saw someone steal a suggestion from the repo so that's kinda funny and maybe about a hundred more suggestions stolen from MHV7

no stuff like the horrific failure %

**Comment by totallyphysicallypossible** [comment]
> no stuff like the horrific failure %

what's that lol

**Comment by Nicko2102** [comment]
#474, idk where in GDHM it is though

**Comment by zohnannor** [comment]
I don't see problems here. GDHM is open source? Then as long as Absolute doesn't steal the actual code (which he doesn't), it's fine imo. If people suggest functionality from GDHM to MH, they want it in the *paid* mod even though they know about the *free* one. It would be worse if it was the other way around. IMHO.

**Comment by defaultacc30** [comment]
well for a long time people would suggest mhv7 mods (like layout mode) so adaf put a end to that. and actually, the only reason why I even bought v7 because of smart start pos and layout mode. Now I regret my decisions but thats beside the point, because im not sure it would fly well if I created a checklist and suggested every GDHM mod that isn't in mhv7, while on the gdhm discord server I would be muted.

**Comment by absoIute** [comment]
Did you know GDHM is based on Mega Hack v5, and mods that were originally on v6/v7 have sometimes appeared on GDHM?

**Comment by defaultacc30** [comment]
actually its based on mhv1

**Comment by absoIute** [comment]
You are stupid

**Comment by defaultacc30** [comment]
TPEDA confirmed it not me

**Comment by absoIute** [comment]
I can confirm that is a lie

**Comment by defaultacc30** [comment]
WHAT WHEN

**Comment by defaultacc30** [comment]
ok maybe i shouldnt trust tpdea soon because https://uploadi.ng/oxYH53mB
