### ISSUE TITLE
Allow people to add labels

### ISSUE THREAD

**Issue by defaultacc30** [absoIute/Mega-Hack-Pro-Future#569]
Instead of having 2 people check and add the labels. Allow people to assign labels.

**Comment by MainConMan** [comment]
I remember this being requested before, but I can't find where.

**Comment by NewAlexGamer** [comment]
since there's only one person capable of working on mega hack, putting labels before or after he checks this repository is kind of useless. i'm pretty sure he doesn't get to know what's happening in here until he actually looks at the thing himself
and anyways you have to find people you trust in order to make that happen. we are all randoms here

**Comment by Nicko2102** [comment]
This was adressed briefly in #431 if i'm not mistaken

**Comment by defaultacc30** [comment]
Nah, having its own issue is pretty good

**Comment by Nicko2102** [comment]
> Nah, having its own issue is pretty good

that has nothing to do with what i said but ok

**Comment by zohnannor** [comment]
It's not that easy: AFAIK, at least for this repo, only people selected by the repo owner can manipulate labels/edit titles, close other's issues, etc.

**Comment by defaultacc30** [comment]
@Brittank88 @absoIute what do you think?

**Comment by Nicko2102** [comment]
i dont want to speak for them but stop tagging the repo collaborators in your messages, they'll see it anyway

**Comment by absoIute** [comment]
GitHub doesn't allow for advanced permissions like that, only user & admin roles

**Comment by defaultacc30** [comment]
> GitHub doesn't allow for advanced permissions like that, only user & admin roles

iirc they do? you can create other roles

**Comment by Nicko2102** [comment]
not to be rude, but absolute has been here for a lot longer so i would trust him to know this stuff
