### ISSUE TITLE
Big gap?

### ISSUE THREAD

**Issue by defaultacc30** [absoIute/Mega-Hack-Pro-Future#570]
Ive noticed that #482 and #547 have a big gap, because all the issues between arent available

**Comment by Nicko2102** [comment]
not sure why, but probably isn't a big deal

**Comment by defaultacc30** [comment]
are you sure? i have a bad aura coming off of this

**Comment by defaultacc30** [comment]
ok

**Comment by zohnannor** [comment]
This range of numbers is occupied by pull requests I believe :)

**Comment by defaultacc30** [comment]
no?
