### ISSUE TITLE
MHv7 wont install correctly 

### ISSUE THREAD

**Issue by ConradPhenom** [absoIute/Mega-Hack-Pro-Future#572]
when i click install in the installer it only downloads: XInput9_1_0.dll, discord_game_sdk.dll
please fix this. -ConradPhenom

**Comment by Nicko2102** [comment]
does it say "Successfully installed"
also at the bottom did you include the path to the exe file

**Comment by ConradPhenom** [comment]
yea

**Comment by MainConMan** [comment]
Maybe it's an antivirus issue?

**Comment by absoIute** [comment]
Send a screenshot of your Geometry Dash folder after installing

**Comment by ConradPhenom** [comment]
thers a few more files/folders th
![Screenshot 2022-02-18 094424](https://user-images.githubusercontent.com/89755450/154714810-f4e19c99-7d23-4d97-aeaa-1159bce559f8.jpg)
o

**Comment by absoIute** [comment]
looks like hackpro.dll was deleted by your antivirus. restore & whitelist it from your antivirus. you may have to copy it over from %localappdata% -> Septima -> inst
