### ISSUE TITLE
1.9 GDPS Suggestions

### ISSUE THREAD

**Issue by defaultacc30** [absoIute/Mega-Hack-Pro-Future#574]
Everything that needs to be added to the 1.9 GDPS mod menu cause it is kinda lacking a lot of useful features that doesn't give a unfair advantage.
- [ ] Auto Deafen
- [ ] Ignore ESC
- [ ] Entire Cosmetic Tab
- [ ] Run Info
- [ ] Transition Time
- [ ] Show Hitboxes (Editor Only)
- [ ] Smooth Editor Trail

**Comment by absoIute** [comment]
Not the right place, Discord server is for that, though we already have mostly solid plans for the next 1.9 GDPS update

**Comment by defaultacc30** [comment]
@absoIute I dont have a phone so maybe take these suggestions to the 1.9 GDPS?

**Comment by defaultacc30** [comment]
and have a community vote?

**Comment by absoIute** [comment]
They're already considered like most things in MH for it, community won't vote on them though

**Comment by defaultacc30** [comment]
I guess. But it irritates me that something as useful as run info, or transition time isnt there.

**Comment by defaultacc30** [comment]
> They're already considered like most things in MH for it, community won't vote on them though

hey uh, have you taken the suggestions? will these be added or no

**Comment by absoIute** [comment]
Suggestions are noted, no guarantee of being implemented, please stop being pushy
