### ISSUE TITLE
Fill Hitboxes

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#575]
idea coming from this comment: https://github.com/absoIute/Mega-Hack-Pro-Future/issues/565#issuecomment-1037713566 : basically make an option that when toggled will fill the hitboxes and make them look like the saw ones

for those asking: but hey, if the object is big enough and you somehow end inside the box itself you don't die because you don't touch the hitbox line
but that's where you are wrong because if you actually manage to spawn, via teleport or starpos, inside a hitbox big enough to fit the player without touching the lines, you'll still die
![image](https://user-images.githubusercontent.com/86263500/153772089-a75ef0e3-727a-4154-aa62-b973bc3ca2fa.png)

**Comment by NewAlexGamer** [comment]
i am so fucking stupid

**Comment by Nicko2102** [comment]
lmaoooo
