### ISSUE TITLE
Alpha and Beta Channels

### ISSUE THREAD

**Issue by defaultacc30** [absoIute/Mega-Hack-Pro-Future#576]
Allow for users to download alpha and beta channels of mega hack v7 to test out new features (with the risk of bugs) and give suggestions, this would be useful as in a "final revision state" it would also help fix more bugs before its official release and "tidy up" some features.

**Comment by absoIute** [comment]
Betas already happen prior to final (Gold Master) releases. Alphas are just too unstable for me to want to give them out regularly like that

**Comment by defaultacc30** [comment]
Well, I get that but your missing the point of alpha channels. They are used to give feedback and solve bugs.
