### ISSUE TITLE
advisory against the EARN IT act

### ISSUE THREAD

**Issue by defaultacc30** [absoIute/Mega-Hack-Pro-Future#597]
tweet on your account to repel the EARN it act because it will ruin privacy.

**Comment by defaultacc30** [comment]
NOOOOOO

**Comment by absoIute** [comment]
Please leave relevant suggestions

**Comment by defaultacc30** [comment]
BUT ITS ACTUALLY RELEVANT ITS REALLY IMPORTANT THO

**Comment by absoIute** [comment]
I know but this isn't the place

**Comment by defaultacc30** [comment]
but can you at least make a twitter post about it?

**Comment by Brittank88** [comment]
> but can you at least make a twitter post about it?

This is not relevant to this tracker. The message may be genuine, but regardless, this sort of behaviour will see you not being allowed to create issues.

**Comment by Nicko2102** [comment]
> but can you at least make a twitter post about it?

if it's a twitter post you want, talk about it there
