### ISSUE TITLE
Config Files For Modules/Cheats

### ISSUE THREAD

**Issue by defaultacc30** [absoIute/Mega-Hack-Pro-Future#598]
Allow people to change the config files and add mods to mhv7? Or is this already possible?

**Comment by defaultacc30** [comment]
Also absolute if you wondering, this is not open sourcing mhv7. you can ask adaf for more clues because im tired and lazy

**Comment by Nicko2102** [comment]
what's with you and adaf? also there's a bunch of mods/extensions that use the mega hack config

**Comment by defaultacc30** [comment]
no no

**Comment by defaultacc30** [comment]
i dont mean that, like the config files for the modules/cheats not the extensions

**Comment by Nicko2102** [comment]
oh ok

**Comment by absoIute** [comment]
Found at %localappdata% -> Septima -> options.json

**Comment by Underkirby** [comment]
they are available to edit in C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\data\core.json (I wouldn't recommend editing it though
)

**Comment by absoIute** [comment]
Oh I misread yeah that's it though that'll be removed next update, extensions are the way to go

**Comment by Underkirby** [comment]
i know this isn't related but would there ever be an addition to the extentions.h so that you can toggle on/off specific hacks (some hacks break my extentions)

**Comment by defaultacc30** [comment]
> Found at %localappdata% -> Septima -> options.json

is mhv7 based off of septima?

**Comment by Underkirby** [comment]
what even is septima?

**Comment by absoIute** [comment]
Septima was v7's codename under development, just "seventh" in latin
