### ISSUE TITLE
What happened to show all nodes?

### ISSUE THREAD

**Issue by Underkirby** [absoIute/Mega-Hack-Pro-Future#599]
there used to be a hack called show all nodes that I sometimes used (finding what things are tagged as with the help of cocos-explorer) but I can't find it anywhere even with searching?

**Comment by absoIute** [comment]
Force Visibility, Universal tab

**Comment by Underkirby** [comment]
oh, did it just get renamed

**Comment by absoIute** [comment]
nope, been that way since v5
