### ISSUE TITLE
Z-Layer 0 Bypass

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#6]
Layer 0, despite being supported by the game (check out the older saws, when they are created they have z-layer 0) are not select-able unless they are copied using "copy values".

I propose we make them select-able again. Gives people one extra actually-supported layer to use again.

**Comment by absoIute** [comment]
Will look into this, there may be a good reason support for the layer was removed

**Comment by absoIute** [comment]
added in v6.2-beta3

**Comment by defaultacc30** [comment]
> added in v6.2-beta3

where do i find this?
