### ISSUE TITLE
"Limit icons" option for icon randomizer

### ISSUE THREAD

**Issue by Maritsu** [absoIute/Mega-Hack-Pro-Future#601]
An option for the icon randomizer which limits it to the icons you currently have unlocked (if it's possible)?

**Comment by Nicko2102** [comment]
love this idea :D

**Comment by absoIute** [comment]
added ready for next update

**Comment by Nicko2102** [comment]
will it only be enabled if the icon bypass is off or will it be a separate option?

**Comment by absoIute** [comment]
it’ll be a separate option, but the icon bypass will affect it

**Comment by Nicko2102** [comment]
perfect
