### ISSUE TITLE
Cleaner UI

### ISSUE THREAD

**Issue by defaultacc30** [absoIute/Mega-Hack-Pro-Future#606]
Heres what I mean: https://www.youtube.com/watch?v=q2c8fAtY9GI (yes i take everything from adaf bc why not)

**Comment by Nicko2102** [comment]
for someone who was complaining about MHV7 always using adaf's stuff, you sure are suggesting a lot of adaf's stuff for MHV7

**Comment by defaultacc30** [comment]
> for someone who was complaining about MHV7 always using adaf's stuff, you sure are suggesting a lot of adaf's stuff for MHV7

sad

**Comment by absoIute** [comment]
UI is as "clean" as it needs to be, no major visual overhaul until v8

**Comment by defaultacc30** [comment]
> UI is as "clean" as it needs to be, no major visual overhaul until v8

oh. can you name the v8's codename Eightos?
