### ISSUE TITLE
Song Previewer

### ISSUE THREAD

**Issue by zohnannor** [absoIute/Mega-Hack-Pro-Future#608]
Add a button to play the song from level page:
![image](https://user-images.githubusercontent.com/35764628/154053838-8dfa2fad-a368-4d01-88e6-2ffacb982078.png)

**Comment by Nicko2102** [comment]
genius

**Comment by totallyphysicallypossible** [comment]
im not sure how this would go with sai's modpack but hopefully it does
if it doesn't idk just ask sai to delete that part lol

**Comment by Nicko2102** [comment]
i think he meant with already downloaded songs, like in the editor

**Comment by defaultacc30** [comment]
> i think he meant with already downloaded songs, like in the editor

already there

**Comment by Nicko2102** [comment]
> i think he meant with already downloaded songs, **LIKE** in the editor

**Comment by Nicko2102** [comment]
> > i mean he had to draw it so clearly it's not
> 
> hes meaning on the level page, so it only works with downloaded songs. 

that's my point lol. also, why would it use more GPU?

**Comment by defaultacc30** [comment]
> Obviously you will have to download the song before playing it

so isnt it the same thing as downloading?

**Comment by defaultacc30** [comment]
> no, he's talking about a button that plays the song after it's downloaded, if it's not downloaded then the button won't be visible

so then the title is misinformation.

**Comment by Nicko2102** [comment]
it really isn't. you get to hear the song before playing the level, so it's a preview.

**Comment by absoIute** [comment]
Added ready for next update
