### ISSUE TITLE
Suggestion: Always allow input

### ISSUE THREAD

**Issue by Underkirby** [absoIute/Mega-Hack-Pro-Future#614]
it would always allow keyboard input

**Comment by Nicko2102** [comment]
keyboard input for what? like pressing any key makes you jump?

**Comment by absoIute** [comment]
Is input not already always allowed?

**Comment by Underkirby** [comment]
No, I just wanted to see what happens if you press the arrow keys while
viewing the account stats

**Comment by zohnannor** [comment]
Nothing?

**Comment by Underkirby** [comment]
Nothing but break the game :D

**Comment by absoIute** [comment]
That wouldn't achieve anything other than just a crash or nothing at all
