### ISSUE TITLE
Level Timestamp Bug

### ISSUE THREAD

**Issue by ImmensityHQ** [absoIute/Mega-Hack-Pro-Future#617]
Instead of showing how long a level was uploaded, Vanilla GD displays "Uploaded: NA Ago" (same with level update timestamp).

**Comment by MainConMan** [comment]
There is already a mod for that! https://github.com/matcool/small-gd-mods/releases/tag/mods download timestamp-fix.dll

**Comment by NewAlexGamer** [comment]
> > There is already a mod for that! https://github.com/matcool/small-gd-mods/releases/tag/mods download timestamp-fix.dll
> 
> yeah but just like he did with run info, he embeds it into mh

if you mean to make it an actual hack of the mod menu, he never did that
