### ISSUE TITLE
Game Server/Demonlist/Challenge List API Config Option

### ISSUE THREAD

**Issue by ImmensityHQ** [absoIute/Mega-Hack-Pro-Future#618]
Option to define what APIs MH requests certain information from in the Septima/options.json config file. For example, this could be used in a GDPS that has a custom demon list/challenge list, or to connect to a 2.1 based GDPS.

**Comment by absoIute** [comment]
Probably not something I'd do with the way lists work right now, but I'll add options to disable them & will also be adding new lists in the future
