### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by RealFX-Code** [absoIute/Mega-Hack-Pro-Future#62]
Adding push notifications in GD, Also seen in Mega hack v6 sneak peek would be a cool addition to mhv6.
Allowing extensions use push notifications would be great, and showing one everytime mhv6 updates would be useful imo.

(sorry I don't know how to add labels :( )

**Comment by Brittank88** [comment]
Don't worry about the labels - I don't think the public can add them to their own issues. GitHub has this issues template thing that would allow that to happen, I'll have to look into it.

**Comment by absoIute** [comment]
Specific GD notifications like Messages & Friend Requests isn't something I'd really want to add right now, but v7 now has auto-update messages!
