### ISSUE TITLE
Prevent FPS Bypass From Automatically Updating

### ISSUE THREAD

**Issue by ImmensityHQ** [absoIute/Mega-Hack-Pro-Future#623]
Perhaps add an "Apply Changes" button for FPS bypass, because when you change it the FPS is temporarily very low due to it updating instantly.

**Comment by MainConMan** [comment]
It might be better to not update it until you close the hack menu? That way there is no need for a new button.

**Comment by BrownieGamingX5** [comment]
How would this be useful in some sense?

**Comment by NewAlexGamer** [comment]
to prevent going at 1 or 2 fps for like a couple of seconds while changing it since it's active and we forget to turn it off

**Comment by absoIute** [comment]
FPS Bypass will now only apply when the input box gets deselected (i.e. you click somewhere else or close the menu)
