### ISSUE TITLE
Exact Percentage Fix

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#634]
If you die at a specific percentage and the accurate percentage says ".000%", it doesn't count as you getting it. For an example, you get 25.000% on a level, but the game still counts it as 24%, even the percentage says 25%.

**Comment by Brittank88** [comment]
Btw pretty sure this might be because under the hood it still is 24.000...000<something>%. It's just limited in the display to a certain decimal accuracy.

**Comment by absoIute** [comment]
Yea it always rounded to the nearest decimal instead of rounding down, fix ready for next update
