### ISSUE TITLE
Vim's <n><command here> Command For "StartPos Switcher"

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#642]
do you know when using vim (a text editor) you can press, in command mode, a number followed by the command? let's say you want to go down 10 lines but you don't press 'j' 10 times, you instead type in "10" followed by the j, now you are 10 lines below. this can be applied to startpos switcher too, where if you have a lot of startposes you can press a number and one of the 2 arrows or 'a' or 'd' to move by <n> the startpos
why would this be useful: when practicing heavy object levels it takes a while to load and can sometimes crash the game because you switch from a startpos to another in half a second and you have to go through every single one of them if the startpos you want is kind of far

**Comment by absoIute** [comment]
Don't want to bloat the UI too much with something like this sorry, just want to keep it simple. But if you enable Switch After Death you can solve the lag issue
