### ISSUE TITLE
Challenge List User Whitelist

### ISSUE THREAD

**Issue by ImmensityHQ** [absoIute/Mega-Hack-Pro-Future#643]
Similar to this, but for the challenge list: [https://twitter.com/vipringd/status/1459525997917884418](https://twitter.com/vipringd/status/1459525997917884418).

**Comment by absoIute** [comment]
Not something I'd be able to keep track of, something that needs to be done on Rob's end

**Comment by ImmensityHQ** [comment]
I was thinking the way this could work client-side would be getting the record-holders/verifiers from the challenge list API and just only showing leaderboard records from those accounts.

**Comment by absoIute** [comment]
could be done, if I do i'll just integrate with their API & do the same for the demonlist, problem is getting the right accountID for every account is just a nightmare, so not something i'll do for a while if i do
