### ISSUE TITLE
get browinex5 banned

### ISSUE THREAD

**Issue by whycantfugu14besupportedon142** [absoIute/Mega-Hack-Pro-Future#645]
@absoIute please ban browinex5 from this tracker. https://uploadi.ng/54yyVEPy he made a death threat against me and i have already reported his account. https://discord.com/channels/901239310110564362/901239310110564365/948092500512505857 here is the DM and here is the server invite to prove. https://discord.gg/WcBU3GGFxy. ik this will be marked as invaild but PLEASE get him off of this tracker. its inapporpite behavior.

**Comment by totallyphysicallypossible** [comment]
I can only guess you're defaultacc30 just because you're using uploadi.ng
![image](https://user-images.githubusercontent.com/94307704/156119130-c340f620-61b1-467b-855f-e0d230a2fd4c.png)

**Comment by absoIute** [comment]
no, that is unrelated to the tracker

**Comment by Brittank88** [comment]
"go die" is not a death threat lmao
