### ISSUE TITLE
No-Clip Accuracy Doesn't Activate Cheat Indicator

### ISSUE THREAD

**Issue by OctahedronV2** [absoIute/Mega-Hack-Pro-Future#65]
Obviously, No-Clip Accuracy is a cheat (at least after your accuracy drops below 100%), so it should probably activate the cheat indicator

**Comment by Brittank88** [comment]
My suggestion is to only turn on the indicator if the accuracy falls below 100%. Is there any reason why this is a bad idea @absoIute ?

**Comment by absoIute** [comment]
I like that idea, will add!
