### ISSUE TITLE
"Show Hitboxes" Bugs?

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#653]
i seriously don't know how to explain it, the only thing i can say is that i've done tests and it happens at every speed
https://youtu.be/_-TN0RWM6os

**Comment by Nicko2102** [comment]
I think thet might be because of the screen transitions, there might be one that moves each object in a random direction, and that spasm is just the game choosing a new random direction each time. I could be wrong though

**Comment by NewAlexGamer** [comment]
> Does the bug still happen with force don't fade and force don't enter on?

nop

**Comment by NewAlexGamer** [comment]
oh...
