### ISSUE TITLE
Demon List Stopped Updating

### ISSUE THREAD

**Issue by MainConMan** [absoIute/Mega-Hack-Pro-Future#658]
It seems like the demon list hasn't been updating since February 19th, might be because ErebuS fell off the list, because I know there have been problems with that level in the past, but I could be wrong.
![unknown(5)](https://user-images.githubusercontent.com/95152593/156865960-0d8d425d-fd73-4de7-b2c0-bab93db1fe2d.png)
![2022 Mar 04 22-16-07 0](https://user-images.githubusercontent.com/95152593/156865954-b69d78cc-cdd9-4741-9ef0-7413ff1499df.png)

**Comment by absoIute** [comment]
Updated
