### ISSUE TITLE
FPS Bypass Screen Tearing

### ISSUE THREAD

**Issue by r2crafter** [absoIute/Mega-Hack-Pro-Future#66]
i don't know if it's possible but when using fps bypass could it be possible to remove screen tearing

**Comment by Brittank88** [comment]
I know at least NVIDIA has a VSync option that actually generates frames past the refresh rate but then discards any extras to avoid tearing. maybe that's related here?

**Comment by Brittank88** [comment]
Lmao editing issues on mobile is not fun.
