### ISSUE TITLE
"Auto Music Sync" Doesn't Work In Normal Mode

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#665]
"auto music sync" doesn't work in normal mode unless "corrective music sync" is enabled
the description for the auto music sync says it is affected by corrective music sync, seems kind of a "works if that is enabled too"
ps: in practice it works without corrective music sync

**Comment by absoIute** [comment]
Could you send a screen recording of this?

**Comment by NewAlexGamer** [comment]
well i guess framerate is a problem now...
https://youtu.be/UvxXnC5a1xE

**Comment by absoIute** [comment]
Expected behaviour, Auto Music Sync is only syncing to speed portals that have been used (so only accounting for lag)

Corrective Music Sync makes any music sync (incl pausing then un-pausing) sync to all checked portals

**Comment by NewAlexGamer** [comment]
Ok nice to know, it would be even better if in the description of the hack it was specified instead of a generic "affected by corrective music sync"
