### ISSUE TITLE
Level not saving progress

### ISSUE THREAD

**Issue by TheBigBoiPenguin** [absoIute/Mega-Hack-Pro-Future#667]
Whenever I play a level in my creations tab, it doesn't save my progress when I get a new best. It doesn't even show the "New Best!" popup. I don't have safe mode or no new best popup on. Here are my mhv7 settings: 
![image](https://user-images.githubusercontent.com/96870792/157321980-7ed6a5e1-d257-44e8-8b4d-cd8a40beafb4.png)

This only happens in my levels.

**Comment by absoIute** [comment]
Could you send a screen recording of this happening?

**Comment by TheBigBoiPenguin** [comment]
Weird, it only happens in levels that have start positions in it. (I'm using startpos switcher.)

**Comment by absoIute** [comment]
That's expected behaviour right now, changing next update
