### ISSUE TITLE
0

### ISSUE THREAD

**Issue by chroniqz** [absoIute/Mega-Hack-Pro-Future#67]
i know this is not a valid issue, but i've got myself megahack v6 pro, the payment processed but i still have the checkout button and i cant download it, i've tried dming aboslute on discord but no response and the same thing with the email
![image](https://user-images.githubusercontent.com/89194298/130054772-441602d6-9559-4e11-a648-c7d8af1f3462.png)

**Comment by Brittank88** [comment]
Future reference, maybe it's good to be just a little more patient. I do understand your position, but Absolute has a full life and set of studies to complete, alongside any work he decides to do for MHv6.
