### ISSUE TITLE
FPS Bypass Failure After Update

### ISSUE THREAD

**Issue by VoncreDev** [absoIute/Mega-Hack-Pro-Future#69]
Hey!

Recently FPS Bypass only works if I use an older version of MHV6.

The FPS says its at what i set it as, but the game is still the same!

**Comment by Brittank88** [comment]
Hmm... If the only thing you have done is change the MHv6 solution, then this may actually be a bug.

Would you be able to provide some system specs (CPU, GPU, RAM, Storage, etc.) as well as the state of VSync both in-game and in your graphics card's control panel?
