### ISSUE TITLE
Ability to "Lock" Editor Layers

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#7]
Similar to locking layers in Adobe Photoshop, the ability to lock layers in the editor per-level (such that objects on that layer are not select-able or modifiable via undo) would be very useful for avoiding situations where one must work in the 'all layers' view, or when someone mistakenly messes with something they didn't want to.

**Comment by absoIute** [comment]
May add to Creator Hacks but seems too niche for this
