### ISSUE TITLE
Auto-Deafen Failure

### ISSUE THREAD

**Issue by tmeanstacocat** [absoIute/Mega-Hack-Pro-Future#72]
whenever I bind my discord toggle deafen to f2, and then I make it the same for the mega hack auto deafen key bind, it refuses to deafen and I have tried other key binds along with f2 like alt, shift, a, and spacebar, no matter what I set it to be, it doesn't work. I don't know what to do

**Comment by absoIute** [comment]
Most likely caused by GD or Discord being run as admin and the other not
