### ISSUE TITLE
Icon Level Colours

### ISSUE THREAD

**Issue by Aktimoose** [absoIute/Mega-Hack-Pro-Future#73]
Currently, the only colour you can set the icon to derive from the level is the background colour. My suggestion is that I'd like to be able to pick any colour from the level to use as my icon colour, specifically because I want to use the OBJ colour for a glow.
Another related suggestion I have which I'm not sure is possible is to allow people to change the opacity/blending of their glow, wave trail or spider dash.

**Comment by Aktimoose** [comment]
To add onto the "glow, wave trail or spider dash", I'd also like to add that I'd like it if I could make these particles that show when you're in a dash orb not have blending so black particles could still show

![image](https://user-images.githubusercontent.com/44620677/130346205-00943723-d78c-4308-8529-21242914496a.png)

**Comment by absoIute** [comment]
No Force Glow should disable blending!

**Comment by absoIute** [comment]
Implemented, ready for next update
