### ISSUE TITLE
Cannot Set Shortcut for Options Requiring Confirmation

### ISSUE THREAD

**Issue by Aktimoose** [absoIute/Mega-Hack-Pro-Future#74]
I used to have F11 set to Borderless Fullscreen before a recent update, but then the shortcut got cleared. Whenever I try to set F11 to Borderless Fullscreen now, it sets the shortcut to be the last hack I enabled before that. I'd like to be able to set a shortcut for Borderless Fullscreen again, and [suggestion] I think the confirm dialog should be toggleable.

**Comment by absoIute** [comment]
oops, working on it
