### ISSUE TITLE
Pastel RGB

### ISSUE THREAD

**Issue by LineOwO** [absoIute/Mega-Hack-Pro-Future#78]
Basically RGB color for icons but with pastel colors #

**Comment by Brittank88** [comment]
Being able to apply HSV over the top of the RGB could be a cool way to achieve this.

**Comment by fedqq** [comment]
Doesnt pastel colours already exist?

**Comment by Brittank88** [comment]
...Actually wait yeah I thought for some reason that animated pastel wasn't a thing but that's what that option is so... what exactly did you want that is a new feature @LineOwO ?

**Comment by absoIute** [comment]
exists, will allow customisation of how strong the pastel is in a later update though
