### ISSUE TITLE
Always Show Retry

### ISSUE THREAD

**Issue by H-inq** [absoIute/Mega-Hack-Pro-Future#79]
Just feels like it takes ages when you're slowing down a level to learn it, etc.

**Comment by fedqq** [comment]
I think they mean always show rety button, but since there is an option to set a keybind for it, it would be kinda useless.

**Comment by Brittank88** [comment]
Yeah, that does make it irrelevant, if that's the case. @H-inq feel free to reopen this if you meant something else, but for now, I'm going to close this considering you can just set a keybind.
