### ISSUE TITLE
Certain Keys Unsupported In Keybinds

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#8]
The keys are:
- [ ] Left Alt
- [ ] Right Alt
- [ ] Windows Key
- [ ] SCRL LOCK
- [ ] Tab Keys
- [ ] Menu Key (?) (My laptop has this but my PC keyboard doesn't - maybe just double check if it's supported if possible)

**Comment by absoIute** [comment]
This is expected behaviour, to use ALT in a keybind hit CTRL first
