### ISSUE TITLE
Song Bypass Missing

### ISSUE THREAD

**Issue by MrEmmet66** [absoIute/Mega-Hack-Pro-Future#85]
Song bypass feature isnt showing in menu, so i cant download banned song like theory of skrillex

![image](https://user-images.githubusercontent.com/55745604/131227035-61aa4cd6-611a-48f9-b327-10fce587038c.png)

**Comment by Brittank88** [comment]
Honestly, I'm not sure about this one. Was it ever a thing in MHv6? I'm not familiar with each individual feature in great detail.

...I guess in the meantime you can [fall back on this](https://www.youtube.com/watch?v=g00xx7XTifA)? I know that's not as convenient though.

**Comment by Brittank88** [comment]
@absoIute Are you able to shed light on this, please?

**Comment by absoIute** [comment]
it was visible up to v6.2 but hasn't been functional since December after it was temporarily disabled to reduce server strain, though since then it was patched by Newgrounds so I just removed it, Mega Hack v5 & older versions will just cause an error when downloading any song with it.
