### ISSUE TITLE
Visible cursor bug

### ISSUE THREAD

**Issue by Zixxer17** [absoIute/Mega-Hack-Pro-Future#88]
I'm using MH v.6.3.0-GM2 and while using fullscreen mode in the MH settings and having "Show cursor in game" in game options turned off I'm still seeing cursor when playing a level. 
![Zrzut ekranu 2021-09-01 212012](https://user-images.githubusercontent.com/89939960/131731743-3f5d474f-6137-42b3-aad7-e7457e135115.png)

https://user-images.githubusercontent.com/89939960/131732051-6e17e76c-d486-4ca3-9cf1-01f6fd8c8404.mp4

**Comment by absoIute** [comment]
Do you have any other mods like zBot installed?

**Comment by Zixxer17** [comment]
> Do you have any other mods like zBot installed?

Yes, I have zBot by Fig installed, which also colided with couple features like FPS Bypass

**Comment by absoIute** [comment]
see if it happens without zBot installed, I've had reports that it causes that issue, not Mega Hack

**Comment by Zixxer17** [comment]
After uninstalling the zBot everything works fine, so this error was caused by 2 mods colliding with each other. 
Problem solved.
