### ISSUE TITLE
Odd Overlay Behaviour When Opened Whilst Playing Levels

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#9]
- [ ] If the mouse is hidden, it remains hidden. I believe it should become visible until the overlay is closed again.
- [ ] Users should be able to choose whether the overlay can be opened whilst playing a level, or the shortcut is ignored until they are at least paused.

**Comment by absoIute** [comment]
The mouse now gets shown when enabling the overlay in-levels after the 6.1.0 patch.
Don't think I'll add an option to disable the overlay in-level but will eventually allow users to change the shortcut for convenience and to stop accidental activation, if that happens.
