### ISSUE TITLE
Fullscreen Toggle Data Loss Risk

### ISSUE THREAD

**Issue by Brittank88** [absoIute/Mega-Hack-Pro-Future#91]
Toggling fullscreen can boot you back to the main menu - if you were in the editor and had not yet saved, this completely destroys all progress made since the last save. I lost a large chunk of progress due to this not long ago.

There are two possible ways I can think of to resolve this:
- It performs the fullscreen toggle without modifying where you are in the game or losing any data (awesome).
- It checks if you're in the editor and there are unsaved changes, and warns you to save first (acceptable).

**Comment by absoIute** [comment]
looking into it, will probably just change fullscreen functionality and make it instant

**Comment by absoIute** [comment]
Added warning for next update
