### ISSUE TITLE
Change Online level Stats Jumps and Attemps and

### ISSUE THREAD

**Issue by VIKI155** [absoIute/Mega-Hack-Pro-Future#94]
https://user-images.githubusercontent.com/90156810/132140781-1c965b85-130d-45cf-9d93-432ce5edc175.mp4

**Comment by VIKI155** [comment]
![image](https://user-images.githubusercontent.com/90156810/132141128-f6bc4a6b-9457-4fe6-94a4-e9e21da7dd26.png)

**Comment by absoIute** [comment]
already possible with the variable window -> player -> attempts & jumps, you just need to be playing the level

**Comment by VIKI155** [comment]
Thank you so much :)
