### ISSUE TITLE
Void Clicks

### ISSUE THREAD

**Issue by pHellowWorld** [absoIute/Mega-Hack-Pro-Future#96]
Whenever I try to adjust the volume on my laptop or in-game there's a void click which often messes me up when I try doing a run and I need to lower the volume a bit, might happen to some who's near the end of a level but dies because of it

**Comment by absoIute** [comment]
when did this start happening?

**Comment by pHellowWorld** [comment]
I'm not 100% sure, I don't think it's an issue from the mega hack itself
but an issue from the game, but like I said I don't really remember
how/when it started

**Comment by absoIute** [comment]
alright, will look into it, have you got a consistent way of reproducing it?

**Comment by absoIute** [comment]
ready for next update!
